### ISSUE TITLE
paramater expansion in command word considered an error

### ISSUE THREAD

**Issue by milkmiruku** [zsh-users/zsh-syntax-highlighting#101]
> mv downloads/logos.zip documents/web/project
> $_

Gives a red $_

**Comment by danielshahaf** [comment]
A workaround is to do `alias \$foo=\$foo`, but then `$foo` would be highlighted in green even if its value is not an existing command (e.g., after `foo=/bin/nosuchcommand; alias \$foo=\$foo`, a `$foo` in command position would be green).

**Comment by danielshahaf** [comment]
Note SH_WORD_SPLIT affects the meaning of variable expansions, including those at command position.

**Comment by danielshahaf** [comment]
4fcfb15 fixes this for the (I think) common case of a simple parameter expansion, with no braces or modifiers, when the `zsh/parameter` module has been loaded (appears in the output of `zmodload`).

It doesn't handle SH_WORD_SPLIT, but nobody should be setting that option ;-)
