### ISSUE TITLE
problem with adding built in highlighters - source .zshrc - number expected

### ISSUE THREAD

**Issue by pmalek** [zsh-users/zsh-syntax-highlighting#111]
When adding 
```export ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)```

and trying to source it I get the following 
```$source ~/.zshrc
    /root/.zshrc:42: number expected```

**Comment by danielshahaf** [comment]
Array parameters cannot be exported. Remove the word `export`.
