### ISSUE TITLE
Brackets should be highlighted inside quotes

### ISSUE THREAD

**Issue by thomasst** [zsh-users/zsh-syntax-highlighting#112]
e.g. when posting json data to a server:

```
curl -XPUT localhost -d '{ "hello": { "nested": "data" } }'
```

**Comment by danielshahaf** [comment]
Skipping data inside quotes was added by f1eb5aeef7cf86d69e31deeb915522fef55bfb51 in #63 for #36.

**Comment by worenga** [comment]
i would love to see this feature

**Comment by danielshahaf** [comment]
Patches welcome.  (But this may need a bit of a design work first)
