### ISSUE TITLE
Half-quoted words are not properly handled

### ISSUE THREAD

**Issue by MarkLodato** [zsh-users/zsh-syntax-highlighting#130]
Example:

```
$ echo "one"two'three'
```

This should highlight `"one"` as `double-quoted-argument`, `two` as `default` (I guess?), and `'three'` and `single-quoted-argument`.

To me, this would make zsh-syntax-highlighting super useful, as messing up quotes is one of my most common command-line mistakes.

**Comment by danielshahaf** [comment]
Another example (via @anntzer on #172): `'foo'$bar"baz"` should indicate that `$bar` will be expanded.
