### ISSUE TITLE
Too many builtin widgets are being rebound

### ISSUE THREAD

**Issue by majutsushi** [zsh-users/zsh-syntax-highlighting#137]
After me tracking down a problem with history-incremental-pattern-search-backward to zsh-syntax-highlighting needlessly rebinding the set-local-history widget, Bart Schaefer listed some more builtin widgets that should get excluded from rebinding or treated specially to avoid potential other issues:

http://www.zsh.org/mla/users/2014/msg00308.html

**Comment by danielshahaf** [comment]
The problem goes away if `s/zle set-local-history/zle .set-local-history/` is applied to the reproduction recipe.  This part — a builtin widget that cannot be transparently wrapped — is similar to https://github.com/zsh-users/zsh-syntax-highlighting/issues/150#issuecomment-136414792.  That said, fixing set-local-history would be an upstream bug, and we can certainly stop wrapping it in the meantime with no ill effect.

List of widgets from [Bart's mail (users/18571)](http://www.zsh.org/mla/users/2014/msg00308.html):

- the suffix widgets (auto-*)
- the argument widgets (*-argument|argument-base)
- reset-prompt
- split-undo
- and probably describe-key-briefly and what-cursor-position,
- plus set-local-history

Action items for this issue: check which widgets in the above list should be excluded from wrapping; check if any other widgets need to be excluded; follow up with upstream about `set-local-history` not being transparently wrappable.

**Comment by danielshahaf** [comment]
Disabled wrapping of `set-local-history` in cb5589db739ca6b835e05537f9a35a0cbc168379.

**Comment by danielshahaf** [comment]
There doesn't seem to be any downside to wrapping the other widgets Bart mentioned.  Wrapping `split-undo` does mean that calling split-undo in the middle of a longer widget will update highlighting in the middle of the widget (but possibly not at the end of the widget), for example:

    f() { BUFFER+=\"; zle split-undo; BUFFER+=42\"\ ; CURSOR=$#BUFFER  } ; zle -N f; bindkey ^T f

will highlight the first `"` but not the following `42"` (until something refreshes the highlight).
