### ISSUE TITLE
Prefix form of stdin redirection is highlighted differently/incorrectly

### ISSUE THREAD

**Issue by OmnipotentEntity** [zsh-users/zsh-syntax-highlighting#146]
Given:

    while read i; do echo $i; done < test.txt

"while" "do" and "done" are highlighted in brown, and test.txt is underlined.

Given:

    < test.txt while read i; do echo $i; done

"while" is not highlighted, and "<" is bold red.

**Comment by danielshahaf** [comment]
Issue #161 is a pull request with a proposed patch for this issue.

**Comment by OmnipotentEntity** [comment]
Thanks so much :D
