### ISSUE TITLE
Highlight alias escaped commands like normal commands

### ISSUE THREAD

**Issue by PythonNut** [zsh-users/zsh-syntax-highlighting#147]
A command like `\emacs` is equivalent to `command emacs` and let's the user invoke the command even if there is also an `emacs` alias. Currently, this pattern is not highlighted. Ideally, `zsh-syntax-highlighting` would highlight this in the same way it highlights regular commands.

**Comment by danielshahaf** [comment]
Possibly related:

```
% s=/bin/true
% $s ""
```

highlights $s as an error (presumably because there is no `/usr/bin/'$s'`), rather than as a command.  (I guess the implementation would have to be aware of the setting of SH_WORD_SPLIT.)

**Comment by PythonNut** [comment]
Thanks @danielshahaf!
