### ISSUE TITLE
breaks tab expansion of `xsel -o -b`

### ISSUE THREAD

**Issue by cstrahan** [zsh-users/zsh-syntax-highlighting#154]
Trying to expand `$(xsel -o -b)` results in `xsel: fstat error on stdin: Bad file descriptor`.

See also: https://github.com/zsh-users/zsh-history-substring-search/issues/13

**Comment by danielshahaf** [comment]
Minimal reproduction:

```
$ zsh -f
% f() { builtin zle .expand-or-complete } ; zle -N f; bindkey ^T f 
% echo $(xsel -o -b)<TAB>
xsel: fstat error on stdin: Bad file descriptor
```

Inspecting the `Thingy::widget` objects for `f` and for `expand-or-complete`, I find:

```
(gdb) p *th
$1 = {next = 0x7ffff604c930 <thingies+10160>, nam = 0x6f7e60 "f", flags = 0, 
  rc = 2, widget = 0x707be0, samew = 0x6f7da0}
(gdb) p th->widget->flags
$2 = 0
⋮
(gdb) p *th
$1 = {next = 0x0, nam = 0x7ffff5e3e8c1 "expand-or-complete", flags = 0, 
  rc = 4, widget = 0x7ffff6048b50 <widgets+2000>, 
  samew = 0x7ffff604c728 <thingies+9640>}
(gdb) p th->widget->flags
$2 = 2565
```

Where 2565 is the bitwise-or of:

```
#define WIDGET_INT      (1<<0)	/* widget is internally implemented */
#define ZLE_MENUCMP     (1<<2)	/* DON'T invalidate completion list */
#define ZLE_KEEPSUFFIX  (1<<9)	/* DON'T remove added suffix */
#define ZLE_ISCOMP      (1<<11)	/* usable for new style completion */
```

I suspect this is another instance of the flags problem described at https://github.com/zsh-users/zsh-syntax-highlighting/issues/150#issuecomment-137949400.

**Comment by danielshahaf** [comment]
> Minimal reproduction:
> 
>     $ zsh -f
>     % f() { builtin zle .expand-or-complete } ; zle -N f; bindkey ^T f 
>     % echo $(xsel -o -b)<^T>
>     xsel: fstat error on stdin: Bad file descriptor

The following fixes the minimal example:

```
f() { zle .expand-or-complete }; zle -C f expand-or-complete f ; bindkey ^T f
```

**Comment by danielshahaf** [comment]
https://github.com/zsh-users/zsh/tree/mikachu/redrawhook plus https://github.com/danielshahaf/zsh-syntax-highlighting/tree/mikachu-redrawhook together fix this issue.  (As well as #150 and #183.)

The former is [workers/36650](http://www.zsh.org/cgi-bin/mla/redirect?WORKERNUMBER=36650).

**Comment by danielshahaf** [comment]
> https://github.com/zsh-users/zsh/tree/mikachu/redrawhook plus https://github.com/danielshahaf/zsh-syntax-highlighting/tree/mikachu-redrawhook together fix this issue. (As well as #150 and #183.)

And #90.

**Comment by danielshahaf** [comment]
Fixed in xsel three years ago: https://github.com/kfish/xsel/pull/22.

I'm going to go ahead and close this.  If anyone runs into this and needs a workaround, use the feature/redrawhook branch.  If _that_ isn't good enough, speak up. :)
