### ISSUE TITLE
Assignment to invalid subscript range

### ISSUE THREAD

**Issue by dtch-** [zsh-users/zsh-syntax-highlighting#157]
_fixed by moving the 'source' line above ZSH_HIGHLIGHT[...]_

Here is the full error:
`/home/dtch/.zshrc:94: ZSH_HIGHLIGHT_STYLES: assignment to invalid subscript range`

Here is the syntax portion of the .zshrc

```
# zsh Syntax Highlighting

ZSH_HIGHLIGHT_HIGHLIGHTER=(main)

#ZSH_HIGHLIGHT_STYLES[command]='fg=yellow,bold'
ZSH_HIGHLIGHT_STYLES[alias]='fg=cyan'

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
```

And [the entire .zshrc](http://sprunge.us/OIgg)

**Comment by jmcclell** [comment]
@dtch You ever figure this one out? I know this is 2 years old, but I'm having a hard time finding the right documentation to show me how to override a single color attribute without modifying the files installed by homebrew. Long shot. /sigh

**Comment by OdinsHat** [comment]
@dtch- You unbelievable cretin! Do you know how ill mannered, nasty, cruel, abhorrent and totally against all we stand for as a species to just close something and walk off having solved the problem without telling anyone how they did it?

How selfish can you be?

I hope you die when a Boeing 747 drops half-a-ton of frozen shit on your head from a great height.
