### ISSUE TITLE
vi-mode: visual mode: no background for commands

### ISSUE THREAD

**Issue by blueyed** [zsh-users/zsh-syntax-highlighting#165]
When using vi-keybindings and entering visual mode (`v`), the visual selection gets a background color / standout mode, but this does not work with some parts when using zsh-syntax-highlighting, e.g. commands and invalid command:

In the below screenshot, the whole line is visually selected, but it is not visible for `ls` and `lss`:

![selection_065](https://cloud.githubusercontent.com/assets/9766/7115262/33783f2e-e1e7-11e4-8760-34016619efaa.png)

**Comment by rosshadden** [comment]
:+1:

**Comment by danielshahaf** [comment]
In your example, printing `$region_highlight` from a widget shows:

```
region_highlight=( '0 2 fg=green' '3 6 underline' '7 10 none' '11 12 none' '13 16 fg=red,bold' )
```

Combining that with your screenshot shows reverse video only applies to the portions that have an `fg=…` attribute.

I can reproduce this without zsh-syntax-highlighting:

```
$ zsh -f
% bindkey -v
% f() { region_highlight=('0 2 fg=green' '2 4 underline') }
% zle -N f
% bindkey -a ^T f
% abcdef<Esc>v0<^T>    # cdef in reverse video, ab in green on normal-background-color
```

I reckon zsh itself should show the `ab` in reverse video too.  @blueyed @rosshadden Could you report this to the zsh project?

**Comment by blueyed** [comment]
> Should zsh turn the fg=green to bg=green?

Seems sensible in the case of reverse?!

**Comment by danielshahaf** [comment]
> Seems sensible in the case of reverse?!

It seems both you and I expect `$region_highlight` to be applied first, and the MARK..CURSOR region's highlighting to be applied on top of that. (Yes, the names are confusing.) However, it would not be unreasonable of zle to do things the other way around: first to apply the MARK..CURSOR region's highlighting and then to apply `$region_highlight` on top of that, so widgets can override the MARK..CURSOR region's highlighting.

The MARK..CURSOR's region highlighting, which defaults to `standout` (i.e., reverse video), is specified by `$zle_highlight`.

The man page is silent on the interaction between `$zle_highlight` and `$region_highlight`. I think that should be clarified by upstream. Once it is clarified whose responsibility it is to reverse the video of the `ls` and `lss` (in your example), that party — either zle or zsh-syntax-highlighting — can implement a fix.

Makes sense?

**Comment by danielshahaf** [comment]
[workers/29425](http://www.zsh.org/mla/workers/2011/msg00859.html) also discusses the interaction between `$zle_highlight` and `$region_highlight`.

**Comment by danielshahaf** [comment]
https://github.com/jimmijj/zsh-syntax-highlighting/commit/ece762e81798bc4448bf17f68a4792d1117dc032 fixes this for the special case that `$zle_highlight` contains an explicit `region:…` element. Therefore, a workaround is:

1. Set the default explicitly: `zle_highlight+=( region:standout )`
2. Cherry-pick https://github.com/jimmijj/zsh-syntax-highlighting/commit/ece762e81798bc4448bf17f68a4792d1117dc032.

So, I think the way forward is:

1. Work with `zsh-workers` to document whether `$region_highlight` takes precedence over `$zle_highlight` (current behaviour: it does).
2. Assuming the current behaviour becomes documented upstream, merge @jimmijj's patch, and improve it to have the code do the right thing even when `$zle_highlight` contains no `region:…` element, as is the default. (That patch is part of PR #152.)

**Comment by danielshahaf** [comment]
Proposed fix: https://github.com/danielshahaf/zsh-syntax-highlighting/commit/0e31d6e1a298adfce9596b7048f207c9940d495d

(It's the `i165-region-v1` branch in my repository.)

**Comment by danielshahaf** [comment]
Merged in https://github.com/zsh-users/zsh-syntax-highlighting/commit/51102bf83fdfdca34f5be82eb3cac5518be64305.
