### ISSUE TITLE
some times misses first character

### ISSUE THREAD

**Issue by oryband** [zsh-users/zsh-syntax-highlighting#169]
Some time when I start typing a command, the first characters is ignored:
```zsh
$ d ~/documents/  # i actually typed `cd ~/documents/`
```
This has started since I started using this plugin in two different machines, ubuntu and arch.

**Comment by danielshahaf** [comment]
I presume this doesn't happen under `zsh -f`.

Do you any `bindkey c …` calls in your configuration? Do you source `zsh-syntax-highlighting.zsh` as the last thing in your .zshrc?

**Comment by oryband** [comment]
- what is `-f`? couldn't find it in the `man` or web (never found a good way to search for `-X` arguments as google interprets it as "don't show 'X'"
- now `bindkey`s at all
- highlighting isn't sourced last, but somewhere in the middle
here are my [.zshrc](https://github.com/oryband/dotfiles/blob/06bb1dc8c3e1c666c6da09fe10c6290a51c47970/.zshrc), [.zshenv](https://github.com/oryband/dotfiles/blob/06bb1dc8c3e1c666c6da09fe10c6290a51c47970/.zshenv), and [.zlogin](https://github.com/oryband/dotfiles/blob/06bb1dc8c3e1c666c6da09fe10c6290a51c47970/.zlogin) (i use arch so i `startx` through zlogin). they're not long, perhaps you can find the culprit

thanks a lot! :)

**Comment by danielshahaf** [comment]
> what is -f? couldn't find it in the man or web (never found a good way to search for -X arguments as google interprets it as "don't show 'X'"

It's "ignore (most) user and system dotfiles". See `man zshoptions`. Or make your search query `"zsh -f"` with quotes, in which case the first result gives the answer.

I'm not familiar with oh-my-zsh, but try making `zsh-syntax-highlighting` the last element of the `plugins` array.

**Comment by danielshahaf** [comment]
I'm guessing this is resolved.

**Comment by oryband** [comment]
@danielshahaf sorry for late reply, but i can confirm that since sourcing the plugin last in the plugin list, this problem has gone away

might be worth to mention it in the docs though, it's not obvious for newcomers

**Comment by danielshahaf** [comment]
Reopened. I don't understand what docs change you are proposing?

**Comment by oryband** [comment]
@danielshahaf i meant emphasizing that the zsh-syntax-highlighter should be sourced after all other zsh plugins.

for example, i'm sourcing this plugin using oh-my-zsh. so i have this in my `.zshrc`:
```
plugins=(
    archlinux systemd
    python pip django celery virtualenv virtualenvwrapper
    npm
    go
    aws tugboat
    tmux
    docker
    colored-man colorize web-search
    history-substring-search
    zsh-syntax-highlighting # syntax-highlighting plugin must be sourced last
)
```

**Comment by danielshahaf** [comment]
@oryband https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/README.md already says that (in the installation instructions, and reemphasized in the FAQ later in the file).  What would you change / add?

**Comment by oryband** [comment]
@danielshahaf maybe emphasize it a bit more. Write:
```
The plugin must be sourced last in the plugin list in `~/.zshrc`:
```
instead of:
```
Activate the plugin in ~/.zshrc (in last position):
```

**Comment by danielshahaf** [comment]
@oryband Perhaps this?

```diff
diff --git a/README.md b/README.md
index cb22c37..c14c9df 100644
--- a/README.md
+++ b/README.md
@@ -39,7 +39,7 @@ How to install
         cd ~/.oh-my-zsh/custom/plugins
         git clone git://github.com/zsh-users/zsh-syntax-highlighting.git
 
-* Activate the plugin in `~/.zshrc` (in **last** position):
+* Activate the plugin in `~/.zshrc`:
 
         plugins=( [plugins...] zsh-syntax-highlighting)
 
@@ -47,6 +47,8 @@ How to install
 
         source ~/.zshrc
 
+Note that `zsh-syntax-highlighting` must be the last plugin sourced,
+so make it the last element of the `$plugins` array.
 
 FAQ
 ---
```

Incidentally, the 'at end of .zshrc' requirement may be removed some day, if/when [the redrawhook work](https://github.com/zsh-users/zsh-syntax-highlighting/issues/154#issuecomment-144541575) is merged.

**Comment by oryband** [comment]
@danielshahaf looks good :+1:

**Comment by oryband** [comment]
keep this issue open though, i want to debug the missing char problem and haven't got to it yet

**Comment by danielshahaf** [comment]
> keep this issue open though, i want to debug the missing char problem and haven't got to it yet

Alright.  I suspect history-substring-search might have something to do with it; it duplicates some code from zsh-syntax-highlighting.zsh: https://github.com/robbyrussell/oh-my-zsh/blob/aa15ebad3e9c86fbd8dd5f01803066f82ece9593/plugins/history-substring-search/history-substring-search.zsh#L180

**Comment by oryband** [comment]
@danielshahaf can these two plugins coexist together? history-substring-search says to source itself after zsh-syntax-highlighting. They're contradicting each other!

**Comment by danielshahaf** [comment]
The documentation of h-s-s says it is compatible with z-sy-h.  However, h-s-s relies on undocumented implementation details of z-sy-h (such as the existence of a `_zsh_highlight` function).  That suggests using both at the same time is _possible_ (since h-s-s's docs says so) but _brittle_ (since h-s-s relies on z-sy-h implementation details which may change without notice).

While you're here, are you in contact with h-s-s's authors?  The use of `return true` in their code could be a bug: that statement sets `$?` not to zero but to integer value of the shell parameter `$true`.

**Comment by oryband** [comment]
@danielshahaf i'm not, just an observer. maybe ping them upstream?

**Comment by danielshahaf** [comment]
It's already fixed upstream: https://github.com/zsh-users/zsh-history-substring-search/commit/c61c9956c4b56b4c5363eed6aca653c453764b42

What about your missing character problems, have you got to the bottom of them yet?

**Comment by oryband** [comment]
yup! thanks :)
