### ISSUE TITLE
cursor disapears when moving back along the command

### ISSUE THREAD

**Issue by nicwest** [zsh-users/zsh-syntax-highlighting#171]
![terminal_edited](https://cloud.githubusercontent.com/assets/794070/7794698/0244731a-02c5-11e5-9bb2-702dbdd5c729.gif)

```bash
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
```

steps to reproduce:
1. open gnome-terminal under ubuntu
2. enter command
3. press the left arrow key (←)

I'm noticing that on gnome-terminal on ubuntu 15.04 that when I move back along a previous typed command the cursor disappears.

In tmux 1.9 the cursor is visible but it displays the character under cursor in italics (this may be intended, I'm unsure).

I have also experienced this issue with arch on urxvt, but identical config files on OSX seems to work fine.

**Comment by nicwest** [comment]
removing the `cursor` highlighter fixed this issue.

Doh

**Comment by phunehehe** [comment]
I just noticed this too. Strange that I only see this in gnome-terminal and not konsole. Makes me wonder the intended use case for the `cursor` highlighter though.

**Comment by danielshahaf** [comment]
`gnome-terminal` has a blinking cursor. The blinking cycle restarts whenever the cursor is moved. I'm guessing what happens is: you press <kbd>←</kbd> several times quickly; each press restarts the cursor blinking cycle; the cycle starts with the cursor in black, but the default cursor highlighting, which is `standout`, applies on top of that and makes the cursor _transparent_ for the first half of the cycle; so, the end result is the cursor is transparent until half a second after it stops moving.

You could try:

```zsh 
typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[cursor]=underline
```

**Comment by phunehehe** [comment]
@danielshahaf you are right about everything :)
I'm not sure what the `cursor` highligher brings to the table, though. The docs doesn't say anything and with your snippet, it behaves just like `cursor` is disabled. Can you give an example?

**Comment by danielshahaf** [comment]
@phunehehe A simple example is:

```zsh
% ZSH_HIGHLIGHT_HIGHLIGHTERS=(main cursor)
% typeset -A ZSH_HIGHLIGHT_STYLES    
% ZSH_HIGHLIGHT_STYLES=(cursor bold)
% source zsh-syntax-highlighting.zsh
```

to make the character under the cursor bold.  See ["Character Highlighting" in zshzle(1)](http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#Character-Highlighting) for the available highlighting styles.  I'm guessing the default  (which is `standout`, i.e., reverse video) is useful to turn a "vertical bar" cursor into a "box" cursor without changing the terminal emulator's configuration.

**Comment by phunehehe** [comment]
thanks, that surely clears things up!
