### ISSUE TITLE
highlighting concatenated strings and expansions

### ISSUE THREAD

**Issue by anntzer** [zsh-users/zsh-syntax-highlighting#172]
The parser seems to choke a bit on `echo 'foo'$f'bar'`.  I don't care much whether it should be highlighted like `echo 'foo' $f 'bar'` or `echo 'foo' "$f" 'bar'`, but it'd be nice to show that `$f` is indeed subject to expansion.

**Comment by danielshahaf** [comment]
Similarly with `'foo'"$bar"` and `foo"$bar"` other pastings --- the parser only looks at the first character.

**Comment by danielshahaf** [comment]
Closing as duplicate of #130

**Comment by danielshahaf** [comment]
Thanks for reporting the problem! I've copied your comment over to the other issue.
