### ISSUE TITLE
incorrect highlighting of array definitions

### ISSUE THREAD

**Issue by anntzer** [zsh-users/zsh-syntax-highlighting#178]
`a=(foo bar)` confuses the parser (it thinks `foo` is a (nonexistent) command).

**Comment by danielshahaf** [comment]
This patch fixes it:

```
diff --git a/highlighters/main/main-highlighter.zsh b/highlighters/main/main-highlighter.zsh
index 5b038b4..1c0ff17 100755
--- a/highlighters/main/main-highlighter.zsh
+++ b/highlighters/main/main-highlighter.zsh
@@ -125,7 +125,10 @@ _zsh_highlight_main_highlighter()
         *': hashed')    style=$ZSH_HIGHLIGHT_STYLES[hashed-command];;
         *)              if _zsh_highlight_main_highlighter_check_assign; then
                           style=$ZSH_HIGHLIGHT_STYLES[assign]
-                          new_expression=true
+                          if [[ $arg[-1] != '(' ]]; then
+                            # scalar assignment, an array assignment
+                            new_expression=true
+                          fi
                         elif _zsh_highlight_main_highlighter_check_path; then
                           style=$ZSH_HIGHLIGHT_STYLES[path]
                         elif [[ $arg[0,1] == $histchars[0,1] || $arg[0,1] == $histchars[2,2] ]]; then
```

**Comment by anntzer** [comment]
@danielshahaf I see that you have a few patches lying around in the bug tracker as well as in your personal fork; do you plan to merge all of them in a single branch that I could use instead of the official plugin?  Thanks.

**Comment by danielshahaf** [comment]
> @danielshahaf I see that you have a few patches lying around in the bug tracker as well as in your personal fork; do you plan to merge all of them in a single branch that I could use instead of the official plugin? Thanks.

I'm a bit busy currently but I'll try and prepare an integrated branch over the weekend. Thanks for the prod.

**Comment by danielshahaf** [comment]
> @danielshahaf I see that you have a few patches lying around in the bug tracker as well as in your personal fork; do you plan to merge all of them in a single branch that I could use instead of the official plugin? Thanks.

Here is the combined branch: https://github.com/zsh-readable/zsh-readable

**Comment by danielshahaf** [comment]
... And here's a pull request form of the above patch.  As stated in the pull request (#179), it also includes a regression test.

**Comment by anntzer** [comment]
Thanks!

**Comment by danielshahaf** [comment]
@anntzer You're welcome. In the meantime, however, I have been granted push access to the zsh-users/zsh-syntax-highlighting repository (this repository), so I no longer have to maintain an integrated branch elsewhere; I plan to merge the fix to this issue to this repository.

(Thanks to @sorin-ionescu for granting me access.)
