### ISSUE TITLE
Wrap 'yank' (was: Unbreak yank-pop)

### ISSUE THREAD

**Issue by danielshahaf** [zsh-users/zsh-syntax-highlighting#183]
The problem with `yank-pop` (issue #99, PR #143) is probably caused by the flags issue described in https://github.com/zsh-users/zsh-syntax-highlighting/issues/150#issuecomment-137949400.

Once `zle -f` / `zle -P` is in zsh, remove `yank-pop` from the list of widgets-not-to-wrap and check whether it functions correctly when wrapped.

**Comment by danielshahaf** [comment]
The patch in https://github.com/zsh-users/zsh-syntax-highlighting/issues/150#issuecomment-144390545 fixes this issue too.

> Confirmed: [Mikael's workers/36709](http://www.zsh.org/cgi-bin/mla/redirect?WORKERNUMBER=36709) plus https://github.com/danielshahaf/zsh-syntax-highlighting/commit/bfa71c983fa6c3b43cc657276223410123d5c145 fix this issue.

**Comment by danielshahaf** [comment]
Commit 766b350a7d346374e8945a0644825953fc202181 makes highlighting works after `yank-pop`.  However, `yank-pop` is currently a no-op because `yank` is wrapped.  There are three options to fix this:

- Merge the `zle -f` patch mentioned in the previous comment;
- Merge the redrawhook work (https://github.com/zsh-users/zsh-syntax-highlighting/issues/154#issuecomment-144541575);
- Avoid wrapping `yank` (revert 8e7c26f489f952213bbb269a0570384184c0f6fe).

**Comment by danielshahaf** [comment]
Commit f48f5400c1faa875fed810f70fb57dfa506b977b fixes the regression.  Leaving this issue open to track wrapping the `yank` widget.

**Comment by adamchainz** [comment]
I'm still experiencing an issue where `yank-pop` doesn't work more than once, and I have found that not wrapping it fixes it:

```patch
diff --git a/zsh-syntax-highlighting.zsh b/zsh-syntax-highlighting.zsh
index 6838e1d..561ac81 100644
--- a/zsh-syntax-highlighting.zsh
+++ b/zsh-syntax-highlighting.zsh
@@ -305,7 +305,7 @@ _zsh_highlight_bind_widgets()
 
   # Override ZLE widgets to make them invoke _zsh_highlight.
   local -U widgets_to_bind
-  widgets_to_bind=(${${(k)widgets}:#(.*|run-help|which-command|beep|set-local-history|yank)})
+  widgets_to_bind=(${${(k)widgets}:#(.*|run-help|which-command|beep|set-local-history|yank|yank-pop)})
 
   # Always wrap special zle-line-finish widget. This is needed to decide if the
   # current line ends and special highlighting logic needs to be applied.

**Comment by danielshahaf** [comment]
Seems to work in current master using zsh 5.7.1 (didn't check older versions).
