### ISSUE TITLE
_zsh_highlight_widget_up-line-or-history: job table full or recursion limit exceeded

### ISSUE THREAD

**Issue by programes** [zsh-users/zsh-syntax-highlighting#197]
When I use TAB, the terminal will appear ‘_zsh_highlight_widget_up-line-or-history: job table full or recursion limit exceeded’

**Comment by programes** [comment]
And when I use the direction key in order to use the history,the terminal will appear '_zsh_highlight_widget_history-search-forward: job table full or recursion limit exceeded'

**Comment by programes** [comment]
And under the terminal using copy and paste will appear this kind of situation

**Comment by programes** [comment]
And under the terminal using copy and paste will appear this kind of situation

**Comment by danielshahaf** [comment]
What version of zsh-syntax-highlighting do you use?

Could you please bisect your configuration?  That is, provide a minimal sequence of commands, starting from `zsh -f`, that still reproduces the problem?  That sequence would probably be a minimized form of your `.zshrc`.

What does `print -r - $widgets[up-line-or-history]` print?

**Comment by danielshahaf** [comment]
I just now noticed: TAB isn't normally bound to up-line-or-history, nor arrows to history-search-forward. So it seems your terminal sends different escape sequences than zle expects.

Anyway, feel free to reopen if you're still seeing the problem.
