### ISSUE TITLE
Bell on every keystroke

### ISSUE THREAD

**Issue by fenhl** [zsh-users/zsh-syntax-highlighting#200]
Whenever I type something, I get a bell character back. Might be related to #92, but I am not using any custom configuration.

**Comment by jaaaaaaaaaam** [comment]
+1 getting this also, fresh install

**Comment by timkurvers** [comment]
Same behaviour here on OSX 10.10.5. Git bisected it to [this commit](e5c2a88db023600d7aeacbb2b7d640e0c8671a83).

**Comment by timkurvers** [comment]
Have a feeling this could be related to the comment in that commit:

> YANK_ACTIVE is only available in zsh-5.1.1 and newer

Version of zsh on my machine:

> zsh 5.0.5 (x86_64-apple-darwin14.0)

**Comment by jaaaaaaaaaam** [comment]
[~] zsh --version
    zsh 5.1.1 (x86_64-apple-darwin14.5.0)

Just upgraded to 5.1.1 via brew and the problem still exists

**Comment by jaaaaaaaaaam** [comment]
git reset --hard 0e31d6e

reverted to 0e31d6e for now until there is a fix

**Comment by danielshahaf** [comment]
Thanks for the bug report. That commit was pushed only yesterday :)

Please check if https://github.com/danielshahaf/zsh-syntax-highlighting/commit/c63293a9a67acf55c59dcd5284f0dfb5a7981e16 fixes the problem:

```zsh
git remote add danielsh https://github.com/danielshahaf/zsh-syntax-highlighting
git fetch danielsh
git checkout master
git merge danielsh/i200-bell-due-to-yank_active
```

**Comment by danielshahaf** [comment]
> Please check if danielshahaf@c63293a fixes the problem:

I assume bells are caused by a widget (= the logic that a keypress invokes) returning non-zero.  That commit makes _all_ widgets return zero, so I think it will disable bells completely (even on operations that normally do cause a bell).  Is that the behaviour you observe?

**Comment by danielshahaf** [comment]
Please try danielshahaf@00862cf4fa6a (the `i200-bell-due-to-yank_active-v2` branch).

**Comment by danielshahaf** [comment]
Thanks to @blueyed's comment I have reproduced the issue and confirmed that danielshahaf@00862cf fixes it.  I have now pushed that to master.

**Comment by hackedbellini** [comment]
@danielshahaf your branch really fixes the issue, but why isn't it yet merged [here](https://github.com/zsh-users/zsh-syntax-highlighting)?

**Comment by danielshahaf** [comment]
@hackedbellini Which branch?  I posted two branches on the issue and merged the second of them 10 days ago: 00862cf4fa6a3613e71f3aba4edc079796440205

Are you still seeing an issue with latest master (7b4598a76495af2e2140be2d7c289a77c654ee8c)?

**Comment by hackedbellini** [comment]
@danielshahaf yes. The `master` branch of `zsh-users/zsh-syntax-hightlight` still has issues for me. Checking out the `i200-bell-due-to-yank_active-v2` branch made it disappear.

Fell free to ask me to test anything you need.

**Comment by danielshahaf** [comment]
@hackedbellini What version of zsh do you use?  Does it happen under `zsh -f` + `source zsh-syntax-highlighting.zsh`?  Could you bisect master (using `git bisect`) to trace the relevant commit?

I suspect you might be seeing a separate bug that has the same symptoms as this one.

Feel free to catch me on IRC (#zsh-syntax-highlighting on freenode) — we can iterate faster there.
