### ISSUE TITLE
Recent push broke plugin with _zsh_highlight:typeset:86: not valid in this context: <char>

### ISSUE THREAD

**Issue by wldcordeiro** [zsh-users/zsh-syntax-highlighting#206]
Appears that some change has broken the plugin, not sure what exactly from the looks of recent commits but some context is causing an error and every character typed will show that error.

**Comment by danielshahaf** [comment]
Sorry about that — please update to dd12dde93a83b2863a4ff05440ec1fb7e82af9a6 and try again.

**Comment by wldcordeiro** [comment]
Awesome! Nice quick turnaround too. :+1:
