### ISSUE TITLE
Main highlighter fighting with antigen/zgen in Cygwin

### ISSUE THREAD

**Issue by christopherbahr** [zsh-users/zsh-syntax-highlighting#211]
Recently as soon as  I tab complete anything in a terminal session I start getting messages saying

"[main] zsh PID child_info_fork::abort:address space needed by 'computil.dll' (0x570000) is already occupied" 
then on the following line
"_zsh_highlight_main_highlighter:79. fork failed: resource temporarily unavaliable"

From there on out it throws that same error on every character I type

Minimal .zshrc
```
source ~/antigen/antigen.zsh
antigen bundle zsh-users/zsh-syntax-highlighting
antigen apply
```
I can also reproduce with no .zshrc using
```
source ~/antigen/antigen.zsh
antigen apply
source zsh-syntax-highlightyng/zsh-syntax-highlighting.zsh
```
zgen has the same problem but if I use no .zshrc at all and source zsh-syntax-highlighting.zsh directly syntax highlighting and tab completion work fine.

I'm running Windows 7, zsh 5.0.8 on cygwin, in mintty

**Comment by danielshahaf** [comment]
> Recently as soon as I tab complete anything in a terminal session I start getting messages saying

Did you upgrade cygwin or anything zsh-related recently?

> "_zsh_highlight_main_highlighter:79. fork failed: resource temporarily unavaliable"

Presumably that's the `local res="$(…)"` line?  You don't mention what version of zsh-syntax-highlighting you use so I amn't sure.

There was a similar issue reported at https://github.com/babun/babun/issues/263.  Does the workaround there (using the antivirus' whitelist) apply?

**Comment by christopherbahr** [comment]
I couldn't use the AV whitelist (unfortunately I don't control the AV on this machine) but rebaseall http://cygwin.wikia.com/wiki/Rebaseall saved me. Thanks for pointing me in the right direction :+1:
