### ISSUE TITLE
Github version keep making alert when input

### ISSUE THREAD

**Issue by fuxialexander** [zsh-users/zsh-syntax-highlighting#212]
With the newest version cloned from Github, I got an alert whenever I input a character. While using the released 0.2.1 has no such problem.
> Mac OS X 10.11
> iTerm 2 nightly
> Zsh + Oh My Zsh
> No customization on the highlighting style

**Comment by danielshahaf** [comment]
That's not enough information to reproduce, identify, or fix the problem.

You can do two things: either bisect the zsh-syntax-highlighting history to determine the first problematic commit, or bisect your configuration to find a minimal coniguration that still reproduces the problem.  For starters, does the problem occur under `zsh -f` followed by `source zsh-syntax-highlighting.zsh`?

What versions of zsh and zsh-syntax-highlighting do you use?

**Comment by danielshahaf** [comment]
... or perhaps run `functions -t _zsh_highlight_widget_self-insert` to trace the widget.

**Comment by fuxialexander** [comment]
Eh...Not sure what happened, but the problem seems disappeared after a remove-reclone...

**Comment by danielshahaf** [comment]
Okay.  If it recurs, feel free to reopen.  Thanks for the report.
