### ISSUE TITLE
$REPLY is leaked

### ISSUE THREAD

**Issue by vaeth** [zsh-users/zsh-syntax-highlighting#213]
In some cases, the variable $REPLY is leaked into the interactive environment; I suppose it should be declared as local somewhere.

It is particularly annoying that this variable contains in some cases the current directory so that (at least with the prompt function that I use) the text $REPLY is displayed instead of the current directory...

**Comment by danielshahaf** [comment]
Fixed, thanks.

Incidentally, you might consider an explicit `unset REPLY` to the beginning of your prompt function, to ensure you don't use lingering values of that parameter.

**Comment by vaeth** [comment]
Thanks for fixing.

Maybe concerning the prompt function there is a misunderstanding: Already PROMPT='%~' displays the text "~REPLY"  if REPLY contains the current directory (perhaps only if certain zsh options are set or unset). In particular, there is nothing special about the name "REPLY" in this function; any leaking variable containing the current directory would have the same effect.

Of course, as a hackish temporary fix, I could have unset REPLY, but I consider it a lucky accident that my prompt reveiled this bug, since I suppose the variables of the user and of prompt/completion/highlighting functions should never be able to collide (unless explicitly documented e.g. as an "interface").

**Comment by danielshahaf** [comment]
I see.  Indeed I misunderstood: I assumed your prompt included $REPLY literally (as in `PS1='$REPLY%#' `), in which case `unset REPLY` would have been a correct fix, not a hackish one.

$REPLY is documented in zshparam(1) as an idiomatic way of returning a string from one shell function to another, so leaking it would have had few adverse effects compared to leaking any other parameter.

I believe the behaviour you saw is triggered by the AUTO_NAME_DIRS option.
