### ISSUE TITLE
Problem activating the plugin

### ISSUE THREAD

**Issue by atomic** [zsh-users/zsh-syntax-highlighting#220]
Using oh-my-zsh, appending zsh-syntax-highlighting at the end in plugins=(... ) has no effect.
Alternatively, placing "source ~/.oh-my-zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" at the end of .zshrc will result in following errors when new zsh shell is started, and hanged. I also has defined my highlighting by placing 'ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)' in my .zshrc.

```
_zsh_highlight_load_highlighters:pwd:13: too many arguments
zsh-syntax-highlighting: 'brackets' highlighter should define both required functions '_zsh_highlight_brackets_highlighter' and '_zsh_highlight_brackets_highlighter_predicate' in '/home/atomic/.oh-my-zsh/plugins/zsh-syntax-highlighting/highlighters/brackets//brackets-highlighter.zsh'.
_zsh_highlight_load_highlighters:pwd:13: too many arguments
zsh-syntax-highlighting: 'cursor' highlighter should define both required functions '_zsh_highlight_cursor_highlighter' and '_zsh_highlight_cursor_highlighter_predicate' in '/home/atomic/.oh-my-zsh/plugins/zsh-syntax-highlighting/highlighters/cursor//cursor-highlighter.zsh'.
_zsh_highlight_load_highlighters:pwd:13: too many arguments
zsh-syntax-highlighting: 'line' highlighter should define both required functions '_zsh_highlight_line_highlighter' and '_zsh_highlight_line_highlighter_predicate' in '/home/atomic/.oh-my-zsh/plugins/zsh-syntax-highlighting/highlighters/line//line-highlighter.zsh'.
_zsh_highlight_load_highlighters:pwd:13: too many arguments
zsh-syntax-highlighting: 'main' highlighter should define both required functions '_zsh_highlight_main_highlighter' and '_zsh_highlight_main_highlighter_predicate' in '/home/atomic/.oh-my-zsh/plugins/zsh-syntax-highlighting/highlighters/main//main-highlighter.zsh'.
_zsh_highlight_load_highlighters:pwd:13: too many arguments
zsh-syntax-highlighting: 'pattern' highlighter should define both required functions '_zsh_highlight_pattern_highlighter' and '_zsh_highlight_pattern_highlighter_predicate' in '/home/atomic/.oh-my-zsh/plugins/zsh-syntax-highlighting/highlighters/pattern//pattern-highlighter.zsh'.
_zsh_highlight_load_highlighters:pwd:13: too many arguments
zsh-syntax-highlighting: 'root' highlighter should define both required functions 
```

The error persists and can only be stopped by closing terminal.

**Comment by danielshahaf** [comment]
There is no `pwd` call on line 13 of `_zsh_highlight_load_highlighters`, or anywhere else in the source tree (!).  Can you please run `git rev-parse HEAD` in your zsh-syntax-highlighting working copy and report the output?  (As well as whether `git status` is clean.)

Does the error happen if you run `zsh -f` and therein `source zsh-syntax-highlighting.zsh`?

**Comment by atomic** [comment]
`git rev-parse HEAD` gives `57624bb9f64b88c633c03df986f73a45512eb60b`
`git status` gives
```
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
```

**Comment by danielshahaf** [comment]
That git output is fine  Does the error happen if you run `zsh -f` and therein run `source zsh-syntax-highlighting.zsh`?

**Comment by atomic** [comment]
hmm, if i run `zsh -f` first, and source the plugin, it works. But it the source doesnt work in my normal zsh. conflicts with other plugins?

**Comment by atomic** [comment]
oh, it works now if i put `zsh-syntax-highlighting` at the end of `plugin=(.... zsh-...)`. I think I might've spelled it wrong previously.

**Comment by danielshahaf** [comment]
@atomic Glad it works now! Thanks for following up and describing the cause and solution of the problem.
