### ISSUE TITLE
parse error near `&&'

### ISSUE THREAD

**Issue by lambdalisue** [zsh-users/zsh-syntax-highlighting#225]
https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/highlighters/main/main-highlighter.zsh#L197

With zsh 5.0.2, zsh installed via `apt-get`, in Ubuntu server 14.04 (64 bit) raise the following exception

> XXXX/zsh-syntax-highlighting/highlighters/main//main-highlighter.zsh:197 parse error near `&&'
> zsh-syntax-highlighting: 'main' highlighter should define both required functions '_zsh_highlight_main_highlighter' and '_zsh_highlight_main_highlighter_predicate' in XXX

Maybe `${interactive_comments+'set'}` part?

**Comment by danielshahaf** [comment]
Does adding `-n` fix it?  That is, make the condition read:

```zsh
[[ -n ${interactive_comments+'set'} && $arg[1] == $histchars[3] ]]
```

Feel free to join #zsh-syntax-highlighting on freenode to iterate there.

**Comment by danielshahaf** [comment]
Or, another option:

```zsh
(( ${+interactive_comments} )) && [[ $arg[1] == $histchars[3] ]]
```

**Comment by lambdalisue** [comment]
@danielshahaf Thanks for quick reply. Adding `-n` solve problem. Looking forward the next commit :-)

**Comment by danielshahaf** [comment]
Thanks for the report @lambdalisue!

**Comment by lambdalisue** [comment]
Thanks a lot @danielshahaf :smile:

**Comment by lambdalisue** [comment]
I confirmed. Thanks again :-)

**Comment by danielshahaf** [comment]
You're most welcome.  Feel free to yell at me directly on #zsh-syntax-highlighting on freenode, if I ever break it again :-).
