### ISSUE TITLE
ANSI C quoting support

### ISSUE THREAD

**Issue by anntzer** [zsh-users/zsh-syntax-highlighting#229]
a.k.a
```
$ echo $'foo\nbar'
foo
bar
```

**Comment by danielshahaf** [comment]
The `\n` is already highlighted, as of 69fcb40275dc7dbc51f46097483cb1328db16686 which was released in 0.3.0.

**Comment by anntzer** [comment]
Oops, sorry.  I ran antigen update but I needed to restart the shell as well.
