### ISSUE TITLE
syntax-highlighting causing segfaults in 5.0.5

### ISSUE THREAD

**Issue by ziegs** [zsh-users/zsh-syntax-highlighting#230]
Per https://github.com/sorin-ionescu/prezto/issues/1026, enabling zsh-syntax-highlighting plugin causes a segmentation fault immediately. The entire zshrc is shown as being parsed when running zsh --verbose, it's crashing right before the prompt is shown.

**Comment by danielshahaf** [comment]
I'll be happy to merge fixes.  Is there a reproduction recipe that doesn't involve prezto?

**Comment by ziegs** [comment]
Doesn't look like it at the minute. I'm trying to isolate which of the calls in Sorin's theme file is triggering this.

**Comment by danielshahaf** [comment]
The other issue has determined that the problem goes away if prezto changes `zle reset-prompt` to `zle .reset-prompt`, which presumably bypasses the `_zsh_highlight_bind_widgets`-added wrapper.
