### ISSUE TITLE
driver: Reset zshoptions to known values

### ISSUE THREAD

**Issue by danielshahaf** [zsh-users/zsh-syntax-highlighting#233]
As per https://github.com/zsh-users/zsh-syntax-highlighting/issues/162#issuecomment-157224594: run `emulate -L zsh` (or `-LR`?) in `zsh-syntax-highlighting.zsh`, after saving the options set on entry and making them available to highlighters which need them.

**Comment by phy1729** [comment]
This was done in b07ada1.
