### ISSUE TITLE
zsh: can't set tty pgrp: Input/output error

### ISSUE THREAD

**Issue by lencioni** [zsh-users/zsh-syntax-highlighting#246]
I recently updated prezto which caused zsh to freeze with the message "zsh: can't set tty pgrp: Input/output error" when starting up in tmux. When opening a new shell, it just closes immediately. Using `git bisect` I was able to determine that my problem starts with 59fbdda but I don't actually see why. Any thoughts?

Running zsh 5.0.5 (x86_64-apple-darwin14.0)

Some more discussion at https://github.com/sorin-ionescu/prezto/issues/1033

**Comment by danielshahaf** [comment]
No idea off the top of my head.  

Two thoughts:

1. This may be a bug in zsh itself, not in zsh-syntax-highlighting.  Can you
try a more recent zsh version?  (The latest is 5.1.1, with 5.1.2 expected to be
announced tomorrow.)   For reference, here is [zsh's changelog](https://github.com/zsh-users/zsh/blob/master/ChangeLog); 5.0.5 occurred on 2014-01-05.

2. In the meantime, you may work around this by wrapping the `accept-line` widget (this takes advantage of #203 not having been fixed yet), by doing

```zsh
accept-line() { zle .$WIDGET "$@" }
zle -N accept-line
```

in your `.zshrc` before loading zsh-syntax-highlighting (either directly or through prezto).

Thanks for bisecting!

**Comment by danielshahaf** [comment]
Also, you say the shell closes _immediately_, before any input to it is done?  The change is in widget code, so the code that was changed shouldn't even be executed before the first interactive keypress.

**Comment by lencioni** [comment]
Yep, it closes immediately before any input to it is done. Here's a gif I recorded of it happening :)

![zsh](https://cloud.githubusercontent.com/assets/195534/11515540/56eb0452-9833-11e5-887a-1b5991246277.gif)

I'll try your two thoughts soon.

**Comment by lencioni** [comment]
Thanks for the suggestions! Unfortunately they didn't seem to do the trick.

> This may be a bug in zsh itself, not in zsh-syntax-highlighting. Can you try a more recent zsh version?

Same problem with zsh 5.1.1

> In the meantime, you may work around this by wrapping the accept-line widget

I added the code you posted to the top of my `.zshrc` file before anything was done, and it also did not fix this problem.

**Comment by danielshahaf** [comment]
Does the error happen if you start zsh as `zsh -f` and then `source zsh-syntax-highlighting.zsh`?

The error is from [the C function `attachtty()`](https://github.com/zsh-users/zsh/blob/ebb0d7ddaad8a0720a062d42de388320dd0e7f53/Src/utils.c#L4297).  z-sy-h doesn't do anything fancy with background processes; does your setup? 

And just to be thorough, could you test [zsh-5.1.1-test-3](http://www.zsh.org/pub/development/) (a prerelease of 5.1.2)?  I don't recall specific fixes in this area, but one could easily have passed under my radar.

**Comment by danielshahaf** [comment]
Can you try 6cdc44b (`i246-zpty/debugging-v1` branch in my personal clone)?  And if it doesn't reproduce the error, try changing the `true` and `false` to `/usr/bin/true` and `/usr/bin/false` respectively and see if it _then_ reproduces the error.

**Comment by lencioni** [comment]
> Does the error happen if you start zsh as `zsh -f` and then source `zsh-syntax-highlighting.zsh`?

If I start zsh as `zsh -f` and then source my `.zshrc` things are fine... until I hit Ctrl+C and then it segfaults. 

```
[1]    16059 segmentation fault  zsh -f
```

> z-sy-h doesn't do anything fancy with background processes; does your setup?

Not that I am aware of, but there might be something in prezto that does. If you feel like poking around, my dotfiles are at https://github.com/lencioni/dotfiles

> And just to be thorough, could you test zsh-5.1.1-test-3 (a prerelease of 5.1.2)? 

At this point I think I'll just wait for 5.1.2.

> Can you try 6cdc44b (`i246-zpty/debugging-v1` branch in my personal clone)?

That does not reproduce the error.

> And if it doesn't reproduce the error, try changing the `true` and `false` to `/usr/bin/true` and `/usr/bin/false` respectively and see if it then reproduces the error.

That also does not reproduce the error. 

```diff
diff --git a/highlighters/main/main-highlighter.zsh b/highlighters/main/main-highlighter.zsh
index ee97c0a..f211f7f 100644
--- a/highlighters/main/main-highlighter.zsh
+++ b/highlighters/main/main-highlighter.zsh
@@ -60,7 +60,7 @@
 _zsh_highlight_main_highlighter_predicate()
 {
   # accept-* may trigger removal of path_prefix highlighting
-  false ||
+  /usr/bin/false ||
     _zsh_highlight_buffer_modified
 }

@@ -283,7 +283,7 @@ _zsh_highlight_main_highlighter_check_path()

   # If this word ends the buffer, check if it's the prefix of a valid path.
   if [[ ${BUFFER[1]} != "-" && ${#BUFFER} == $end_pos ]] &&
-     true; then
+     /usr/bin/true; then
     local -a tmp
     tmp=( ${expanded_path}*(N) )
     (( $#tmp > 0 )) && style_override=path_prefix && return 0
```

**Comment by danielshahaf** [comment]
> > Does the error happen if you start zsh as `zsh -f` and then `source zsh-syntax-highlighting.zsh`?
> 
> If I start zsh as `zsh -f` and then source my `.zshrc` things are fine... until I hit Ctrl+C and then it segfaults.
> 
> ```
> [1]    16059 segmentation fault  zsh -f
> ```

Okay, so first of all, there is a bug in zsh.  (There may or may not be a bug in zsh-syntax-highlighting, but in either case zsh shouldn't segfault.)

Now, normally I'd ask you to narrow down your .zshrc to the minimal file that still reproduces the segfault, and then report that as a bug to zsh-users{_AT_}zsh.org.  However, I suspect the bug wouldn't be reproducible without enabling prezto, and in that case, it would be preferable to narrow down the bug even further, to the specific submodule within prezto that's required to reproduce the problem.

So, while I realize that you've been forwarded once, I'm afraid I must suggest that you report the segfault to zsh-users{_AT_}zsh.org, possibly after working with @sorin-ionescu to bisect your config (and the parts of prezto it enables) as much as possible, to the minimum .zshrc that still reproduces the bug.  (I'm also a zsh upstream committer and I'll be happy to help fixing the C bug as well, if I can.)

Sorin, what we know so far is @lencioni  sees an EIO from attachtty() and an immediate exit with his full config, and a segfault upon ^C with only his `.zshrc`.  He uses a self-compiled zsh 5.1.1.  The problem was bisected down to a `$WIDGET == accept-*` codepath.

**Comment by sorin-ionescu** [comment]
@danielshahaf, I have difficulty helping him because I cannot reproduce it. I also have had no need to read the code of zsh-syntax-highlighting; so, I do not know how it works. My [contributions](https://github.com/zsh-users/zsh-syntax-highlighting/commits?author=sorin-ionescu) to this project have been miniscule. I would have to allocate time to read it, at least the part that is causing problems, and understand what it is doing.

No shell code should crash Zsh. A crash dump would help to see where it happens in Zsh. If he could recompile Zsh with debug symbols, and capture a crash dump, that would be even better. He should post it to the mailing list where Zsh developers can see it.

I wonder if he has zsh-history-substring-search enabled. I know that has had conflicts with zsh-syntax-highlighting in the past.

**Comment by danielshahaf** [comment]
@sorin-ionescu, sorry, I wasnt clear.  I wasn't asking you to read z-sy-h's source code.  However, I _was_ getting ahead of myself; I shall rectify that now.

@lencioni: does the segfault reproduce after `zsh -f; source zsh-syntax-highlighting.zsh; ^C`?

**Comment by danielshahaf** [comment]
@lencioni I think you might be running into this issue: http://www.zsh.org/cgi-bin/mla/redirect?WORKERNUMBER=34694

**Comment by lencioni** [comment]
Thanks so much for all of the help so far!

> what we know so far is @lencioni sees an EIO from attachtty() and an immediate exit with his full config, and a segfault upon ^C with only his .zshrc. He uses a self-compiled zsh 5.1.1.

Sorry, I should have been more clear as well. I was experiencing the segfaults upon ^C with zsh 5.0.5 that came with my Mac. I just now tried installing 5.1.1 via homebrew and I no longer get a segfault when running `zsh -f`, sourcing my `.zshrc` file and then ^C. So it seems that perhaps that bug has been resolved already. Sorry for the confusion.

I tried 6cdc44b with and without the modifications with 5.1.1 and had the same results as before, FWIW. 

> I wonder if he has zsh-history-substring-search enabled. I know that has had conflicts with zsh-syntax-highlighting in the past.

[I do have that enabled](https://github.com/lencioni/dotfiles/blob/58178e71045a9da2b33a2d4029111a46f3d79289/.zpreztorc#L44). Removing that line does't make this problem go away, unfortunately.

**Comment by danielshahaf** [comment]
@lencioni, so with 5.1.1, you cannot reproduce a segfault, but can reproduce the error message in the title of this issue, is that correct?

In this case, my advice to you is the same as before: narrow down your .zshrc to the shortest file that reproduces the problem.

I'm sure you're familiar with the doctrine of a minimal example of a bug.  In zsh context, a "minimal example" means starting from `zsh -f` and adding as few things as possible, i.e., sourcing as short a file as possible.  In particular, have as few `source` and `autoload` commands as possible.

**Comment by lencioni** [comment]
> with 5.1.1, you cannot reproduce a segfault, but can reproduce the error message in the title of this issue, is that correct?

That is correct.

> In this case, my advice to you is the same as before: narrow down your `.zshrc` to the shortest file that reproduces the problem.

Yep, good advice.

> In zsh context, a "minimal example" means starting from `zsh -f` and adding as few things as possible, i.e., sourcing as short a file as possible. In particular, have as few `source` and `autoload` commands as possible.

Ah, I think I actually figured this out (sort of). With 5.1.1 when starting zsh by opening a new terminal, running `zsh`, or running `zsh -f` and manually sourcing `.zshenv`, `.zprofile`, `.zshrc`, and `.zlogin` everything is actually working okay. However, when opening a new tmux pane I was still getting this error which I guessed meant that tmux was still using the old version of zsh. I quit out of tmux and tried again and things seem to be working.

Sorry it took so long to get to the bottom of this and thank you so much for your help! I really appreciate all of the work you've put into zsh.
