### ISSUE TITLE
Update highlighting on Ctrl+P / Ctrl+N

### ISSUE THREAD

**Issue by dimonomid** [zsh-users/zsh-syntax-highlighting#250]
First of all, thanks for this great plugin.

I'm facing an issue: wnen I use up/down arrow keys to list history, highlighting is updated properly. However, when I use Ctrl+P / Ctrl+N shortcuts, it doesn't update, until I press some other key. It's just a little bit annoying, and I'd be happy if it can be resolved.

Thanks.

**Comment by danielshahaf** [comment]
Works for me:

```zsh
$ zsh -f
% source zsh-syntax-highlighting.zsh 
% print $ZSH_VERSION
5.1.1-test-3
% git rev-parse $ZSH_HIGHLIGHT_REVISION 
82f5eb17ecee1f18b3ce3d8a93761a51235cab78
% bindkey -e
% <^P><^N>
```

At a guess, your ^P and ^N are bound by some other plugin?  What do the following commands show:

```zsh
% bindkey -L \^P                       
bindkey "^P" up-line-or-history
% print $widgets[up-line-or-history]         # replace "up-line-or-history" by value from previous line
user:_zsh_highlight_widget_up-line-or-history
```

**Comment by danielshahaf** [comment]
In other words, I'm speculating this is an instance of #203.  And if that is the case, a workaround would be to bind ^N yourself to a widget that calls both the current widget and `_zsh_highlight`.

**Comment by dimonomid** [comment]
Oh yes, I have remapped them to something more convenient for me:
```
$ bindkey -L \^P    
bindkey "^P" up-line-or-beginning-search
$ print $widgets[up-line-or-beginning-search]
user:up-line-or-beginning-search
```
Thanks, will try to figure how to make a widget that will do the trick for me.

**Comment by danielshahaf** [comment]
Just add a call to `_zsh_highlight` (without arguments) to your `up-line-or-beginning-search` function.

For reference, that's exactly what z-sy-h does for non-user-defined widgets:

```zsh
% print $widgets[up-line-or-history]
user:_zsh_highlight_widget_up-line-or-history
% which ${widgets[up-line-or-history]#user:}
_zsh_highlight_widget_up-line-or-history () {
	_zsh_highlight_call_widget .up-line-or-history "$@"
}
% which _zsh_highlight_call_widget
_zsh_highlight_call_widget () {
	builtin zle "$@" && _zsh_highlight
}
```

**Comment by dimonomid** [comment]
Ok, thanks. Actually `up-line-or-beginning-search` is not my own function, I guess it comes with oh-my-zsh, so I had to write my own wrappers, like this:
```
my-highlighted-up-line-or-beginning-search() {
  _zsh_highlight_call_widget up-line-or-beginning-search \"\$@\"
};

my-highlighted-down-line-or-beginning-search() {
  _zsh_highlight_call_widget down-line-or-beginning-search \"\$@\"
};

autoload -U my-highlighted-up-line-or-beginning-search
autoload -U my-highlighted-down-line-or-beginning-search
zle -N my-highlighted-up-line-or-beginning-search
zle -N my-highlighted-down-line-or-beginning-search
```
and then bind them instead of original functions.

But, I'm wondering why does z-sy-h ingore user-defined functions? I see this line:
```
      # Already rebound event: do nothing.
      user:$cur_widget|user:_zsh_highlight_widget_*);;
```
Why not rewrite it so that only `_zsh_highlight_widget_*` are ignored:
```
      # Already rebound event: do nothing.
      user:_zsh_highlight_widget_*);;
```
If I do this, then `up-line-or-beginning-search` gets wrapped automatically.

I guess there is a rationale of the current behaviour (otherwise, why would one implement is as it is), but it's still unclear for me. I'd be glad if you explain a bit.

And anyway, thank you, the issue is resolved for me.

**Comment by danielshahaf** [comment]
> ```
> my-highlighted-up-line-or-beginning-search() {
>   _zsh_highlight_call_widget up-line-or-beginning-search \"\$@\"
> };
> ```

You should remove the backslashes; `_zsh_highlight_bind_widgets` uses them because it uses an `eval`, but in your case it probably only works because the `up-line-or-beginning-search` widget doesn't inspect its positional arguments.

> But, I'm wondering why does z-sy-h ingore user-defined functions?

To be honest, I'm not sure.  The code has been doing that since before I started working on this project.  Issue #203 tracks understanding and possibly changing that code.

> And anyway, thank you, the issue is resolved for me.

Ok, closing.  We can discuss the general issue with user-defined widgets on #203.  (I just added a comment to it.)

**Comment by danielshahaf** [comment]
... and, by the way, you don't need those two `autoload` lines.

**Comment by dimonomid** [comment]
oh, thanks for the notes.
