### ISSUE TITLE
The bell rings on every keystroke.

### ISSUE THREAD

**Issue by houshuu** [zsh-users/zsh-syntax-highlighting#253]
I tried the solutions in #200 and #92, but that didn't works.

-zsh 5.2 (x86_64-apple-darwin15.0.0)
-zsh-syntax-highlighting is up-to-date with master.

**Comment by danielshahaf** [comment]
What's the value of `$ZSH_HIGHLIGHT_REVISION`?

Does the issue occur under `zsh -f` + `source zsh-syntax-highlighting.zsh`?

When did the issue start?  Was it caused by a git pull?  If so, could you bisect?

**Comment by danielshahaf** [comment]
And if you can easily test an older version of zsh that'd help too.  (But no need for you to compile an old version just for this if you don't already have one lying around..)

**Comment by danielshahaf** [comment]
I cannot reproduce this; feel free to reopen and followup with more information.
