### ISSUE TITLE
Highlight global aliases

### ISSUE THREAD

**Issue by danielshahaf** [zsh-users/zsh-syntax-highlighting#265]
Idea: Highlight global aliases, created by `alias -g`.

**Comment by danielshahaf** [comment]
Would you be interested in writing the patch? We'd be happy to point you in the right direction.

**Comment by HaleTom** [comment]
I'd be happy to scope out the work and see if it's something that fits my expertise.

How to be in touch?

**Comment by danielshahaf** [comment]
Thanks. The bases to cover are the implementation, documentation, and a unit test; see `grep -R 'suffix.alias'` and mimic it. You can talk to us here or on #zsh-syntax-highlighting on freenode. (I'm not always online, but I'll read scrollback and reply.)

**Comment by HaleTom** [comment]
If anyone else wishes to merge in the changes, this has been implemented by @psprint here: https://github.com/zdharma/fast-syntax-highlighting/issues/41

**Comment by danielshahaf** [comment]
@HaleTom Thanks for the reference, but it doesn't get us any closer to implementing the same feature in z-sy-h.  We just need someone to write the patch and PR it.  (It doesn't have to be you, of course.)

If you could give examples of "faster" and "more complex syntax", that'd be appreciated.  There are some known [performance issues](https://github.com/zsh-users/zsh-syntax-highlighting/issues?q=is%3Aopen+label%3Aperformance), but I don't remember any particular outstanding feature requests for smarter parsing.  Cheers!

**Comment by HaleTom** [comment]
The project page details it better than I could.

**Comment by danielshahaf** [comment]
Submitted #700 to fix this.  For reference, incorporating https://github.com/zdharma/fast-syntax-highlighting/'s features is issue #434.
