### ISSUE TITLE
vi visual linewise mode misses beginning of line

### ISSUE THREAD

**Issue by danielshahaf** [zsh-users/zsh-syntax-highlighting#267]
In `bindkey -v` mode, type `foo foo<^V><^J>bar bar<^[>BvkV` to enter visual linewise mode.  This should highlight from the start of the first line to the end of the second line (that's what it does with z-sy-h disabled), but doesn't highlight the beginning of the first line.

Found by code inspection of uses of `REGION_ACTIVE == 2` for #266.

**Comment by danielshahaf** [comment]
At that point:

REGION_ACTIVE=2
CURSOR=4 (the second `f`)
MARK=12 (the second `b`)

The fix would be to stretch the $MARK..$CURSOR (or $CURSOR..$MARK) values up to the preceding and following `'\n'`, see for example [zrefresh()](https://github.com/zsh-users/zsh/blob/c82ce14950c327d45fe8a1dfece0f883a420641a/Src/Zle/zle_refresh.c#L1056-L1062).

This should be easy to fix, but conflicts with #256, so let's wait until #256 is merged before fixing this.

**Comment by danielshahaf** [comment]
I've pushed a branch that should fix the issue: https://github.com/zsh-users/zsh-syntax-highlighting/compare/master...danielshahaf:i267-linewise-region-v1

This seems to fix the issue, but I don't use vi mode, so confirmation from someone who does would be useful.

**Comment by ninrod** [comment]
I can confirm that your branch is a fix to this issue.

**Comment by danielshahaf** [comment]
Thanks for testing, @ninrod.  I've added a regression test and pushed the fix.

**Comment by danielshahaf** [comment]
For future reference, the output of `zle -M "$REGION_HIGHLIGHT,$MARK,$CURSOR,$(typeset -p region_highlight)"` before/after the patch is:

```
before: 2,12,4,typeset -a region_highlight=( '0 3 fg=red,bold' '4 7 none' '7 8 none' '8 11 fg=red,bold' '12 15 none' '4 12 standout' )

after:  2,12,4,typeset -a region_highlight=( '0 3 fg=red,bold' '4 7 none' '7 8 none' '8 11 fg=red,bold' '12 15 none' '0 16 standout' )
```

**Comment by danielshahaf** [comment]
Fallout (still being investigated): #340
