### ISSUE TITLE
maximum nested funtions limit reached

### ISSUE THREAD

**Issue by basheer7707** [zsh-users/zsh-syntax-highlighting#274]
"_zsh_autosuggest_invoke_original_widget:2: maximum nested function level reached" errors showed after installation. After closing and opening the shell several times, it disappeared. Plugin is working now.

**Comment by danielshahaf** [comment]
Thanks for the report.  Based on the function name mentioned, I guess this failure mode will go away when #245 is implemented (will require zsh-5.3).  However, I'm afraid I don't currently have the brainwidth to look into this issue more closely.  Sorry ☹

**Comment by danielshahaf** [comment]
Not reproducible with current HEAD of zsh-autosuggestions and zsh-syntax-highlighting.  If the issue persists, please reopen.  Thanks again for the report.
