### ISSUE TITLE
highlight unclosed string literals

### ISSUE THREAD

**Issue by euclio** [zsh-users/zsh-syntax-highlighting#277]
I'm trying to switch over to zsh from fish, and I really miss how fish's syntax highlighting will highlight unclosed string literals as red. I couldn't figure out how to do this with the current plugin.

**Comment by danielshahaf** [comment]
It's not currently possible: the code looks for the starting quote and doesn't distinguish whether or not a final quote is present.  (This gives rise to #130.)

As a workaround, you might try to revert ff4d402e9a587e0e8f8400a3aeac40a8f73215e5, which would cause unterminated strings not to be highlighted.

Possibly related is [workers/37631](http://www.zsh.org/cgi-bin/mla/redirect?WORKERNUMBER=37631) about detecting unterminated words.

**Comment by phy1729** [comment]
This could be implemented after #454 is merged.
