### ISSUE TITLE
_zsh_highlight_main_highlighter:147: unrecognized modifier ` '

### ISSUE THREAD

**Issue by a-m-s** [zsh-users/zsh-syntax-highlighting#279]
I've just started getting this error after updating:

```
_zsh_highlight_main_highlighter:147: unrecognized modifier ` '
```

git bisect shows that the error was introduced in commit 3cb58fd7d7b9e42067ffcf24892114dc2c9b26e4 "Optimization: -1 is extra computation of string length internally".

I see this in ZSH version 4.3.10, but not in 5.0.2 (or 5.2). I can't update ZSH on the older machine.

**Comment by danielshahaf** [comment]
@psprint This bisects to your commit, could you have a look please?

@a-m-s Thanks for the detailed report.  I'm not entirely sure whether 4.3.10 is supported: README.md states 4.3.17+ is required, but that statement predates 3cb58fd.  But I'd like to fix this if possible.

**Comment by danielshahaf** [comment]
@a-m-s Does changing `: ` (colon space) to `:` (colon) on [this line](https://github.com/zsh-users/zsh-syntax-highlighting/blob/7e7e291b2047e89419ab77fffe2f310b8c7d79e0/highlighters/main/main-highlighter.zsh#L244) (of latest master) fix the issue?  I'm not sure it would, but I'd like to rule this out.

**Comment by a-m-s** [comment]
No, I tried changing both ": " sequences, independently and together, but the problem persists. :-(

**Comment by danielshahaf** [comment]
Could you try this patch?

```diff
diff --git a/highlighters/main/main-highlighter.zsh b/highlighters/main/main-highlighter.zsh
index a6465a6..61d07c8 100644
--- a/highlighters/main/main-highlighter.zsh
+++ b/highlighters/main/main-highlighter.zsh
@@ -237,10 +237,10 @@ _zsh_highlight_main_highlighter()
       local needle=$'[;\n]'
       # Len-start_pos drops one character, but it should do it, as start_pos
       # starts from next, not from "start_pos", character
-      integer offset=${${buf: start_pos: len-start_pos}[(i)$needle]}
+      integer offset=${${buf[start_pos+1,len]}[(i)$needle]}
       (( start_pos += offset - 1 ))
       (( end_pos = start_pos + $#arg ))
     else
-      ((start_pos+=(len-start_pos)-${#${${buf: start_pos: len-start_pos}##([[:space:]]|\\[[:space:]])#}}))
+      ((start_pos+=(len-start_pos)-${#${${buf[start_pos+1,len]}##([[:space:]]|\\[[:space:]])#}}))
       ((end_pos=$start_pos+${#arg}))
     fi
```

What does `s=foobar; echo ${s:2:3}` print in your shell?

**Comment by danielshahaf** [comment]
I checked that patch for correctness but not for performance (which was the original motivation for 3cb58fd7d7b9e42067ffcf24892114dc2c9b26e4).

**Comment by a-m-s** [comment]
That patch appears to have the desired effect. :+1: 

As for performance, if this change is not good for new shells then it would be fine (for me) if it simply had two versions of the code for different shell versions, so it can work fast where possible, and at least work otherwise.

The other question:

```
$ s=foobar; echo ${s:2:3}
zsh: unrecognized modifier `2'
```

**Comment by psprint** [comment]
Ah so the problem was in 4.3.10. I was scared away by the issue as it seemed to reveal some random thing in Zsh, as the lines:

```zsh
integer offset=${${buf: start_pos: len-start_pos}[(i)$needle]}
integer offset=${${buf[start_pos+1,len]}[(i)$needle]}
# And
((start_pos+=(len-start_pos)-${#${${buf: start_pos: len-start_pos}##([[:space:]]|\\[[:space:]])#}}))
((start_pos+=(len-start_pos)-${#${${buf[start_pos+1,len]}##([[:space:]]|\\[[:space:]])#}}))
```

Should be equivalent. Seems that basically 4.3.10 doesn't support Bash indexing `${var:a:b}`

**Comment by danielshahaf** [comment]
> Seems that basically 4.3.10 doesn't support Bash indexing `${var:a:b}`

Correct.  The log message of my above commit refers to the specific zsh upstream commit that added that support (zsh-users/zsh@23bdfc7fd2a012d5205ed22d18eb39e41c8fbc95).
