### ISSUE TITLE
Review performance implications of bc7f8ea433adf3efd71a3e950e9a8dec846a1171

### ISSUE THREAD

**Issue by danielshahaf** [zsh-users/zsh-syntax-highlighting#282]
bc7f8ea433adf3efd71a3e950e9a8dec846a1171, which fixes #279, changes code touched in 3cb58fd7d7b9e42067ffcf24892114dc2c9b26e4, which was an optimization commit.

Double-check that bc7f8ea433adf3efd71a3e950e9a8dec846a1171 does not lose the performance win from 3cb58fd7d7b9e42067ffcf24892114dc2c9b26e4.

**Comment by psprint** [comment]
I believe bc7f8ea is a revert of optimizations so the performance is lost?

As for performance implications. Currently, the code works around those indices:

```zsh
      integer offset=${${buf[start_pos+1,-1]}[(i)$needle]}
      (( start_pos += offset - 1 ))
      (( end_pos = start_pos + $#arg ))
    else
      ((start_pos+=${#buf[$start_pos+1,-1]}-${#${buf[$start_pos+1,-1]##([[:space:]]|\\[[:space:]])#}}))
      ((end_pos=$start_pos+${#arg}))
    fi
```

Basically, when buffer is parsed, the indices are step by step incremented. As every use of index means iteration over every preceding characters of a string (this to be confirmed by Bart in reply to my 38410), then while after while z-sy-h slows down, which becomes visible for long buffers.

A solution would be: discard already parsed content. If we need only what's after `start_pos`, then what's before should be discarded, and that buffer should be further processed. This way z-sy-h would constantly work on short string, the beginning of buffer to parse. Only the cut-of of the beginning of buffer and making a new copy would require to search for end of string, to copy it whole.

**Comment by danielshahaf** [comment]
The previous comment analysed an old version of the code, not current master.

**Comment by danielshahaf** [comment]
@psprint reports the timings are as follows: 4.53s for the original code (pre-[3cb58fd](https://github.com/zsh-users/zsh-syntax-highlighting/commit/3cb58fd7d7b9e42067ffcf24892114dc2c9b26e4)); 2.4s for the middle code (3cb58fd until bc7f8ea); 2.81s for the current code (bc7f8ea).  His profiling code is at https://github.com/psprint/zsh-tools.

So:
- The optimization is mostly intact.
- The fact that bc7f8ea introduced a difference is surprising.  Might it point to a zsh upstream performance bug?

**Comment by psprint** [comment]
Here are performance test done with scripts from https://github.com/psprint/zsh-tools/ (all the `parse*.zsh` files):

- ./parse.zsh parse.zsh  2,43s user 0,88s system 94% cpu 3,491 total
- ./parse_orig.zsh parse.zsh  4,55s user 0,95s system 99% cpu 5,553 total
- ./parse_orig_len.zsh parse.zsh  2,80s user 0,89s system 97% cpu 3,791 total

parse_orig_len.zsh is the current version

**Comment by psprint** [comment]
The following:

```zsh
#!/bin/zsh

local str=${(r:1000000::_:)a};
index_it() {
    repeat 1000; do
        local character=${str[$1]}
    done
}

zmodload zsh/zprof
for i in 1000 5000 25000 $(( 5*25000 )) $(( 5*5*25000 )); do
    index_it $i
    zprof_out=( "${(@f)"$( zprof )"}" )
    # Third line
    zprof_out="$zprof_out[3]"
    # For third field in the print
    zprof_out=( $=zprof_out )
    print "${(l:8):: :)i} ${(l:10:: :)zprof_out[3]}"
    zprof -c
done
```
Outputs:

```
    1000     797,43
    5000     885,96
   25000    1302,70
  125000    3374,42
  625000   13550,54
```

Which is ultimate proof that the longer the index, the longer is access time – especially `3374,42` vs `13550,54` shows this, it's almost the same times higher as the index is (5 times).

That said, I wonder how many times the loop in main-highlighter runs, as the times are significant starting from `1000` repetitions. It doesn't feel like indexing would be the slow down, however the previous optimization is almos 2x gain and it's the indexing that's the cause. I once optimized out fork for `type` there, and it was no-gain, so I guess it's really the indexing, normally expected "don't allocate" process or memory might not be really a problem.

**Comment by psprint** [comment]
I now tested this, and it's `2.12s` for version with no fork for `type`, and `2.87s` for current version of the code. The test file that comments out `type`:

https://github.com/psprint/zsh-tools/commit/46e83c5cc016ad3fc99533b9948a292648264928

There is the "-zplg-statica-type" and in general "-zplg*" function names because I once wanted to adapt z-sy-h as static analysis subsystem for `zplugin`, but resigned because of the performance. Despite the function names lifting, this is extracted main-highlighter, without changes.

**Comment by danielshahaf** [comment]
Here's a slightly more condensed version of your script; its results are consistent with yours:

```zsh
% cat ./1
#!/usr/local/bin/zsh -f

local str=${(r#1000000##:#)a};
typeset -F SECONDS end
integer i

for i in 1000 5000 25000 $(( 5*25000 )) $(( 5*5*25000 )); do
    SECONDS=0
    repeat 1000; do
        ${str[$i]}
    done
    end=$SECONDS
    print "${(l:8:: :)i} $end"
done
% zsh -f ./1 
    1000 0.3446590000
    5000 0.5428940000
   25000 1.5944010000
  125000 7.2752290000
  625000 36.0570010000
```
(using zsh from git master)

> That said, I wonder how many times the loop in main-highlighter runs, as the times are significant starting from `1000` repetitions.

The loop iterates `${PREBUFFER}${BUFFER}` one word at a time.  It splits $buf into words using the `${(z)}` flag (aka the C function `bufferwords()`), which may or may not be efficient.  That is: it's possible that simply doing `: ${(z)BUFFER}` on large buffers is expensive, in addition to any inefficiencies in z-sy-h's code itself.

> It doesn't feel like indexing would be the slow down, however the previous optimization is almos 2x gain and it's the indexing that's the cause.

Yes, but note that using `${foo:offset:offset}` gives only a linear improvement, not an order of magnitude improvement: changing the profiled code to use `${str: $i : 1}` still gives the same "almost x5" trend in the measured durations.

An order of magnitude improvement would require making the C code smarter (such as by using a constant-width encoding, or by marking a string "dirty" if it has characters in different widths _and_ implementing a fast path for the "non-dirty" case, etc).

> I guess it's really the indexing, normally expected "don't allocate" process or memory might not be really a problem.

So to be clear, the proposed explanation is that the offset is in _characters_, so all preceding bytes have to be inspected individually for multibyte characters to be handled correctly.  That sounds reasonable.  There doesn't seem to be a different, faster codepath for `--disable-multibyte` builds, either (from code inspection; not tested).

As to the idea of cutting the head off `$buf` as it is iterated through: I am skeptical of this idea, since the result would have the same complexity (O(N²), although due to memcpy's rather than due to indexing).  However, `$buf` is only used three times:

1. Passed to `bufferwords` (${(z)})
2. "Look for the next `;` or `\n`"
3. "Remove leading whitespace characters, optionally backslash-escaped"

If `bufferwords` is slow, that would have to be fixed in zsh itself.

However, perhaps (2) and (3) would be faster if they operated on on array variable `buf_array=( ${(s::)buf} )` instead of on `$buf`?  The C code would then split `$buf` into characters _once_, and hopefully will subsequently index that array in O(1) time.  Does this approach make sense?

> There is the "-zplg-statica-type" and in general "-zplg*" function names because I once wanted to adapt z-sy-h as static analysis subsystem for `zplugin`, but resigned because of the performance. Despite the function names lifting, this is extracted main-highlighter, without changes.

I'd love to make z-sy-h more performant, and even to extract the 'main' highlighter's parser into a separate, reusable component.

You haven't mentioned it explicitly, so I'll ask: is the [advance `start_pos` block](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/highlighters/main/main-highlighter.zsh#L226-L243) the lowest-hanging fruit here?  Is it the part where an optimization would have the biggest gains?

For future reference, the relevant C code is paramsubst()→fetchvalue()→getindex()→getarg().

Thanks again!

**Comment by danielshahaf** [comment]
> However, perhaps (2) and (3) would be faster if they operated on on array variable `buf_array=( ${(s::)buf} )` instead of on `$buf`?  The C code would then split `$buf` into characters _once_, and hopefully will subsequently index that array in O(1) time.  Does this approach make sense?

That approach scales much better; however, the initial ${(s::)} takes a while:

```zsh
#!/usr/local/bin/zsh -f

local str=${(r#1000000##:#)a};
typeset -F SECONDS end
integer i

strarray=( ${(s::)str} )
for i in 1000 5000 25000 $(( 5*25000 )) $(( 5*5*25000 )); do
    SECONDS=0
    repeat 1000; do
        ${strarray[$i]}
    done
    end=$SECONDS
    print "${(l:8:: :)i} $end"
done
```

```
    1000 5.5746880000
    5000 5.7208890000
   25000 5.7921100000
  125000 5.9011140000
  625000 5.9699420000
```

**Comment by psprint** [comment]
If we gather data on pefromance, here is one I think interesting test:

```zsh
a=; a=${(r:100000::_:)a}; len=${#a};
zshstyle() { repeat 500; do b=${a[-5000,-1]}; done };
zshstyle2() { repeat 500; do b=${a[-5000,len]}; done };
shstyle() { repeat 500; do b=${a: -5000:5000}; done };
time ( zshstyle );
time ( zshstyle2 );
time ( shstyle )

( zshstyle; )  3,39s user 0,01s system 99% cpu 3,406 total
( zshstyle2; )  2,70s user 0,01s system 99% cpu 2,718 total
( shstyle; )  2,00s user 0,01s system 99% cpu 2,020 total
```

**Comment by danielshahaf** [comment]
Thanks for these numbers.  What needs to be done before this issue can be closed?

If we want to use the `${foo:N:M}` syntax we'd have to handle zsh≤4.3.10 specially (either provide a separate codepath for it, or break compatibility with it; since is-at-least appears to have been in zsh upstream since forever, we will be able to use it in the driver without compatibility issues, should we choose the second option).

**Comment by danielshahaf** [comment]
Triage: The code in question has been optimised again since then (`$proc_buf`) added.
