### ISSUE TITLE
accepting a line in isearch does not remove cursor imprint and partial path highlighting

### ISSUE THREAD

**Issue by m0vie** [zsh-users/zsh-syntax-highlighting#284]
When accepting a line from within an isearch minimuffer, none of the `accept-*` widgets are called so the special handling for cursor imprint and partial path removal is not triggered.

Should use `zle-line-finish` instead.

**Comment by danielshahaf** [comment]
Reproduction instructions at https://github.com/zsh-users/zsh-syntax-highlighting/pull/259#issuecomment-168395647

**Comment by danielshahaf** [comment]
PR: #288
