### ISSUE TITLE
brackets quoted-patentheses.zsh test has invalid expectations

### ISSUE THREAD

**Issue by danielshahaf** [zsh-users/zsh-syntax-highlighting#289]
As found in https://github.com/zsh-users/zsh-syntax-highlighting/issues/287#issuecomment-205075851, https://github.com/zsh-users/zsh-syntax-highlighting/blob/31ac2b36a9156ef424e8ccee560ec31f97bd3eef/highlighters/brackets/test-data/quoted-patentheses.zsh#L30-L34 has invalid expectations: it expects `${(q-)ZSH_HIGHLIGHT_STYLES[none]}`, but there is no such key.

**Comment by phy1729** [comment]
Agreed on IRC to use `NONE`. As styles are usually all lower-case there should be no collision.

**Comment by danielshahaf** [comment]
@phy1729 Thanks for the patch.  Review:

- Could you document `NONE` convention in docs/README.md?

- The test-highlighting.zsh change is unneeded (`make test` passes without it), but if you keep that line, I think it could benefit from an explanatory comment.

**Comment by phy1729** [comment]
Proposed fix: 5173c9d

**Comment by danielshahaf** [comment]
Most of this is already mentioned in tests/README.md; two parts that aren't are (a) the new `NONE` convention, (b) that test files need to define `$BUFFER`.  Could you update patch to add that information to tests/README.md (and point to it from docs/highlighters.md)?

Sorry for the late reply, this slipped through the cracks.

**Comment by danielshahaf** [comment]
> two parts that aren't are (a) the new `NONE` convention, (b) that test files need to define `$BUFFER`.

This isn't an exhaustive list; for instance, the code exemplifying the "inter-test file isolation" is also a candidate for porting to tests/README.md.
