### ISSUE TITLE
Highlight commands in sub shells and command substitution

### ISSUE THREAD

**Issue by sorin-ionescu** [zsh-users/zsh-syntax-highlighting#29]
__which__ should be highlighted in all the following cases.

__echo__ (__which__ echo)
__echo__ $(__which__ echo)

I'm not sure if back ticks should be treated like above or like a string.
__echo__ \`__which__ echo`

**Comment by danielshahaf** [comment]
Duplicate of https://github.com/zsh-users/zsh-syntax-highlighting/issues/166 (subshells) and https://github.com/zsh-users/zsh-syntax-highlighting/issues/139 (backticks)
