### ISSUE TITLE
simplify code: work with the keys of ZSH_HIGHLIGHT_STYLES until assignment

### ISSUE THREAD

**Issue by m0vie** [zsh-users/zsh-syntax-highlighting#300]
All the code currently works like this:
````
style=$ZSH_HIGHLIGHT_STYLES[path]
...
zle_highlight+=("start end $style")
````

The following would be simpler, more readable, would carry more semantics (for styles with identical value), and could potentially simplify testing a lot:

````
style=path
...
zle_highlight+=("start end $ZSH_HIGHLIGHT_STYLES[$style]")
````

**Comment by phy1729** [comment]
Closed with #301.
