### ISSUE TITLE
Syntax highlighting is not reset after "cd fo<tab><enter>"

### ISSUE THREAD

**Issue by blueyed** [zsh-users/zsh-syntax-highlighting#310]
After `cd fo<tab><enter>`, where `cd fo<tab>` displays multiple options with " -- directory in cdpath --" the syntax highlighting is not reset, and the "cd: no such file or directory: fo" is displayed in grey, just like / similar to the (new?) part that highlights the already typed text.

This only happens after the first call to this in a new shell, afterwards it works.
But there are differences, e.g. with `cd b<tab><enter>` it seemed to be triggered always?!

Hopefully this is enough to reproduce, otherwise I'd be happy to bisect and/or provide more information.

```
% setopt
alwaystoend
autocd
autopushd
completeinword
correct
extendedglob
extendedhistory
noflowcontrol
noglobalrcs
globcomplete
histexpiredupsfirst
histignoredups
histignorespace
incappendhistorytime
interactive
interactivecomments
longlistjobs
mailwarning
monitor
numericglobsort
printeightbit
pushdignoredups
pushdminus
pushdsilent
rcexpandparam
shinstdin
zle
```

**Comment by danielshahaf** [comment]
I cannot reproduce this.

Could you provide a self-contained reproduction recipe (starting from `zsh -f` and creating its own directory tree for testing)?

Does #288 fix this?

Are you using latest master?

Feel free to join #zsh-syntax-highlighting on freenode.

**Comment by blueyed** [comment]
#288 does not fix it.
I am using master.

I've feared that it might be related to some custom settings/config.  Would need to investigate further, but cannot at the moment.

**Comment by blueyed** [comment]
Sorry for the confusion, this happened because of my theme.

I've started using `%F{19}` for coloring (instead of the `$fg`-style vars), but have not added `%f`.
It's a bit weird though why it did not happen always.

It had the nice side effect of using a different style for (parts of) the already typed text after completion was triggered, which I've thought was a new feature after also upgrading z-sy-h at the same time.. :)
(so you could see what was there before the completion was done)

**Comment by danielshahaf** [comment]
We don't have a feature for highlighting the just-added-by-completion text differently, however, there _are_ the `show-ambiguity` and `list-colors` styles, which are independently useful...

I use `zstyle -e :completion:\* list-colors 'reply=( "=(#b)(${(b)PREFIX})(?)([^ ]#)*=0=33=34=33" )'`, changing the second 33 to 34 gives a markedly different UX.
