### ISSUE TITLE
bug triggered when pasting

### ISSUE THREAD

**Issue by chenhouwu** [zsh-users/zsh-syntax-highlighting#325]
```
_zsh_highlight_widget_bracketed-paste: bracketed-paste-magic: function definition file not found
```

**Comment by danielshahaf** [comment]
It seems that you did `zle -N bracketed-paste bracketed-paste-magic` and then invoked `bracketed-paste`, but at that point `bracketed-paste-magic` wasn't in $fpath.  `bracketed-paste` and `bracketed-paste-magic` appeared in the same zsh upstream release, so it'd odd if you had one but not the other.

Does this error also occur if you disable zsh-syntax-highlighting in your .zshrc?

**Comment by chenhouwu** [comment]
the bug is not caused by `zsh-syntax-highlighting`. it's because that `tmux` does not support *bracketed paste* yet. see: https://github.com/tmux/tmux/issues/223

**Comment by danielshahaf** [comment]
That tmux bug is simply about the bracketing escape sequences entering tmux's colon command line literally.  I don't see how that explains the symptoms you reported.

To be clear: Pasting into zsh inside tmux works fine, and triggers highlighting as expected.

**Comment by chenhouwu** [comment]
After disable the bracket_paste feature, no problem at all.

``` 
if [ ${TMUX} ]; then
 unset zle_bracketed_paste
fi
```

**Comment by danielshahaf** [comment]
The line `unset zle_bracketed_paste` causes the `bracketed-paste` widget
never to be invoked.  The root problem is that the widget was redeclared
as a user-defined widget implemented by an autoloadable function, and
that function can't be autoloaded.

I still suggest that you figure out (a) what redefined the
bracketed-paste widget, (b) why the bracketed-paste-magic function
(which ships with zsh itself) can't be autoloaded.

Minimal example:

```
% autoload foo
% foo
zsh: foo: function definition file not found
```

**Comment by chenhouwu** [comment]
After an upgrade of https://github.com/zplug/zplug, some of the plugins do not work any more, unless I explicitly source `oh-my-zsh` init script.

Thus I think maybe in this way the `oh-my-zsh` init script is invoked twice, because in early version of zplug I need not to explicitly source `oh-my-zsh` init script.

All is OK after I shift to the https://github.com/tarjoilija/zgen plugin system.
