### ISSUE TITLE
Change highlighter hook naming pattern (namespace)

### ISSUE THREAD

**Issue by danielshahaf** [zsh-users/zsh-syntax-highlighting#329]
- [ ] Change `_zsh_highlight_${highlighter}_highlighter_*` to `_zsh_highlight_highlighter_${highlighter}_*` to make the namespace clearer / more intuitive.
- [x] On the other hand, `_zsh_highlight_${highlighter}_highlighter_cache` should be moved from the highlighter's namespace (`_zsh_highlight_highlighter_${highlighter}_cache`) to the driver's namespace, since it's an implementation detail of the driver, and would prevent highlighters from having their own global variable by that name. _(Update: done in 3e59ab4)_

Suggested by @phy1729.

**Comment by danielshahaf** [comment]
Milestone 0.5.0: this affects third party API consumers so it'd be best to get this done as early as possible.

**Comment by danielshahaf** [comment]
I just pushed an initial draft of the rename: [`git fetch danielsh i329-v1`](https://github.com/danielshahaf/zsh-syntax-highlighting/compare/docs-s-myhighlighter-acme-v1...danielshahaf:i329-v1?expand=1).  That branch is written on top of #341 and is expected to be rebased.

As written, it designates the `_zsh_highlight_highlighter_acme_*` namespace for callback functions defined by the `acme` highlighter to be called by the driver.

Question:
- Compatibility: do we want a warning for third party highlighters that use the old entrypoint names? Can we get that warning to only be emitted for the respective highlighter's author, not for every user of that highlighter?

**Comment by ascii-soup** [comment]
This looks really good to me. Worth the effort in modifying my highlighter to get the benefits for sure.

**Comment by danielshahaf** [comment]
Thanks for the review, I'll go forward with this and #341 when I have time.

**Comment by danielshahaf** [comment]
I've updated the branch.  It now includes back-compat glue so third-party highlighters will continue to work even if they haven't updated their entry point names.

Currently, that results in a warning, but I'll probably disable that warning since there's no way to make it appear only for maintainers, and having it appear _for every user_ would be untenable.  Instead, I'll just publish the change to third party highlighter authors in README/NEWS/ChangeLog.

**Comment by danielshahaf** [comment]
I've disabled the warning and rebased the branch, but we forgot something...

80148f6c840299f0980f4359ec5307ca63837dff implies the _driver_ should use a double-underscore namespace — `_zsh_highlight__*` — to avoid namespace clashes with individual highlighters.  So that needs to be done, too...

**Comment by danielshahaf** [comment]
Done in f91a7b885e7d.
