### ISSUE TITLE
Starting a line with an environment varible causes error in _zsh_highlight_main_add_region_highlight

### ISSUE THREAD

**Issue by hpbretz** [zsh-users/zsh-syntax-highlighting#337]
If one starts a line with an environment variable, the highlighter will cause an error while typing the variable. 

Example: One has a variable $folder and wants to change the directory without typing `cd`. As soon as one starts typing `$f` one gets the error message
```_zsh_highlight_main_add_region_highlight:1: bad math expression: operand expected at `' ```

Exception: If the variable is one letter long and already exists, no error message is given.

**Comment by hpbretz** [comment]
To be more precise regarding the exception above: If the letters you have typed do not exist as a variable, the error occurs.

So if you have a variable called `$folder`, and variables called `$f`, `$fo` and `$fol` are also defined, the error will occur as soon as you have typed `$fold`.

**Comment by danielshahaf** [comment]
That's precise enough, thank you, but I can't reproduce the problem.  Could you please provide the output of `echo $ZSH_VERSION $ZSH_PATCHLEVEL $ZSH_HIGHLIGHT_REVISION` and reproduction instructions starting with `zsh -f` + `source zsh-syntax-highlighting.zsh`?  You may need to `setopt autocd` there, too.

**Comment by hpbretz** [comment]
```
~/software/zsh-syntax-highlighting % zsh -f                                              
~/software/zsh-syntax-highlighting % source zsh-syntax-highlighting.zsh               
~/software/zsh-syntax-highlighting % setopt autocd                                    
~/software/zsh-syntax-highlighting % echo $ZSH_VERSION $ZSH_PATCHLEVEL $ZSH_HIGHLIGHT_REVISION
4.3.11 1.5161 HEAD
~/software/zsh-syntax-highlighting % $i                                               
_zsh_highlight_main_add_region_highlight:1: bad math expression: operand expected at `'
~/software/zsh-syntax-highlighting % $i                                               
/software/zsh-syntax-highlighting %  
```

**Comment by danielshahaf** [comment]
Thanks for that.  The root cause was da91264 (introduced in 12b879ca,).   d9e07b5 fixed an unrelated bug (we were calling `_zsh_highlight_main__type` with a null parameter).
