### ISSUE TITLE
Stop requiring FUNCTION_ARGZERO

### ISSUE THREAD

**Issue by danielshahaf** [zsh-users/zsh-syntax-highlighting#338]
Look into using `$(print -P %N)` instead, see [users/21637](www.zsh.org/cgi-bin/mla/redirect?USERNUMBER=21637).

**Comment by psprint** [comment]
More like a knowledge base thing what I'm submitting, while it isn't exactly related. I've just noted doing `0=...` inside a **script** causes segfault on 5.0.2. Sourced files still are allowed to do this there.

Best regards

**Comment by danielshahaf** [comment]
Thanks for the heads up.
