### ISSUE TITLE
Cannot working normally with oh-my-zsh

### ISSUE THREAD

**Issue by johnwatsondev** [zsh-users/zsh-syntax-highlighting#339]
OS Version: OS X EI Capitan 10.11.5

iTerm2 : Build 3.0.0

Oh-My-Zsh: input `upgrade_oh_my_zsh` just show below info:

```
From https://github.com/robbyrussell/oh-my-zsh
 * branch            master     -> FETCH_HEAD
Current branch master is up to date.
```

Zsh Version: zsh 5.2 (x86_64-apple-darwin15.5.0)

Install with a plugin manager: follow this [mechanism](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md#oh-my-zsh)

install path: `~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting`

---

Here is my [.zshrc](https://gist.github.com/johnwatsondev/6382ec146e9f80e98c677a0c62956f61) file

Please let me know if I missed some file or config?

Thanks for the feedback.

**Comment by danielshahaf** [comment]
What is the actual problem?  What behaviour do you observe, and what behaviour do you expect instead?

**Comment by johnwatsondev** [comment]
I always thought it didn't work normally. Sorry for my mistake. My shell display is right. 
I think we should provide a standard of what is right behavior.

**Comment by danielshahaf** [comment]
There's a screenshot in README.md.  Do you have a specific documentation change in mind?

**Comment by johnwatsondev** [comment]
I think we can provide this in README.md.
e.g. : 
Please input `cat file.txt`. It will work normally if `file.txt` displayed with the underline.

I thought it didn't work normally because I saw my `cat` command is not displayed with the color in the screenshot.
I seemed to be an idiot of course before. Sorry for my mistake again. 😭

**Comment by danielshahaf** [comment]
No need to apologise.  I can see how having such a sentence made explicit could be useful, but I don't see where in README.md/INSTALL.md it would best fit ...

**Comment by johnwatsondev** [comment]
I thought the FAQ is maybe a fit place. :)
