### ISSUE TITLE
flags to `command` are mishighlighted as missing commands

### ISSUE THREAD

**Issue by anntzer** [zsh-users/zsh-syntax-highlighting#343]
Basically,

```
$ command -v foo
```

highlights `-v` in red (as I don't have an executable called "-v" in my PATH).

**Comment by danielshahaf** [comment]
Similar to #168 #247 #248.  Fixing this in the current infrastructure will require extending the state machine; but extending the state machine for each of _N_ precommands isn't the best idea.  Perhaps there's a better option (something based on `getopts` or `zparseopts` might be nice).

The other requests _could_ be addressed if they are normally invoked without options (so `nice pwd`, `doas pwd`, `pkexec pwd` would work but `foo -x pwd` would highlight the `-x` instead of the `pwd` as a command).  Perhaps that should be done...

**Comment by anntzer** [comment]
Sorry, I skimmed through the tracker for a duplicate but couldn't find one.  Feel free to close this.

**Comment by danielshahaf** [comment]
I've added a test (0d41933) and started on a fix (https://github.com/zsh-users/zsh-syntax-highlighting/compare/master...danielshahaf:i343-precommands-v1), but ran into an outstanding issue about aliases not being resolved correctly.

**Comment by danielshahaf** [comment]
That outstanding issue is #264.

**Comment by danielshahaf** [comment]
I've force-pushed that branch, it now fixes both `command` and `nice`, and adds support for aliases too.  The aliases handling needs a closer look, (a) audit uses of `$arg`, (b) outstanding questions on #247.

**Comment by danielshahaf** [comment]
That branch now conflicts due to:

* 2c002f9 noop: Add comments.
* 757d047 'main': The word after 'sudo' is only a non-command word if it is an option.
* 179b8e7 'main': Test for redirection earlier.
* d1c773f noop: Fix indentation.

**Comment by danielshahaf** [comment]
I"ve rebased the branch as https://github.com/zsh-users/zsh-syntax-highlighting/compare/master...danielshahaf:i343-precommands-v2.

It's a pretty invasive change so I'm tentatively scheduling it for 0.6.0, but with favourable winds and calm seas it could get merged in time for 0.5.0.

**Comment by ascii-soup** [comment]
I've been testing this fix against master side-by-side and I couldn't find any instances where the new behaviour was incorrect (as far as this issue goes). Overall it works better / is fixed versus master.
:+1:

**Comment by danielshahaf** [comment]
@ascii-soup Thanks for the feedback!  Did you review the code as well, or did you only do blackbox testing of the fix?

**Comment by ascii-soup** [comment]
Just black box testing for now; had a brief glance at the code in the time I had, will endeavour to clone to CR properly this afternoon.

**Comment by ascii-soup** [comment]
Code looks good to me, to the extend that I understand it ;)

**Comment by danielshahaf** [comment]
Thanks for the review!  Feel free to ask on IRC for clarifications about
the code.

**Comment by danielshahaf** [comment]
Thank you!
