### ISSUE TITLE
Cursor colors? Help wanted!

### ISSUE THREAD

**Issue by ucharfli** [zsh-users/zsh-syntax-highlighting#348]
I have to edit file
File:  ~/.zprezto/modules/syntax-highlighting/externel/highlighters/cursor/cursor-highlighter.zsh
Line: region_highlight+=("$CURSOR $(( $CURSOR + 1 )) $ZSH_HIGHLIGHT_STYLES[cursor]")
Edit: .... ("$CURSOR $(( $CURSOR + 0 ))...
Lxterminal : no problem. >  ** *** LINK REMOVED *** ** 
Urxvt : same again. Back cursor. No colors >. ** *** LINK REMOVED *** **

**Comment by danielshahaf** [comment]
I've removed your pastebin links since they appear to cause a DoS.

The cursor highlighter works fine in `xterm -uc`

Could you repeat your question?

**Comment by ucharfli** [comment]
Yes. Xterm and urxvt,  cursor underline no problem.
Problem; cursor block. 
Lxterminal, no problem.
Xterm and urxvt to problem.
What is problem?

**Comment by danielshahaf** [comment]
I'm not sure I understand your English, but perhaps you're looking for this:

```
(( $+ZSH_HIGHLIGHT_STYLES )) || declare -gA ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[cursor]=underline
```

Put it at the very end of your zshrc.

**Comment by danielshahaf** [comment]
If you want the cursor to be underlined and your terminal provides a *built-in* block cursor, you need to disable the latter in your terminal configuration.  Check your terminal's documentation for details for details.

**Comment by ucharfli** [comment]
I'm sorry but the link to share 
https://vid.me/b774  < I want to do this.
You can monitor and delete.
My terminal urxvt .
but I can not. Cursor back no colors.
Can you help me ?

**Comment by ucharfli** [comment]
Sorry. My bad english  :(

**Comment by danielshahaf** [comment]
I'm sorry, but I simply don't understand your question.

1. Can you describe the current behaviour?
2. Can you describe the desired behaviour?
3. Can you describe the difference between (1) and (2)?

Are you asking about the color of the cursor itself (the color of the underline or bar or box) or about the color of the command line typed in at the prompt?

**Comment by ucharfli** [comment]
the cursor does not change color comes back.
?

**Comment by ucharfli** [comment]
the cursor does not change color on the left gone.

**Comment by danielshahaf** [comment]
I guess what you see is that urxvt's box cursor is used in preference to zsh-syntax-highlighting's box cursor.

Try configuring urxvt to use an underline cursor or a vertical bar cursor.

**Comment by ucharfli** [comment]
Underline and vertical bar no problem. Verry good.
I am cursor block. My video. 
Is it possible to?

**Comment by ucharfli** [comment]
![cursor](http://i.imgur.com/JPMA8RJ.png)

**Comment by danielshahaf** [comment]
The color of the cursor in this situation is controlled by the terminal emulator, not by zsh-syntax-highlighting.

You need to configure your terminal emulator to disable the _standout_ or _reverse video_ method of drawing the cursor.

Good luck!

**Comment by ucharfli** [comment]
Thanks for the help.
