### ISSUE TITLE
paste highlighting

### ISSUE THREAD

**Issue by lanox** [zsh-users/zsh-syntax-highlighting#349]
Hi 

Is there a way to disable highlighting when pasting to terminal ?.

<img width="166" alt="screen shot 2016-08-09 at 12 08 36 am" src="https://cloud.githubusercontent.com/assets/7599183/17482523/7da7dd60-5dc5-11e6-875d-f6712ff66ffe.png">

**Comment by danielshahaf** [comment]
Yes: https://github.com/zsh-users/zsh/blob/ac0dcc9a63dc2a0edc62f8f1381b15b0b5ce5da3/NEWS#L37-L42
