### ISSUE TITLE
Causing iterm to crash for zsh 5.2

### ISSUE THREAD

**Issue by pradeepcheers** [zsh-users/zsh-syntax-highlighting#350]
Tried installing via Prezto and Homebrew as well! Disappointing!

**Comment by danielshahaf** [comment]
pradeepcheers wrote on Fri, Aug 19, 2016 at 18:26:40 -0700:
> Tried installing via Prezto and Homebrew as well! Disappointing! 

Sorry you're having trouble.  What version of z-sy-h (git commit hash)
are you installing?

Could you — in iterm — run `zsh` and within *that* shell run `source
/path/to/zsh-syntax-highlighting.zsh` and report what the output and
exit code are?

Could you narrow down your .zshrc to the smallest one that still
reproduces the problem?

**Comment by pradeepcheers** [comment]
Hi Daniel

The git commit hash of z-sh-h is ``7c7e2d00af9d8a05f4736c368804713fba61a422``.

As soon as I run the command ``source /path/to/zsh-syntax-highlighting.zsh`` in zsh it seem to be fine. But when I set the command ``. source /path/to/zsh-syntax-highlighting.zsh`` on ``~/.zshrc`` then the iterm window or tab closes immediately!.

FYI, My **~/.zshrc** is as follows:
``` 
#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
   source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Setting Z
. `brew --prefix`/etc/profile.d/z.sh
```

Thanks

**Comment by danielshahaf** [comment]
> As soon as I run the command `source /path/to/zsh-syntax-highlighting.zsh` in zsh it seem to be fine. But when I set the command `. source /path/to/zsh-syntax-highlighting.zsh` on ~/.zshrc then the iterm window or tab closes immediately!.

What happens if you just put `source /path/to/zsh-syntax-highlighting.zsh` (_without_ the leading dot-space) in your .zshrc?

**Comment by danielshahaf** [comment]
For what it's worth, with the printexitvalue option set:

```zsh
% . source zsh-syntax-highlighting.zsh 
.: no such file or directory: source
zsh: exit 127
```

so perhaps something sets the errexit option (which is a bad idea for interactive usage)...  What happens if you simply run `false` at the prompt, does it die too?

**Comment by pradeepcheers** [comment]
Even after removing the leading dot-space didn't make any difference.

**Comment by danielshahaf** [comment]
pradeepcheers wrote on Sat, Aug 20, 2016 at 16:02:09 -0700:
> Even after removing the leading dot-space didn't make any difference.

So, to clarify: if you run `source zsh-syntax-highlighting.zsh` in an
interactive shell it works, and if you put the same command as the last
thing in your .zshrc then zsh fails to start?

**Comment by pradeepcheers** [comment]
yes, you are correct.

**Comment by danielshahaf** [comment]
Start the shell as 'zsh -x' and see what gets executed after the end of
.zshrc and before the first prompt.

**Comment by pradeepcheers** [comment]
zsh -x output is as follows:

+pmodload:36> zstyle :prezto:module:prompt loaded yes
+/Users/Pradeep/.zprezto/init.zsh:113> unset pmodules
+/Users/Pradeep/.zshrc:16> brew --prefix
+/Users/Pradeep/.zshrc:16> . /usr/local/etc/profile.d/z.sh
+/usr/local/etc/profile.d/z.sh:26> [ -d /Users/Pradeep/.z ']'
+/usr/local/etc/profile.d/z.sh:205> alias 'z=_z 2>&1'
+/usr/local/etc/profile.d/z.sh:207> [ '' ']'
+/usr/local/etc/profile.d/z.sh:207> _Z_RESOLVE_SYMLINKS=-P
+/usr/local/etc/profile.d/z.sh:209> type -a compctl
+/usr/local/etc/profile.d/z.sh:211> [ '' ']'
+/usr/local/etc/profile.d/z.sh:213> [ '' ']'
+/usr/local/etc/profile.d/z.sh:222> [[ -n '' ]]
+/usr/local/etc/profile.d/z.sh:223> precmd_functions[$(($#precmd_functions+1))]=_z_precmd
+/usr/local/etc/profile.d/z.sh:232> compctl -U -K _z_zsh_tab_completion _z
+prompt_sorin_precmd:1> setopt LOCAL_OPTIONS
+prompt_sorin_precmd:2> unsetopt XTRACE KSH_ARRAYS
+_z_precmd:1> _z --add /Users/Pradeep
+_z:2> local 'datafile=/Users/Pradeep/.z'
+_z:5> [ -z '' -a -f /Users/Pradeep/.z -a '!' -O /Users/Pradeep/.z ']'
+_z:8> [ --add '=' --add ']'
+_z:9> shift
+_z:12> [ /Users/Pradeep '=' /Users/Pradeep ']'
+_z:12> return
~ ❯❯❯ +zsh:1> prompt_sorin_git_info
+prompt_sorin_git_info:1> ((  _prompt_sorin_precmd_async_pid > 0  ))
+prompt_sorin_git_info:3> [[ -s /tmp/zsh-prompt_sorin_data ]]
+prompt_sorin_git_info:4> alias 'typeset=typeset -g'
+prompt_sorin_git_info:5> source /tmp/zsh-prompt_sorin_data
+/tmp/zsh-prompt_sorin_data:1> typeset -g -A git_info
+/tmp/zsh-prompt_sorin_data:2> git_info=( )
+prompt_sorin_git_info:6> RPROMPT+='${git_info:+${(e)git_info[status]}}'
+prompt_sorin_git_info:7> unalias typeset
+prompt_sorin_git_info:11> _prompt_sorin_precmd_async_pid=0
+prompt_sorin_git_info:14> zle
+prompt_sorin_git_info:14> zle reset-prompt

**Comment by danielshahaf** [comment]
pradeepcheers wrote on Sat, Aug 20, 2016 at 16:43:41 -0700:
> +prompt_sorin_git_info:11> _prompt_sorin_precmd_async_pid=0
> +prompt_sorin_git_info:14> zle
> +prompt_sorin_git_info:14> zle reset-prompt

Known issue: https://github.com/sorin-ionescu/prezto/issues/1026#issuecomment-156210936

Workaround available: https://github.com/sorin-ionescu/prezto/pull/1028/files

**Comment by pradeepcheers** [comment]
@danielshahaf, Thanks a lot for the workaround. Is it not a permanent fix? The PR[](https://github.com/sorin-ionescu/prezto/pull/1028/files) is still open

**Comment by danielshahaf** [comment]
It's not a "fix" because zsh should never segfault no matter what user scripts do.

Could you post the output of `print -r -- $widgets[reest-prompt]`?

**Comment by pradeepcheers** [comment]
The output for  print -r -- $widgets[reset-prompt] is empty line.
