### ISSUE TITLE
Tmux pane is closed when executing whatever command after sourcing .zshrc

### ISSUE THREAD

**Issue by zgqq** [zsh-users/zsh-syntax-highlighting#352]
`ooo/                 OS: Arch Linux
                `+oooo:                Kernel: x86_64 Linux 4.7.1-1-ARCH
               `+oooooo:               Uptime: 3h 38m
               -+oooooo+:              Packages: 531
             `/:-:++oooo+:             Shell: zsh 5.2
            `/++++/+++++++:            Resolution: 1920x1080
           `/++++++++++++++:           WM: i3
          `/+++ooooooooooooo/`         CPU: Intel Core i7-4710MQ CPU @ 3.5GHz
         ./ooosssso++osssssso+`        GPU: GeForce GTX 765M
        .oossssso-````/ossssss+`       RAM: 1581MiB / 15972MiB

**Comment by danielshahaf** [comment]
1. Please set the `set-remain-on-exit` tmux option and report what
error message appears, if any.

2. You might be running into this issue:
.
   https://github.com/zsh-users/zsh-autosuggestions/issues/126#issuecomment-217041261
.
See two comments down the page from that for a workaround.

**Comment by z1003031335** [comment]
@danielshahaf I tried to exec tmux set remain-on-exit on,giving me the message of Pane is dead.

**Comment by danielshahaf** [comment]
Sorry for the long silence;I missed your reply.  Does this still occur?  If it does, can you show the _smallest_ zshrc for which it occurs?  (Binary search your zshrc to find the most minimal reproducer.)

**Comment by danielshahaf** [comment]
Feedback timeout.   See #353 for known issues.
