### ISSUE TITLE
Bug: broken completion

### ISSUE THREAD

**Issue by gimbo** [zsh-users/zsh-syntax-highlighting#354]
Hi there,

[This commit from the 28th of March](https://github.com/zsh-users/zsh-syntax-highlighting/commit/2f18ba64e397f11b04e685eeaee802b7285510cc) seems to introduce a problem with completion, at least on my system.

The problem is that if I am typing the name of a command in the current working directory, including a leading `./`, completion picks up names of commands in other folders in my `$PATH`.

For example, let's say I'm doing some Django development and I want to run `./manage.py`.  Then, if I type `./man` and hit tab, it completes to `./man ` (with a trailing space), presumably because it's finding `man` in my `$PATH`. Same for `ls`, `sudo`, `yes`, `wc`, etc.

My understanding/expectation is that given the leading `./`, it should *only* complete to something in the cwd, and ignore the rest of `$PATH`.

I've stripped my `~/.zshrc` back to this single line and I still see the problem:

```
source $HOME/prog/others/zsh-users/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
```

Sadly I don't have the zsh knowledge to attempt to fix this, so I'm raising it as an issue. As a temporary workaround, I've rolled my local copy of `zsh-syntax-highlighting` back to [the previous commit](https://github.com/zsh-users/zsh-syntax-highlighting/commit/3ce01076b521d9ab37dce90f2e73bdf1d44ec3d7), which seems to work fine.

Other info:

```
ld% echo $PATH    
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

ld% zsh --version
zsh 5.0.2 (x86_64-pc-linux-gnu)

ld% lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```

**Comment by ascii-soup** [comment]
> I've stripped my ~/.zshrc back to this single line and I still see the problem:

And I'm assuming you've tried it without this line and the problem disappears? I realise this seems like a silly question, I just want to be 100% clear :)

**Comment by ascii-soup** [comment]
I can confirm that I see the same behaviour here, using master z-sy-h and zsh 5.2

**Comment by gimbo** [comment]
Yep, completely empty `.zshrc` fixes the problem. :-)

**Comment by gimbo** [comment]
Hmmm, I might be wrong about the commit that's introducing the problem though. I found it via a `git bisect`, but I've just cloned out a fresh version of the repo and checked out that commit and I'm not seeing it on that commit.  I did another bisect and it's looking like [this](https://github.com/zsh-users/zsh-syntax-highlighting/commit/12b879caf7a6f96921d1c03ab9b839a7f6c8eb1e) is the culprit but I might just be confusing myself so I'd recommend doing your own bisect rather than 100% trusting that aspect of the original report. Apologies for confusion.

**Comment by ascii-soup** [comment]
OK thanks for the info: I'll attempt to isolate it myself and see what I can come up with here.

**Comment by ascii-soup** [comment]
According to a git bisect I've just done, the first bad commit is 12b879caf7a6f96921d1c03ab9b839a7f6c8eb1e

**Comment by ascii-soup** [comment]
On closer inspection, it would appear that if I remove line 116/117:
```
elif ! builtin type -w -- $1 >/dev/null 2>&1; then
  REPLY=none
```

it works as expected again. Wrapping the `builtin type -w -- $1` inside `$()` also seems to prevent the completion of items on the PATH, but I'm not experienced enough in zsh to understand the ramifications of doing that :-)

**Comment by danielshahaf** [comment]
I think I see the problem: `./sudo<TAB>` gives me this output (with the `format` style set):

```
> external command
./sudo
> executable file
sudofoo*
> all matches
./sudo sudofoo
```

This doesn't happen for ./sud<TAB>, only for ./sudo<TAB>.

**Comment by ascii-soup** [comment]
I'll have to get you to explain all this to me on IRC at some point :)

**Comment by danielshahaf** [comment]
Even odder: I can reproduce the issue in `zsh -f` + `autoload compinit && compinit` + z-sy-h, but not in z-sy-h with this patch:

```diff
diff --git zsh-syntax-highlighting.zsh zsh-syntax-highlighting.zsh
index 9de8d61..855fe33 100644
--- zsh-syntax-highlighting.zsh
+++ zsh-syntax-highlighting.zsh
@@ -272,5 +272,6 @@ _zsh_highlight_bind_widgets()
   widgets_to_bind+=(zle-isearch-update)
 
   local cur_widget
+  widgets_to_bind=( expand-or-complete )
   for cur_widget in $widgets_to_bind; do
     case $widgets[$cur_widget] in
```

where `expand-or-complete` is the widget invoked by <kbd>TAB</kbd>.  Binding just `expand-or-complete` and `zle-line-finish` doesn't reproduce the bug either.

<hr>

I suspect this may be a [workers/39001](http://www.zsh.org/cgi-bin/mla/redirect?WORKERNUMBER=39001) problem — namely, an issue where simply installing a noop wrapper around a widget change its behaviour.

**Comment by danielshahaf** [comment]
The bug is triggers with `widgets_to_bind=( self-insert )` but not with `widgets_to_bind=()`.  

However, that alone is not the whole story: in `zsh -f` + `autoload compinit && compinit`, the command `func() { () { zle "$@" && : } .self-insert -- "$@" }; zle -N self-insert func` does not reproduce the issue.  That command mimics [the wrapping of the `self-insert` widget](https://github.com/zsh-users/zsh-syntax-highlighting/blob/11c908196700c00c4662295f44747a5826615c4b/zsh-syntax-highlighting.zsh#L297-L299).

**Comment by danielshahaf** [comment]
Found a reproducer:

```zsh
func() { () { zle "$@" && { if [[ $BUFFER == ./sudo ]]; then type -w ./sudo >/dev/null; fi } } .self-insert -- "$@" }; zle -N self-insert func
```

Without the `type -w` call it doesn't reproduce the problem.  This assumes `sudo` is in $PATH and `./sudofoo` exists and is executable.

**Comment by danielshahaf** [comment]
I reported the bug upstream: http://www.zsh.org/cgi-bin/mla/redirect?WORKERNUMBER=39099

Thanks for the report @gimbo, it was an interesting chase!  And thank you, @ascii-soup, for narrowing down the problem.

**Comment by danielshahaf** [comment]
The link should be [Running 'type' causes false positive hashed command completion](http://www.zsh.org/mla/workers/2016/msg01583.html).

**Comment by danielshahaf** [comment]
Fixed, and for future reference the upstream bug has been fixed too:

https://github.com/zsh-users/zsh/commit/b312abc93b3b8eae8feb4a9884b22f519a137c7f (workers/39104)
