### ISSUE TITLE
Installation fails in if there is no HEAD

### ISSUE THREAD

**Issue by penman** [zsh-users/zsh-syntax-highlighting#357]
This is really a corner case, but when attempting to install from a git repository with no commits (e.g. with `brew install --git zsh-syntax-highlighting` from [Homebrew](http://brew.sh), `make install` fails because the code _is_ in a git repo, but `HEAD` is undefined.

To fix this, an extra check needs to be added to the Makefile to check if `HEAD` is defined.

**Comment by danielshahaf** [comment]
> This is really a corner case, but when attempting to install from
> a git repository with no commits (e.g. with `brew install --git
> zsh-syntax-highlighting` from [Homebrew](http://brew.sh), `make
> install` fails because the code _is_ in a git repo, but `HEAD` is
> undefined.

I don't have OS X.  Could you describe what `brew install --git` does?
Can you provide a self-contained reproduction recipe (one using only git
and POSIX shell commands)?

The docs didn't tell me much:
https://github.com/Homebrew/brew/blob/2c35d2c939b3cf9dc3824042a824a9deb211f137/share/man/man1/brew.1#L318

/cc @phy1729

> To fix this, an extra check needs to be added to the Makefile to check
> if HEAD is defined.

**Comment by penman** [comment]
It's like a normal `brew install` (which just downloads a tarball, then [copies the `.zsh` files to a directory](https://github.com/Homebrew/homebrew-core/blob/2835103b0c7060ed4f8d232f71effe1d2d8e26b8/Formula/zsh-history-substring-search.rb#L11)), except it does this before copying:

```sh
git init
git add -A
```

Here's the relevant [part](https://github.com/Homebrew/brew/blob/2c35d2c939b3cf9dc3824042a824a9deb211f137/Library/Homebrew/build.rb#L117-L120) of the Homebrew source.

(This, admittedly, doesn't seem a very useful feature of Homebrew to me. I thought it would set up a bit more of the git configuration.)

Incidentally, I didn't actually encounter this issue on OS X, but rather on CentOS using [Linuxbrew](http://linuxbrew.sh). Linuxbrew and Homebrew both work the same way, though.

**Comment by danielshahaf** [comment]
Thanks for the details.  @phy1729 and I discussed this on IRC (#zsh-syntax-highlighting on freenode) and it seems to us that this should be patched locally in the brew package.

For reference here's Debian's patch: https://anonscm.debian.org/cgit/pkg-zsh/zsh-syntax-highlighting.git/tree/debian/patches/set-version.patch

**Comment by MikeMcQuaid** [comment]
Homebrew maintainer here. We don't like to carry patches that will never be merged upstream. Is there a possible solution that you'd consider including?

**Comment by danielshahaf** [comment]
> Homebrew maintainer here. We don't like to carry patches that will
> never be merged upstream. Is there a possible solution that you'd
> consider including?

I'm open to suggestions.  The invariant I'd like to maintain is that
.revision-hash and .version — aka $ZSH_HIGHLIGHT_REVISION and
$ZSH_HIGHLIGHT_VERSION — precisely identify the installed version, both
when installing from a git clone of upstream and when installing from
a tarball or a package.

The problem with special-casing "inside a git worktree that hasn't been
committed to" is that for non-brew users, it's more likely to mask
legitimate failure modes (some form of corruption in .git) than to be
the right thing.

Are there any plans to make brew --git clone the upstream repository
rather than start a new one?  I saw some comments to that effect on IRC,
but am not sure what the status of that idea is.

**Comment by penman** [comment]
[Re: our conversation about `brew install --git`'s behaviour Homebrew on the zsh-syntax-highlighting IRC, thought I'd just clarify that I'm not officially involved with Homebrew, just a contributor.]

**Comment by MikeMcQuaid** [comment]
@danielshahaf Actually I think we are fine with this being a Homebrew-only patch (or at least some workaround) as it's a fairly niche Homebrew behaviour.

**Comment by danielshahaf** [comment]
@MikeMcQuaid Alright.  Closing, but feel free to reopen if there's change on upstream's side needed too.

**Comment by MikeMcQuaid** [comment]
@danielshahaf Will do. Thanks for being a great upstream ❤️
