### ISSUE TITLE
Error: ZSH_HIGHLIGHT_STYLES: assignment to invalid subscript range

### ISSUE THREAD

**Issue by Lordanakun** [zsh-users/zsh-syntax-highlighting#359]
I got a few errors after add this package to my mac os:
dotfiles/zsh-syntax-highlighting/highlighters/brackets/brackets-highlighter.zsh:32: ZSH_HIGHLIGHT_STYLES: assignment to invalid subscript range

Terminal wont start. If I open the brackets-highlighter.zsh with vi. It complains:
~ /brackets-highlighter.zsh|32 error| bad substitution.

This is the source code of brackets-highlighter.zsh:

# Define default styles.
: ${ZSH_HIGHLIGHT_STYLES[bracket-error]:=fg=red,bold}
: ${ZSH_HIGHLIGHT_STYLES[bracket-level-1]:=fg=blue,bold}
: ${ZSH_HIGHLIGHT_STYLES[bracket-level-2]:=fg=green,bold}
: ${ZSH_HIGHLIGHT_STYLES[bracket-level-3]:=fg=magenta,bold}
: ${ZSH_HIGHLIGHT_STYLES[bracket-level-4]:=fg=yellow,bold}
: ${ZSH_HIGHLIGHT_STYLES[bracket-level-5]:=fg=cyan,bold}
: ${ZSH_HIGHLIGHT_STYLES[cursor-matchingbracket]:=standout}

Could you please help?

Thanks,

**Comment by phy1729** [comment]
What version of zsh are you running (what is the output of `echo $ZSH_PATCHLEVEL`)?

**Comment by Lordanakun** [comment]
zsh version 5.0.2.

**Comment by Lordanakun** [comment]
zsh version is 5.0.8

**Comment by Lordanakun** [comment]
I brew install zsh 5.1, still get the same errors.

**Comment by danielshahaf** [comment]
> I got a few errors after add this package to my mac os:
> dotfiles/zsh-syntax-highlighting/highlighters/brackets/brackets-highlighter.zsh:32: ZSH_HIGHLIGHT_STYLES: assignment to invalid subscript range

What's the output of `print -r -- ${+ZSH_HIGHLIGHT_STYLES} ${(t)ZSH_HIGHLIGHT_STYLES}`?

It should say "1 association" but I'm guessing for you it says "1
array".

**Comment by Lordanakun** [comment]
Thanks everyone, I got it fixed.

**Comment by flamendless** [comment]
How did you fixed it? I'm having this problem too

**Comment by danielshahaf** [comment]
(Try running the command I suggested in my last comment.)

**Comment by flamendless** [comment]
it returns 1 array

**Comment by danielshahaf** [comment]
Then something in your setup (re)declares `ZSH_HIGHLIGHT_STYLES` as a normal (not associative) array.

**Comment by hamedarman** [comment]
> Then something in your setup (re)declares ZSH_HIGHLIGHT_STYLES as a normal (not associative) array.

Can you please explain it in more details and a hint to solve this problem? It is about two days that I am struggling with my .zshrc file and con't fix it.

**Comment by Hacksaurus** [comment]
I'm having the same problem... I'm not sure how to fix this either...

**Comment by Siriki-Saikiran** [comment]
Having the same issue as well

**Comment by danielshahaf** [comment]
Run `zsh -x` and grep for `ZSH_HIGHLIGHT_STYLES`.  As I said before, that variable is declared as an associative array by z-sy-h, but something in your setups converts it to a plain array.

**Comment by Siriki-Saikiran** [comment]
This is what I'm getting when i run grep. I don't understand which file is causing the erro
```
+omz_termsupport_preexec:1> emulate -L zsh
+omz_termsupport_preexec:2> setopt extended_glob
+omz_termsupport_preexec:4> [[ '' == true ]]
+omz_termsupport_preexec:9> local CMD=grep
+omz_termsupport_preexec:10> local LINE='grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn} ZSH_HIGHLIGHT_STYLES'
+omz_termsupport_preexec:12> title '$CMD' '%100>...>$LINE%<<'
+title:1> emulate -L zsh
+title:2> setopt prompt_subst
+title:4> [[ '' == *term* ]]
+title:8> : '%100>...>$LINE%<<'
+title:10> case xterm-256color (cygwin | xterm*)
+title:12> print -Pn '\e]2;%100\>...\>\$LINE%\<\<\a'
+title:13> print -Pn '\e]1;\$CMD\a'
+powerlevel9k_preexec:1> _P9K_TIMER_START=1506804537.8026986122 
+zsh:1> grep '--color=auto' '--exclude-dir=.bzr' '--exclude-dir=CVS' '--exclude-dir=.git' '--exclude-dir=.hg' '--exclude-dir=.svn' ZSH_HIGHLIGHT_STYLE
This is what I get. I don't know if this helps
```

**Comment by danielshahaf** [comment]
I meant, run 'zsh -x' and then grep the output you get before the first shell prompt.

**Comment by Siriki-Saikiran** [comment]
Did you mean something like this? 
`zsh -x | grep "ZSH_HIGHLIGHT_STYLES"`
Sorry I'm noob at Linux

**Comment by danielshahaf** [comment]
Siriki SaiKiran wrote on Sat, 30 Sep 2017 21:37 +0000:
> Did you mean something like this? 
> `zsh -x | grep "ZSH_HIGHLIGHT_STYLES"`
> Sorry I'm noob at Linux

No, I didn't.  I meant: Run `zsh -x`, then, look among the lines printed before the first prompt for the string `ZSH_HIGHLIGHT_STYLES`.  You wouldn't literally run the command `grep` to do that; I was using "grep" as a verb.  (You can, e.g., run `zsh -x` under script(1), exit it at the first prompt, and then grep the `typescript` file.)

Cheers,

**Comment by Hacksaurus** [comment]
Coming back to this thread, I totally forgot what problem I had here, but I apparently fixed it later on...
This is what I have in my `.zshrc`
```
...SNIP...
#Extra
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)
ZSH_CACHE_DIR=$HOME/.cache/oh-my-zsh
if [[ ! -d $ZSH_CACHE_DIR ]]; then
  mkdir $ZSH_CACHE_DIR
fi
source $ZSH/oh-my-zsh.sh
source /usr/share/zsh-theme-powerlevel9k/powerlevel9k.zsh-theme

#Syntax Highlighting
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

ZSH_HIGHLIGHT_STYLES[default]=fg=250
ZSH_HIGHLIGHT_STYLES[unknown-token]=fg=red,bold
ZSH_HIGHLIGHT_STYLES[reserved-word]=fg=108
ZSH_HIGHLIGHT_STYLES[alias]=fg=063
ZSH_HIGHLIGHT_STYLES[builtin]=fg=063
ZSH_HIGHLIGHT_STYLES[function]=fg=063
ZSH_HIGHLIGHT_STYLES[command]=fg=063
ZSH_HIGHLIGHT_STYLES[precommand]=fg=069
ZSH_HIGHLIGHT_STYLES[path]=fg=249,underline
ZSH_HIGHLIGHT_STYLES[history-expansion]=fg=222
ZSH_HIGHLIGHT_STYLES[comment]=fg=245,italic
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]=fg=250
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]=fg=250
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]=fg=250
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]=fg=033
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]=fg=173
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]=fg=173
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]=fg=140
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]=fg=140
ZSH_HIGHLIGHT_STYLES[back-dollar-quoted-argument]=fg=140
ZSH_HIGHLIGHT_STYLES[bracket-level-1]=fg=250
ZSH_HIGHLIGHT_STYLES[bracket-level-2]=fg=250
ZSH_HIGHLIGHT_STYLES[bracket-level-3]=fg=250
ZSH_HIGHLIGHT_STYLES[bracket-level-4]=fg=250
ZSH_HIGHLIGHT_STYLES[cursor-matchingbracket]=fg=237,bold,bg=74 
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE=fg=240

#Background Jobs Function
set_default POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE true
prompt_background_jobs() {
local background_jobs_number=${$(jobs -l | wc -l)// /}
local wrong_lines=`jobs -l | awk '/pwd now/{ count++ } END {print count}'`
if [[ wrong_lines -gt 0 ]]; then
     background_jobs_number=$(( $background_jobs_number - $wrong_lines ))
  fi
  if [[ background_jobs_number -gt 0 ]]; then
    local background_jobs_number_print="1"
    if [[ "$POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE" == "true" ]] && [[ "$background_jobs_number" -gt 1 ]]; then
      background_jobs_number_print="$background_jobs_number"
    fi
    "$1_prompt_segment" "$0" "$2" "$DEFAULT_COLOR" "cyan" "$background_jobs_number_print" 'BACKGROUND_JOBS_ICON'
  fi
}
```
I think the error might be caused if you put your highlighting UNDER your source...

I hope this helps

**Comment by AaronFlower** [comment]
@danielshahaf If the output of `print -r -- ${+ZSH_HIGHLIGHT_STYLES} ${(t)ZSH_HIGHLIGHT_STYLES}` is  "1 array".  Just add one line  `typeset -gA ZSH_HIGHLIGHT_STYLES` before  any assignments of `ZSH_HIGHLIGHT_STYLES` to reset the type.

e.g.
```
typeset -gA ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[cursor]='bold'
```

**Comment by danielshahaf** [comment]
That wouldn't be very robust: whatever redeclared it as a plain array might do so again later.

**Comment by bkjoel** [comment]
I'll add in my 10 cents, sorry for necroing -
In my case `source .../zsh-syntax-highlighting.zsh` was after a reference I made to `ZSH_HIGHLIGHT_STYLES[unknown-token]="fg=208"` to darken the `unknown token` coloring and easing my eyes.

The solution was to move the reference to `ZSH_HIGHLIGHT_STYLES[unknown-token]="fg=208"` below `source .../zsh-syntax-highlighting.zsh`

**Comment by mahiki** [comment]
found this after similar problems, moved the highlight styles assignment to after sourcing zsh-syntax-highlighting.zsh. So yeah.
I think I should look into zsh package managers like antigen, zinit or ohmyzsh

**Comment by danielshahaf** [comment]
@mahiki The ordering issue is documented, isn't it?
