### ISSUE TITLE
Sign release tags

### ISSUE THREAD

**Issue by danielshahaf** [zsh-users/zsh-syntax-highlighting#360]
Downstreams (at least [debian][1]  and [homebrew][2]) prefer that release tags be PGP-signed.

[1]: https://lintian.debian.org/tags/debian-watch-may-check-gpg-signature.html
[2]: https://github.com/Homebrew/homebrew-core/pull/4386#discussion_r77437443

**Comment by danielshahaf** [comment]
Is the following a correct way of manufacturing a signed tag?

```zsh
% cat x
object a8728aae66c04e6aa057dbf6000a6c80d8061aa7
type commit
tag t3
tagger Daniel Shahaf <d.s@daniel.shahaf.name> 1472922258 +0000

this is a log message
% gpg -ba x
% git update-ref t3 $(cat x x.asc | gpg hash-object -t tag -w)
% git push --tags upstream
```

I know about `git tag -s`; I might not be able to use it directly, so I'm asking whether the above is equivalent to it.

**Comment by MikeMcQuaid** [comment]
@danielshahaf Sorry, some confusion here: Homebrew doesn't need it to be a signed tag but just that the SHA-1 does not change without notification.

**Comment by danielshahaf** [comment]
> Is the following a correct way of manufacturing a signed tag?

That was a whitebox approach.  A blackbox approach would be to set `git config --global gpg.program` to a proxy program that ships its stdin and argv to gpg ${somehow} and feeds back gpg's output.

**Comment by danielshahaf** [comment]
Asked #git on freenode and was told:

> […] The storage format for signed tags isn't -that- complex, so you could reengineer it, but it's not simple enough that there's a stream you can feed into gpg if you just move it to the right box
>
> (the signature is interleaved in the middle of the tag object)
>
> [object preamble]\0[headers headers headers][signature][optionally more headers][tag message]

**Comment by danielshahaf** [comment]
> Is the following a correct way of manufacturing a signed tag?

I've used the following procedure:

```sh
<generate the 6-line template above> > foo
gpg --armor --detach-sign foo
git update-ref refs/tags/0.5.0 $(cat foo foo.asc | git hash-object --stdin -t tag -w)
git push --tags
git tag -v 0.5.0
```
