### ISSUE TITLE
How to change the underline in directory name ?

### ISSUE THREAD

**Issue by Saurav92** [zsh-users/zsh-syntax-highlighting#363]
When I type a command which involves directory an underline shows in directory name. How to remove the underline ?

**Comment by ascii-soup** [comment]
From the documentation here (https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/main.md) you should be able to define a new style for paths as follows:

```
# To have paths colored instead of underlined
ZSH_HIGHLIGHT_STYLES[path]='fg=cyan'
```

**Comment by danielshahaf** [comment]
Thanks for the help with triaging issues, @ascii-soup.
