### ISSUE TITLE
Getting no such option: ignore_close_braces on zsh 4.3.11

### ISSUE THREAD

**Issue by DictumMortuum** [zsh-users/zsh-syntax-highlighting#368]
Up until the last commit, everything worked fine on a dev environment that still has zsh 4.3.11
Now I am getting  `_zsh_highlight_highlighter_main_paint:6: no such option: ignore_close_braces`

I know that it's mentioned that the supported version should be 4.3.17+ , so this is not a bug report; it's more of a warning for people, as I couldn't find anything relevant.

```
git:master+ on dev01 in ~ if [[ -o ignore_close_braces ]]; then echo "YES"; fi 
zsh: no such option: ignore_close_braces
git:master+ on dev01 in ~ zsh --version
zsh 4.3.11 (x86_64-redhat-linux-gnu)
```

compared to my local computer:

```
git:master on apparatus in ~ if [[ -o ignore_close_braces ]]; then echo "YES"; fi 
git:master on apparatus in ~ zsh --version                                        
zsh 5.1.1 (x86_64-ubuntu-linux-gnu)
```

**Comment by danielshahaf** [comment]
> Up until the last commit, everything worked fine on a dev environment that still has zsh 4.3.11
> Now I am getting  `_zsh_highlight_highlighter_main_paint:6: no such option: ignore_close_braces`
> 

The tricky part is that `[[ -o nosuchoption ]]` doesn't simply return false; it's considered a syntax error and aborts execution of the line.

The following would fix it:

```diff
diff --git a/highlighters/main/main-highlighter.zsh b/highlighters/main/main-highlighter.zsh
index 50408a0..af0ee67 100644
--- a/highlighters/main/main-highlighter.zsh
+++ b/highlighters/main/main-highlighter.zsh
@@ -176,7 +176,7 @@ _zsh_highlight_highlighter_main_paint()
   if [[ -o interactive_comments ]]; then
     local interactive_comments= # set to empty
   fi
-  if [[ -o ignore_braces ]] || [[ -o ignore_close_braces ]]; then
+  if [[ -o ignore_braces ]] || eval '[[ -o ignore_close_braces ]] 2>/dev/null'; then
     local right_brace_is_recognised_everywhere=false
   else
     local right_brace_is_recognised_everywhere=true
```

I'll commit that unless a better idea comes up.

> I know that it's mentioned that the supported version should be
> 4.3.17+ , so this is not a bug report; it's more of a warning for
> people, as I couldn't find anything relevant.

Thanks for the report.  I'm not sure why it says 4.3.17.  `git blame` traces that to adding uses of `:A`, which is present in zsh 4.3.10.  (Moreover, there was a bug report from a 4.3.9 user last month.)

**Comment by DictumMortuum** [comment]
To be honest, I didn't look into it that much (plus I don't have any idea what `:A` does :P). I just ssh'ed into the dev server and couldn't do anything, after pulling the latest version of my dotfiles, which includes a submodule for this repo, as all typed characters would trigger that error.

Everything worked fine in my local environment, so I knew that it had something to do with the zsh shell.

Considering that the supported version is the second line of the readme, it's a matter of respect not calling this a "bug", that's all.

**Comment by danielshahaf** [comment]
Oh, I wasn't expecting you to "look into" anything.  I posted the diff here so other z-sy-h developers could review the patch before it gets pushed.  Sorry if that wasn't clear.

I suggest you apply that patch locally for now.  I'll commit it tomorrow.

And to be clear: I consider this a bug.  (And the "4.3.17" declaration in README may be a docs bug; that's not trivial to ascertain.)

**Comment by DictumMortuum** [comment]
I was referring to looking into the version where the ignore_close_braces option was introduced.
Anyway, I guess that my contribution is over now, I leave it in your hands.
Cheers!

**Comment by danielshahaf** [comment]
> I was referring to looking into the version where the ignore_close_braces option was introduced.

It was introduced in 4.3.15.  Cheers!
