### ISSUE TITLE
Terminal crush after source

### ISSUE THREAD

**Issue by junhan-z** [zsh-users/zsh-syntax-highlighting#370]
I'm using zsh and oh-my-zsh configs, I noticed that after adding zsh-syntax-highlighting to plugins of OMZ, then if I do `source ~/.zshrc`, the terminal will crush.

**Comment by danielshahaf** [comment]
Does one of the scenarios in #353 apply to your setup?

**Comment by jackgu1988** [comment]
This applies in my case: https://github.com/zsh-users/zsh-autosuggestions/issues/126#issuecomment-217041261

Thanks for the help :+1:

**Comment by danielshahaf** [comment]
Closing: upstream issue with workaround available.

**Comment by junhan-z** [comment]
Thanks!
