### ISSUE TITLE
Disable path checking by directory

### ISSUE THREAD

**Issue by danielshahaf** [zsh-users/zsh-syntax-highlighting#379]
RFE: Disable path checking for some directories but not others.  Similar to the `vcs_info` [`disable-patterns` style](http://zsh.sourceforge.net/Doc/Release/User-Contributions.html#index-disable_002dpatterns).  This would be useful under expensive-to-readdir()/stat() mountpoints (e.g., sshfs).

This would need to check several things:
- [ ] Absolute filenames under DIR: `% stat /victim/foo/bar`
- [ ] Relative paths that resolve to paths under DIR (could use the `:a` modifier here, since it's disk-agnostic): `% stat ../victim/foo/bar`
- [ ] Any paths, when cwd is DIR:  `/victim% stat foo` (where the prompt displays cwd)
- [ ] Any of the foregoing, as a command word: `% /victim/foo/bar`

**Comment by danielshahaf** [comment]
Tentatively adding to 0.7.0 milestone.

**Comment by phy1729** [comment]
Any suggested array name? I think something like this would do the trick.

```
diff --git a/highlighters/main/main-highlighter.zsh b/highlighters/main/main-highlighter.zsh
index b8ed1a5..a3bdcf4 100644
--- a/highlighters/main/main-highlighter.zsh
+++ b/highlighters/main/main-highlighter.zsh
@@ -764,6 +764,13 @@ _zsh_highlight_main_highlighter_check_path()
   [[ -L $expanded_path ]] && return 0
   [[ -e $expanded_path ]] && return 0
 
+  # Check if this is a disallowed path
+  local path=$expanded_path:P
+  while [[ $path != / ]]; do
+    [[ -z ${path:|ZSH_HIGHLIGHT_XXX} ]] && return 1
+    path=$path:h
+  done
+
   # Search the path in CDPATH
   local cdpath_dir
   for cdpath_dir in $cdpath ; do
```

**Comment by danielshahaf** [comment]
XXX = DIRS_BLACKLIST

:P requires a new zsh, also it can access disk (as can the `[[` tests right above) so we need to be careful, is just readdir() expensive or also stat()?

Making `path` local requires `-h` (`-H`?).

Excuse brevity.
