### ISSUE TITLE
Version 0.5.0 doesn't work in latest oh-my-zsh

### ISSUE THREAD

**Issue by extesy** [zsh-users/zsh-syntax-highlighting#386]
After upgrading `zsh-syntax-highlighting` to 0.5.0 it doesn't work in oh-my-zsh anymore and shows these errors:

> zsh-syntax-highlighting: 'brackets' highlighter should define both required functions '_zsh_highlight_brackets_highlighter' and '_zsh_highlight_brackets_highlighter_predicate' in '/usr/local/share/zsh-syntax-highlighting/highlighters/brackets//brackets-highlighter.zsh'.
zsh-syntax-highlighting: 'cursor' highlighter should define both required functions '_zsh_highlight_cursor_highlighter' and '_zsh_highlight_cursor_highlighter_predicate' in '/usr/local/share/zsh-syntax-highlighting/highlighters/cursor//cursor-highlighter.zsh'.
zsh-syntax-highlighting: 'line' highlighter should define both required functions '_zsh_highlight_line_highlighter' and '_zsh_highlight_line_highlighter_predicate' in '/usr/local/share/zsh-syntax-highlighting/highlighters/line//line-highlighter.zsh'.
zsh-syntax-highlighting: 'main' highlighter should define both required functions '_zsh_highlight_main_highlighter' and '_zsh_highlight_main_highlighter_predicate' in '/usr/local/share/zsh-syntax-highlighting/highlighters/main//main-highlighter.zsh'.
zsh-syntax-highlighting: 'pattern' highlighter should define both required functions '_zsh_highlight_pattern_highlighter' and '_zsh_highlight_pattern_highlighter_predicate' in '/usr/local/share/zsh-syntax-highlighting/highlighters/pattern//pattern-highlighter.zsh'.
zsh-syntax-highlighting: 'root' highlighter should define both required functions '_zsh_highlight_root_highlighter' and '_zsh_highlight_root_highlighter_predicate' in '/usr/local/share/zsh-syntax-highlighting/highlighters/root//root-highlighter.zsh'.

**Comment by danielshahaf** [comment]
> After upgrading `zsh-syntax-highlighting` to 0.5.0 it doesn't work in oh-my-zsh anymore and shows these errors:
> 
> zsh-syntax-highlighting: 'brackets' highlighter should define both required functions '_zsh_highlight_brackets_highlighter' and '_zsh_highlight_brackets_highlighter_predicate' in '/usr/local/share/zsh-syntax-highlighting/highlighters/brackets//brackets-highlighter.zsh'.

In 0.5.0, the error message is different:

    print -r -- >&2 "zsh-syntax-highlighting: ${(qq)highlighter} highlighter should define both required functions '_zsh_highlight_highlighter_${highlighter}_paint' and '_zsh_highlight_highlighter_${highlighter}_predicate' in ${(qq):-"$highlighter_dir/${highlighter}-highlighter.zsh"}."

The error message you see is from 0.4.1 or earlier.

You'll need to check your zshrc to see why it sources the
`zsh-syntax-highlighting.zsh` from 0.4.1, instead of the one from 0.5.0.
You may have both 0.4.1 and 0.5.0 installed.

Version information is recorded in:

$ZSH_HIGHLIGHT_REVISION and /usr/local/share/zsh-syntax-highlighting/.revision-hash
$zSH_HIGHLIGHT_VERSION and /usr/local/share/zsh-syntax-highlighting/.version

**Comment by extesy** [comment]
You were right, it turns out I also had a conflicting old version of zsh-syntax-highlighting installed. I cleaned it up and the error is gone now. Thanks for the insight!
