### ISSUE TITLE
support for italics

### ISSUE THREAD

**Issue by ratheesh** [zsh-users/zsh-syntax-highlighting#394]
I would love to see support for italics in highlighters. Not sure if someone has already requested.

**Comment by danielshahaf** [comment]
> I would love to see support for italics in highlighters. Not sure if someone has already requested.

zsh-syntax-highlighting	can only set attributes that are exposed by zsh
upstream (documented on [`zshzle(1)`][1].  You'll have to make this
feature request of zsh upstream at zsh-users@zsh.org.

I'll close this issue now sincw there is nothing z-sy-h can do until zsh
implements this.

Thanks for the report.

[1]: http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#index-terminal-escape-sequences-for-highlighting
