### ISSUE TITLE
zsh-syntax-highlighting: unhandled ZLE widget 'up-line'

### ISSUE THREAD

**Issue by feluxe** [zsh-users/zsh-syntax-highlighting#396]
I just installed zsh-syntax-highlighting and get this error when starting zsh:

> zsh-syntax-highlighting: unhandled ZLE widget 'up-line'

**Comment by danielshahaf** [comment]
This might mean some other plugin had done `zle -N up-line foo` without defining the function `foo`.  Bisect or trace your startup to determine which other plugin does that.

**Comment by feluxe** [comment]
Your right! There was an issue with a key bind on up-line in my zshrc. My fault... Nothing to worry about.
Thanks for the info! :)
