### ISSUE TITLE
Errors on version 0.5.0

### ISSUE THREAD

**Issue by lylemoffitt** [zsh-users/zsh-syntax-highlighting#397]
After upgrading to version 0.5.0 I started immediately getting the following errors after opening a new shell. 
```
zsh-syntax-highlighting: 'brackets' highlighter should define both required functions '_zsh_highlight_brackets_highlighter' and '_zsh_highlight_brackets_highlighter_predicate' in '/usr/local/share/zsh-syntax-highlighting/highlighters/brackets//brackets-highlighter.zsh'.
zsh-syntax-highlighting: 'cursor' highlighter should define both required functions '_zsh_highlight_cursor_highlighter' and '_zsh_highlight_cursor_highlighter_predicate' in '/usr/local/share/zsh-syntax-highlighting/highlighters/cursor//cursor-highlighter.zsh'.
zsh-syntax-highlighting: 'line' highlighter should define both required functions '_zsh_highlight_line_highlighter' and '_zsh_highlight_line_highlighter_predicate' in '/usr/local/share/zsh-syntax-highlighting/highlighters/line//line-highlighter.zsh'.
zsh-syntax-highlighting: 'main' highlighter should define both required functions '_zsh_highlight_main_highlighter' and '_zsh_highlight_main_highlighter_predicate' in '/usr/local/share/zsh-syntax-highlighting/highlighters/main//main-highlighter.zsh'.
zsh-syntax-highlighting: 'pattern' highlighter should define both required functions '_zsh_highlight_pattern_highlighter' and '_zsh_highlight_pattern_highlighter_predicate' in '/usr/local/share/zsh-syntax-highlighting/highlighters/pattern//pattern-highlighter.zsh'.
zsh-syntax-highlighting: 'root' highlighter should define both required functions '_zsh_highlight_root_highlighter' and '_zsh_highlight_root_highlighter_predicate' in '/usr/local/share/zsh-syntax-highlighting/highlighters/root//root-highlighter.zsh'.
```

Furthermore, any time I would type something I would get the following error:
```
_zsh_highlight:29: command not found: _zsh_highlight_main_highlighter_predicate
```

Rolling back to 0.4.1 removed this issue.

**Comment by danielshahaf** [comment]
> After upgrading to version 0.5.0 I started immediately getting the following errors after opening a new shell. 

See https://github.com/zsh-users/zsh-syntax-highlighting/issues/386

**Comment by lylemoffitt** [comment]
I'm using `brew switch` for version management. Is that not sufficient? The version info in `/usr/local/share/zsh-syntax-highlighting/.version` matches as appropriate. 

After examining my `.zshrc` it turned out I wasn't sourcing `zsh-syntax-highlighting.zsh` at all (AFAIK). Adding  `source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh` stopped the `_zsh_highlight:29` errors, but not the first, larger block.

 Am I not sourcing the right file?
`MD5 (/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh) = 4d01aefd17b3525a988219f4fe646907`

**Comment by danielshahaf** [comment]
>  Am I not sourcing the right file?
> `MD5 (/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh) = 4d01aefd17b3525a988219f4fe646907`

That's indeed the file from 0.5.0:

```zsh
% git cat-file blob 0.5.0:zsh-syntax-highlighting.zsh | md5sum 
4d01aefd17b3525a988219f4fe646907  -
```

You probably have both 0.4.1 and 0.5.0 installed and sourced.  `zsh -o
sourcetrace` may find the culprit.

**Comment by lylemoffitt** [comment]
Calling `zsh -o sourcetrace` reveals the following:
```
+/Users/Lyle/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh:1> <sourcetrace>
```

It looks like this might be the cause of the second sourcing. It has a different hash, and substantially different contents. 
```
MD5 (/Users/Lyle/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh) = 6e6a235f680c1f45901d4b7d2ea3c1d7
```

Sure enough, removing `zsh-syntax-highlighting` from the `plugins=(...)` list solves the problem. So, I guess the onus is on Oh-My-Zsh to keep their plugin up to date?

**Comment by danielshahaf** [comment]
> Sure enough, removing `zsh-syntax-highlighting` from the `plugins=(...)` list solves the problem. So, I guess the onus is on Oh-My-Zsh to keep their plugin up to date?

omz should do that, yes, but also you shouldn't be sourcing z-sy-h twice.  OS packages and omz will generally provide you with different versions of z-sy-h; having both installed/sourced is just asking for trouble.

z-sy-h goes to some lengths to be idemptentily re-sourceable, but it wasn't designed to allow multiple versions of it to be sourced in the same shell.
