### ISSUE TITLE
Allow for nounset flag, particularly in _zsh_highlight_apply_zle_highlight

### ISSUE THREAD

**Issue by paxe** [zsh-users/zsh-syntax-highlighting#398]
This may be more a feature request than bug report, since I must be in a minority in liking to always use the nounset flag to help prevent typos and such.

In my setup _zsh_highlight_apply_zle_highlight aborts without inserting a
**setopt localoptions unset**
up front. This is likely not an ideal fix, and I expect it might indicate some initialization that could be better done.

**Comment by danielshahaf** [comment]
Agreed that the code should be `NO_UNSET`-clean.  (Either by avoiding
uninitialized variables, or by disabling that locally)

Would you be interested in writing the patch?

**Comment by paxe** [comment]
Sure, could do. I see that there are some tests included, that I've not looked at yet. I'd be interested in perhaps doing an improvement or two there as well,  and see if it'd help in coming up with something better than just a localoptions hack.

**Comment by danielshahaf** [comment]
> Sure, could do. I see that there are some tests included, that I've
> not looked at yet. I'd be interested in perhaps doing an improvement
> or two there as well,

Yes, please.  Just `setopt no_unset` at the top of test-highlighting.zsh
should do the trick.

Note that there are separate codepaths for zsh ≥5.3 [just released] and
≤5.2.  If you can do both, great; if not, let me know which one you
tested so I can handle the other one.

Thanks!

**Comment by paxe** [comment]
Opened a pull request #403 for this -- I guess handle that before closing this issue?

**Comment by danielshahaf** [comment]
> Opened a pull request #403 for this -- I guess handle that before closing this issue?

Yes, please leave the issue open until it's fixed in master.

**Comment by phy1729** [comment]
Closing since I think this is fixed now. Please reopen if it's not.
