### ISSUE TITLE
zsh-syntax-highlighting with zsh-autosuggestions bugs, source ~/.zshrc shell will broken

### ISSUE THREAD

**Issue by clay-f** [zsh-users/zsh-syntax-highlighting#401]
.zshrc config:
```
ZSH_THEME="robbyrussell"
plugins=( zsh-autosuggestions zsh-syntax-highlighting git z)
source $ZSH/oh-my-zsh.sh
```
`source ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh`
everything seem be fine.
` source ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh`
shell will be broken right away.

edit zsh-aut/src/start.zsh
```
_zsh_autosuggest_start() {
	_zsh_autosuggest_check_deprecated_config
	_zsh_autosuggest_bind_widgets
}

autoload -Uz add-zsh-hook
add-zsh-hook precmd _zsh_autosuggest_start
```

reference from <a href="https://github.com/zsh-users/zsh-autosuggestions/issues/126#issuecomment-217041261">#126</a>
zsh version:  zsh 5.3

**Comment by danielshahaf** [comment]
> and the shell will be broken.
> zsh version:  zsh 5.3

5.3 was released last week.  Did the problem occur with 5.2?

If not: see #353 and https://github.com/zsh-users/zsh-autosuggestions/issues/126

**Comment by clay-f** [comment]
oh, have see #126 , but not fount the fixed way, description have little complex,

have tried edit `plugins/zsh-autosuggestions/src/start.zsh` and make

but make no sense

**Comment by danielshahaf** [comment]
> oh, have see #126 , but not fount the fixed way, description have little complex,
> 
> have tried edit `plugins/zsh-autosuggestions/src/start.zsh` and make

After 'make' you should see zsh-autosuggestions.zsh modified.

I believe there was also another patch floating around the
zsh-autosuggestions issue tracker, unfortuantely I don't have a link
handy.

> but make no sense

Don't say "make no sense" in bug reports; describe what you're seeing.

http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by clay-f** [comment]
edit the `start.zsh` to
```
_zsh_autosuggest_start() {
        _zsh_autosuggest_check_deprecated_config
        _zsh_autosuggest_bind_widgets
       add-zsh-hook -d precmd _zsh_autosuggest_start
 }
autoload -Uz add-zsh-hook
```
then `make`,

i meaning is: `source ~/.zshrc` shell would be worked, but `z-aus` can't work. ^_^

**Comment by clay-f** [comment]
have tried again.

1. brew install zsh
2. config oh-my-zsh

the `.zshrc`:
```
ZSH_THEME="robbyrussell"
plugins=(zsh-autosuggestions zsh-syntax-highlighting  git)
source $ZSH/oh-my-zsh.sh
```

this is all, config.

**Comment by clay-f** [comment]
edit `zsh-autosuggestions/src/start.zsh` to

```
_zsh_autosuggest_start() {
        _zsh_autosuggest_check_deprecated_config
        _zsh_autosuggest_bind_widgets
       add-zsh-hook -d precmd _zsh_autosuggest_start
 }
autoload -Uz add-zsh-hook
```

`make`, show info :
```
cat DESCRIPTION URL VERSION LICENSE | sed -e 's/^/# /g' > zsh-autosuggestions.zsh
cat ./src/config.zsh ./src/deprecated.zsh ./src/bind.zsh ./src/highlight.zsh ./src/widgets.zsh ./src/suggestion.zsh ./src/strategies/*.zsh ./src/start.zsh >> zsh-autosuggestions.zsh
```

**Comment by seagle0128** [comment]
same issue here.

**Comment by akhy** [comment]
same issue here, using `zplug` as plugin manager... confirmed the two plugins cannot activated together, would cause broken pipe in my iterm2

my setup:
- `zplug`
- `zsh 5.3.1 (x86_64-apple-darwin15.6.0)` (from homebrew)
- `zsh-syntax-highlighting` `master`/`9523d6d49cb3d4db5bd84c3cec6168a2057fe3ab`
- `zsh-autosuggestions` `master`/`fedc22e9bbd046867860e772d7d6787f5dae9d4c`

additional info: starting the shell the first time is no problem, the broken pipe occurs when I manually `source ~/.zshrc`

**Comment by danielshahaf** [comment]
> same issue here, using `zplug` as plugin manager... confirmed the two plugins cannot activated together, would cause broken pipe in my iterm2
> 
> my setup:
> - `zplug`
> - `zsh 5.3.1 (x86_64-apple-darwin15.6.0)` (from homebrew)
> - `zsh-syntax-highlighting` `master`/`9523d6d49cb3d4db5bd84c3cec6168a2057fe3ab`
> - `zsh-autosuggestions` `master`/`fedc22e9bbd046867860e772d7d6787f5dae9d4c`
> 
> additional info: starting the shell the first time is no problem, the broken pipe occurs when I manually `source ~/.zshrc`

Have you tried the workarounds posted above?

**Comment by Kutsan** [comment]
And same issue.

**Comment by danielshahaf** [comment]
zsh-users/zsh-autosuggestions#126 is fixed.  Reopen this issue or that one if the problem persists.
