### ISSUE TITLE
Ideas about a theme manager

### ISSUE THREAD

**Issue by melmi** [zsh-users/zsh-syntax-highlighting#402]
I don't know is this the right place to discuss this idea or not. But I start this thread anyway. 

I want to start a theme manager for `zsh-syntax-highlighting`. My main idea is to define 16-color palettes which would be nothing but arrays of styles. The user then can simply invoke the desired theme by calling something like `apply-zsh-syntax-highlighting-theme(some-theme)`.  This function simply assigns the content of the theme palette array to corresponding keys of `$ZSH_HIGHLIGHT_STYLES` of each highlighter.

I'm not sure whether this idea worth working on or not. I also don't know if is it better to define this idea as a part of `zsh-syntax-highlighting` itself (through a pull request for example) or as a separate plugin. So I'm writing this to ask for your kind comments.

**Comment by phy1729** [comment]
Support for themes has been started in https://github.com/zsh-users/zsh-syntax-highlighting/pull/241. Part of the reason of why it isn't merged is lack of feedback, so any feedback you may have would be greatly appreciated.
