### ISSUE TITLE
zsh-syntax-highlighting: unhandled ZLE widget 'vi-backward-delete-char-incr'

### ISSUE THREAD

**Issue by rexlow** [zsh-users/zsh-syntax-highlighting#404]
I tried to source the plugin and it was fine until I reload my terminal.

It complains about this error every time I launch my terminal

`zsh-syntax-highlighting: unhandled ZLE widget 'vi-backward-delete-char-incr'`

**Comment by danielshahaf** [comment]
> zsh-syntax-highlighting: unhandled ZLE widget 'vi-backward-delete-char-incr'

That's not a widget from zsh so it must be defined by some other plugin.

This error generally means that other plugin did `bindkey x
vi-backward-delete-char-incr foo` without defining the widget `foo`.

**Comment by rexlow** [comment]
Thanks for the input. I have found the cause of the problem. It was a program I installed, Bit. Bit injected a zsh dot file and its causing the problem

**Comment by danielshahaf** [comment]
> Thanks for the input. I have found the cause of the problem. It was a program I installed, Bit. Bit injected a zsh dot file and its causing the problem

Thanks for sharing the caused.  Glad it's resolved.
