### ISSUE TITLE
`bundle exec`-style commands make third argument red unless it's in $PATH

### ISSUE THREAD

**Issue by habibalamin** [zsh-users/zsh-syntax-highlighting#405]
Possibly, `exec`'s inclusion in `ZSH_HIGHLIGHT_TOKENS_PRECOMMANDS` is causing this.

I noticed this with a custom `npm` function I wrote to hijack `npm exec` (God, I hate the JS ecosystem). I've reproduced it with `bundle exec`, too (I used it as the title, because it's the canonical example). I kept trying to replicate this with another function, and only then realised that it's the use of `exec` that causes the red highlight. No other subcommand does this (again, including with Bundler).

**Comment by danielshahaf** [comment]
> Possibly, `exec`'s inclusion in `ZSH_HIGHLIGHT_TOKENS_PRECOMMANDS` is causing this.
> 
> I noticed this with a custom `npm` function I wrote to hijack `npm exec` (God, I hate the JS ecosystem). I've reproduced it with `bundle exec`, too (I used it as the title, because it's the canonical example). I kept trying to replicate this with another function, and only then realised that it's the use of `exec` that causes the red highlight. No other subcommand does this (again, including with Bundler).

I cannot reproduce this: «bundle exec foo» colors 'bundle' in red (or
green, if I define it first as a function/alias) and the rest in white.

Please provide a minimal reproduction recipe starting from 'zsh -f'.
Thanks!

What's the output of `which bundle`?  Is the word "exec" in green and underlined?

**Comment by habibalamin** [comment]
I am also unable to reproduce this with a brand new installation of `antigen` and `zsh-syntax-highlighting`. I'll get back to you when I have managed to do so. I don't think I've changed anything in that regard, so I'll have to see what's different between my installation vs. a brand new one (I even tried resetting the repo to the same commit).

**Comment by habibalamin** [comment]
My dotfiles were in a state of flux with regard to antigen and Oh My ZSH, anyway, so I've reorganised them, and I've now got it working the same as you. Just in case anyone's wondering how I fixed it.
