### ISSUE TITLE
Color Blind Friendliness

### ISSUE THREAD

**Issue by applesjgtl** [zsh-users/zsh-syntax-highlighting#410]
I have a friend who can't see the red/green command highlighting due to colorblindness who loves the concept. Any way we can add support for an alternate 'safe' color palette?

**Comment by danielshahaf** [comment]
> I have a friend who can't see the red/green command highlighting due to colorblindness who loves the concept. Any way we can add support for an alternate 'safe' color palette?

Certainly.

In the longer term we plan to add support for themes, see #241; with
that branch, we could add a 'red-green-colorblind' theme and then it
would be a one-line configuration.

In the meantime, you could just change the values of the associative
array $ZSH_HIGHLIGHT_STYLES.  If there's a particular set of 'safe'
alternate colors to use, we could add it to the documentation (and later
to the 'themes' branch).

But to be honest, I suspect your friend would be best served by shifting
his terminal emulator's color palette, so colors 1-16 or 1-88 or 1-256
(as the case may be) are all shades he can easily distinguish.  I'm
afraid I don't have a specific recommendation for how to do...

**Comment by danielshahaf** [comment]
@Pound-Hash Thanks for sharing those.  I see they are licensed under CC-BY 4.0.  If you'd like to add them to the documentation on the master branch or to the themes branch, please open a new issue or pull request.

**Comment by Pound-Hash** [comment]
> @Pound-Hash Thanks for sharing those. I see they are licensed under CC-BY 4.0. If you'd like to add them to the documentation on the master branch or to the themes branch, please open a new issue or pull request.

Word. When they're ready, I'll make a pr like a kitty do.

**Comment by Pound-Hash** [comment]
> @Pound-Hash Thanks for sharing those. I see they are licensed under CC-BY 4.0. If you'd like to add them to the documentation on the master branch or to the themes branch, please open a new issue or pull request.

Just filed a PR for this

**Comment by danielshahaf** [comment]
> Just filed a PR for this

That's #869.
