### ISSUE TITLE
unhandled ZLE widget error since 0.5.0

### ISSUE THREAD

**Issue by rotsix** [zsh-users/zsh-syntax-highlighting#411]
Hi guys,

since version 0.5.0, and zsh 5.3.1 on Arch 4.8.13,

an error appears everytime I launch zsh (login,terminal..)

This one : 
```
zsh-syntax-highlighting: unhandled ZLE widget 'history-substring-search-up'
zsh-syntax-highlighting: unhandled ZLE widget 'history-substring-search-down'
```

With an empty zshrc, error still appears.

Any idea ? thx :)

**Comment by danielshahaf** [comment]
> Hi guys,
> 
> since version 5.0.0, and zsh 5.3.1 on Arch 4.8.13,

ITYM 0.5.0, but thanks for giving these details up front.

> an error appears everytime I launch zsh (login,terminal..)
> 
> This one : 
> ```
> zsh-syntax-highlighting: unhandled ZLE widget 'history-substring-search-up'
> zsh-syntax-highlighting: unhandled ZLE widget 'history-substring-search-down'
> ```
> 
> With an empty zshrc, error still appears.

That's be odd.  Launch zsh as `zsh -x` to see which startup files it
reads (and what they do to these two widgets).  See also #409.

**Comment by rotsix** [comment]
I'll try when i'm back home. Thx !

**Comment by rotsix** [comment]
I searched a little, and found this : 
`bindkey "$terminfo[kcuu1]" history-substring-search-up`

I think that could come from here. Any idea about it ? is it needed ?
(i've this line in both /etc/zsh/zshrc and ~/.zshrc)

Thx

**Comment by danielshahaf** [comment]
> I searched a little, and found this : 
> `bindkey "$terminfo[kcuu1]" history-substring-search-up`
> 
> I think that could come from here. Any idea about it ?

None at all.  Are you sure you didn't put it there?  It's not part of
upstream and Arch doesn't usually patch its packages.

> is it needed ?

It probably breaks your up-arrow key, since it maps it to a nonexistent
widget.  See how that key behaves with/without that binding.  Binding to
undefined-key is also an option.

Unless you install history-substring-search-up _after_ sourcing z-sy-h
in your dotfiles.  In this case, just put z-sy-h last.

> (i've this line in both /etc/zsh/zshrc and ~/.zshrc)

Ah, because you emptied your zshrc, which is not the same as `zsh -f`.

**Comment by rotsix** [comment]
wow, forgot `zsh -f`

With it, it works perfectly.

So the problem comes from the bind. I'll remove it, since there is no difference with or without it.

You can close issue, Mea Culpa !

**Comment by katylava** [comment]
I ran into this as well after I installed https://github.com/zsh-users/zsh-history-substring-search. The problem was the order in which I was defining key bindings and sourcing the two plugins.

**1. bind keys first, recommended order of sources**

- history search works properly and has syntax highlighting
- syntax highlighting displays errors

```
bindkey '\e[A' history-substring-search-up
bindkey '\e[B' history-substring-search-down

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/local/share/zsh-history-substring-search/zsh-history-substring-search.zsh
```

**2. bind keys first, switch order of sources**

- history search works, but doesn't have syntax highlighting
- syntax highlighting doesn't display any errors

```
bindkey '\e[A' history-substring-search-up
bindkey '\e[B' history-substring-search-down

source /usr/local/share/zsh-history-substring-search/zsh-history-substring-search.zsh
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
```

**3. bind keys last, recommended order of sources**

- history search works and has syntax highlighting
- syntax highlighting doesn't report any errors

```
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/local/share/zsh-history-substring-search/zsh-history-substring-search.zsh

bindkey '\e[A' history-substring-search-up
bindkey '\e[B' history-substring-search-down
```

So, 3 works, though I'd prefer to have my key bindings first, but it's not that big of a deal.

**Comment by danielshahaf** [comment]
> I ran into this as well after I installed https://github.com/zsh-users/zsh-history-substring-search. The problem was the order in which I was defining key bindings and sourcing the two plugins.
> 

Thanks for the details @katylava!

> **1. bind keys first, recommended order of sources**
> 
> - history search works properly and has syntax highlighting
> - syntax highlighting displays errors
> 
> ```
> bindkey '\e[A' history-substring-search-up
> bindkey '\e[B' history-substring-search-down
> 
> source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

At this point, history-substring-search-* are partially initialized, they have been referenced by bindkey but not yet created with `zle -N`.  I remember fixing this, are you using latest master of z-sy-h?

> source /usr/local/share/zsh-history-substring-search/zsh-history-substring-search.zsh
> ```
> 
> **2. bind keys first, switch order of sources**
> 
> - history search works, but doesn't have syntax highlighting
> - syntax highlighting doesn't display any errors
> 
> ```
> bindkey '\e[A' history-substring-search-up
> bindkey '\e[B' history-substring-search-down
> 
> source /usr/local/share/zsh-history-substring-search/zsh-history-substring-search.zsh
> source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
> ```

Here, by the time z-sy-h runs, all widgets are properly defined.  What version of zsh are you using?  z-sy-h works better with more recent zsh's.

> 
> **3. bind keys last, recommended order of sources**
> 
> - history search works and has syntax highlighting
> - syntax highlighting doesn't report any errors
> 
> ```
> source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
> source /usr/local/share/zsh-history-substring-search/zsh-history-substring-search.zsh
> 
> bindkey '\e[A' history-substring-search-up
> bindkey '\e[B' history-substring-search-down
> ```
> 
> So, 3 works, though I'd prefer to have my key bindings first, but it's not that big of a deal.

Try your option (1) but also add `zle -N history-substring-search-up; zle -N history-substring-search-down` before either `source` command?

**Comment by katylava** [comment]
> I remember fixing this, are you using latest master of z-sy-h?

Using 0.5.0 installed with homebrew.

> What version of zsh are you using?

`zsh 5.2 (x86_64-apple-darwin16.0)` ... which surprised me as I thought I had installed it with homebrew.

> Try your option (1) but also add `zle -N history-substring-search-up; zle -N history-substring-search-down` before either `source` command?

That works, thank you!

**Comment by erdaltoprak** [comment]
On Mac OS Catalina with Zsh 5.7.1 everything installed through homebrew, I had to put the bindkeys at the very end as @katylava suggested

**Comment by peteromero** [comment]
@katylava @erdaltoprak thanks - that did the trick on Arch Linux, as well (zsh 5.8).
