### ISSUE TITLE
%N in prompt shows "_zsh_highlight_call_widget" on Ctrl-L instead of e.g. "/usr/bin/zsh" or "-zsh" since recently

### ISSUE THREAD

**Issue by xtaran** [zsh-users/zsh-syntax-highlighting#414]
I'm not sure since when this happens, but that part of my prompt hasn't changed for quite a while and this happens for a few weeks now, maybe since the z-sy-h 0.5.0 release or since the zsh 5.3 release, but at least with the combination of z-sy-h 0.5.0 and zsh 5.3.1:

Everytime I press Ctrl-L in my xterm, `%N` inside my prompt shows `_zsh_highlight_call_widget` instead of e.g. `/usr/bin/zsh` or `-zsh`:

Normal prompt:

```
!5334 Z5 ?0 L1 user@host:~ (pts/39 -zsh 5.3.1 stretch) 21:35:56 
~ → 
```

After Ctrl-L:

```
!5334 Z2 ?0 L1 user@host:~ (pts/39 _zsh_highlight_call_widget 5.3.1 stretch) 21:36:18 
~ → 
```

How to reproduce:

```
~ → zsh -f
host% . /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 
host% PS1='%N %% '
zsh % ^L
_zsh_highlight_call_widget % 
```

I'm not sure if this is an issue with z-sy-h or if I should just not expect `%N` to always show `zsh` (with or without path and or the dash indicating a login shell) and should just use `$0` instead of `%N`.

**Comment by danielshahaf** [comment]
Hello Axel!

> ```
> ~ → zsh -f
> host% . /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 
> host% PS1='%N %% '
> zsh % ^L
> _zsh_highlight_call_widget % 
> ```
> 

I can reproduce this without z-sy-h:

```zsh
$ zsh -f
% clear-screen() { zle .$WIDGET -- "$@" }
% zle -N clear-screen 
% PS1='%1N %# '
zsh % <^L>
clear-screen % 
```

That's with zsh master; with zsh 5.0.7 from debian stable, the last
prompt says "zsh", …

> should just use `$0` instead of `%N`.

… so this is an upstream change.  I am not sure whether it's a regression
or a bugfix.

Is a change on z-sy-h's side needed?

(I quickly grepped upstream's git, but haven't found anything yet)

**Comment by xtaran** [comment]
> I can reproduce this without z-sy-h:

Oh, I didn't think of trying that after I saw one of z-sy-h's function names in there.

> … so this is an upstream change. I am not sure whether it's a regression or a bugfix.

Yes, I see it now that way, too. Will report it on zsh-workers.

> Is a change on z-sy-h's side needed?

I have no idea. Feel free to close the issue, if you want.

**Comment by danielshahaf** [comment]
> I have no idea. Feel free to close the issue, if you want.

Closing; please reopen if needed.
