### ISSUE TITLE
rpm packages

### ISSUE THREAD

**Issue by nicoulaj** [zsh-users/zsh-syntax-highlighting#419]
Hi,

I have started creating packages for zsh-users projects on OpenSUSE build service: https://build.opensuse.org/project/subprojects/shells:zsh-users

It is an easy way to build, maintain and distribute packages for many distributions at once (Debian and derivatives/RHEL and derivatives/Fedora/SUSE...). The packaging quality is very low (just puts files in /usr/share), but I guess it can still be useful to users, and we can improve it later if experienced packagers step in.

The package for this project is [here](https://build.opensuse.org/package/show/shells:zsh-users:zsh-syntax-highlighting/zsh-syntax-highlighting), and users can download it from [here](https://software.opensuse.org/download.html?project=shells%3Azsh-users%3Azsh-syntax-highlighting&package=zsh-syntax-highlighting).

Maybe you could add a mention in your README like [I did in zsh-completions](https://github.com/zsh-users/zsh-completions#using-packages) ?

**Comment by danielshahaf** [comment]
Just go ahead and add it to INSTALL?  Note we already have native debian/fedora packages so I think it's just opensuse that needs adding.
