### ISSUE TITLE
Support for 24-bit (16M) colors?

### ISSUE THREAD

**Issue by magiruuvelvet** [zsh-users/zsh-syntax-highlighting#420]
Is there any way to make use of more colors when the terminal emulator supports it. There is this escape sequence for example `\e[38;2;0;118;154m` which changes the foreground text color to #00769A RGB. I could not find a way to tell `ZSH_HIGHLIGHT_STYLES` to use any of those colors.

I tried `fg=`
 - `38;2;...`
 - hex `RRGGBB`
 - hex `0xRRGGBB`
 - in decimal
 - and even `$(printf '\e...')`

None of those changed the color to a 24-bit one.

This seems like a huge customization limitation. Any way to fix this easily?

**Comment by danielshahaf** [comment]
This restriction is inherited from zsh:

**Comment by danielshahaf** [comment]
This restriction is inherited from zsh:

http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#Character-Highlighting

z-sy-h cannot support what the underlying zsh doesn't.  I suggest you follow up on zsh-users@zsh.org.

**Comment by danielshahaf** [comment]
Once zsh supports this, z-sy-h should automatically support this, too; so closing this as no code changes are required.  Thanks @phy1729.
