### ISSUE TITLE
color resets to default (solved)

### ISSUE THREAD

**Issue by ralpheeee88** [zsh-users/zsh-syntax-highlighting#424]
(.zsh/zsh-autosuggestions/src/config.zsh)
when changing ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=green' 
and souring the file it works in the terminal until i open a new terminal; after which it resets to the default color. How can i make the change in color perminant?

**Comment by danielshahaf** [comment]
> (.zsh/zsh-autosuggestions/src/config.zsh)
> when changing ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=green' 
> and souring the file it works in the terminal until i open a new terminal; after which it resets to the default color. How can i make the change in color perminant?

I think you're meant to run `make` in the parent directory (`src/..`)
and source the amalgamated file, not the individual files in `src/`.

That said, you're asking at the wrong place; that's a z-asug question,
not a z-sy-h question.

/cc @ericfreese

**Comment by ericfreese** [comment]
@ralpheeee88 see the instructions on configuration in the z-asug readme: https://github.com/zsh-users/zsh-autosuggestions#configuration

You need to run `ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=green'` in every shell session. The best way to do that is not to modify `src/config.zsh` but to add that line to your `.zshrc`. Make sure it comes *after* you source `zsh-autosuggestions.zsh`.

If you're still having trouble, feel free to open an issue in [the z-asug issue tracker](https://github.com/zsh-users/zsh-autosuggestions/issues).

**Comment by ralpheeee88** [comment]
Super... Thxs guys!!!!
