### ISSUE TITLE
Why doesn't this plugin work on CentOS 7? 

### ISSUE THREAD

**Issue by fusion809** [zsh-users/zsh-syntax-highlighting#428]
Hi,

On my CentOS 7 VM this plugin doesn't work, by which I mean there is no syntax-highlighting at all, the text is left as gray against a black background. Here is a screenshot to show you what I mean:

![zsh-see-no-syntax-highlighting](https://cloud.githubusercontent.com/assets/4717341/25301584/80eaa1b0-276e-11e7-8e9d-8710c650be91.png)

See not one of these lines is syntax-highlighted. Now naturally you'll want my `~/.zshrc` well [here](https://github.com/fusion809/centos-scripts/blob/master/.zshrc), or if you want it at this precise point in time, as I am asking this question (as it will undoubtedly change when you's give me a solution), [here](https://github.com/fusion809/centos-scripts/blob/009d481/.zshrc) it is. On shell startup I get no errors, in case you're wondering if the line:

```bash
export TERM="xterm-256color"
```

is failing due to some limited colouring support. I use oh-my-zsh here is my plugins line for quick reference:

```bash
plugins=(git github zsh-syntax-highlighting safe-paste)
```

Lastly, my Zsh version is 5.3.1. I have an Open Build Service project in which I build the latest Zsh, which is presently 5.3.1 ([here](https://build.opensuse.org/package/show/home:fusion809/zsh) is the URL). Any ideas what the problem is?

Thanks for your time,
Brenton

**Comment by danielshahaf** [comment]
> Any ideas what the problem is?

No.

Does `print -rP -- '%F{red}hello world%f'` print "hello world" in red?

Try running `zsh -f` and therein `source zsh-syntax-highlighting.zsh`; do colors work then?

What's the output of `typeset -p ZSH_HIGHLIGHT_HIGHLIGHTERS ZSH_HIGHLIGHT_REVISION ZSH_HIGHLIGHT_VERSION ZSH_VERSION ZSH_PATCHLEVEL`?

**Comment by danielshahaf** [comment]
Feedback timeout.
