### ISSUE TITLE
No syntax highlighting until (e.g.) left/right is pressed, when oh-my-zsh is present

### ISSUE THREAD

**Issue by anntzer** [zsh-users/zsh-syntax-highlighting#429]
With the latest zsh-syntax-highlighting, latest oh-my-zsh (both loaded by zplug) and zsh 5.3.1, no syntax highlighting occurs while text is being typed.  When I press left/right to move the cursor, however, highlighting is correctly triggered.

Removing oh-my-zsh (from the zplug config) solves the issue, though, so it's probably some weird interaction between the two.

**Comment by danielshahaf** [comment]
Perhaps something overwrites the `self-insert` widget.  Try to diff `bindkey -L` outputs with/without omz.

**Comment by anntzer** [comment]
Without OMZ:
bindkey -R "^A"-"^C" self-insert
bindkey -R "^E"-"^F" self-insert
bindkey "^K" self-insert
bindkey -R "^N"-"^P" self-insert
bindkey -R "^S"-"^T" self-insert
bindkey -R "^Y"-"^Z" self-insert
bindkey -R "^\\\\"-"~" self-insert
bindkey -R "\M-^@"-"\M-^?" self-insert

With OMZ:
bindkey -R "^B"-"^C" self-insert
bindkey "^F" self-insert
bindkey "^K" self-insert
bindkey "^O" self-insert
bindkey -R "^S"-"^T" self-insert
bindkey -R "^Y"-"^Z" self-insert
bindkey -R "^\\\\"-"~" self-insert
bindkey -R "\M-^@"-"\M-^?" self-insert

**Comment by danielshahaf** [comment]
Thinko on my part, I meant `${widgets[self-insert]}` and, if it's of the
form "user:foo", the function `foo`.

Or you could try to bisect omz; I'm not going to try that.

**Comment by anntzer** [comment]
Thanks, found it: it is omz/lib/misc.zsh which loads url-quote-magic.
Loading zsh-syntax-highlighting *after* omz solves the issue.

**Comment by danielshahaf** [comment]
> Loading zsh-syntax-highlighting *after* omz solves the issue.

Yes, that's the supported & documented order.

**Comment by anntzer** [comment]
Apologies for the noise, then :-)
