### ISSUE TITLE
Highlight EQUALS command name filename expansion as error

### ISSUE THREAD

**Issue by danielshahaf** [zsh-users/zsh-syntax-highlighting#430]
`: =foo` should highlight `=foo` as an error ([unknown-token]) when

1. The EQUALS option is set
2. The expansion would fail, as in

        % : =foo
        zsh: foo not found

**Comment by phy1729** [comment]
What should `: =foo$variable` do? Evaluating a variable (or worse a command substitution) can execute code.

**Comment by danielshahaf** [comment]
The parser would classify this as a "command execution using EQUALS but I don't know whether that command exists".  I'm not sure what style the default theme would use in this case.

**Comment by danielshahaf** [comment]
It sounds like we need an "I don't know whether or not this is unknown-token" highlighting for this case and for, say, `${:-$(foo)}` at command position.
