### ISSUE TITLE
Typing in backslash 4 times + any character makes Cygwin/Mintty "freeze"

### ISSUE THREAD

**Issue by guixxx** [zsh-users/zsh-syntax-highlighting#431]
I made a short video to show what I mean by "freeze":

https://youtu.be/jwiOIkYfGYo

I have no knowledge about `zsh-syntax-highlighting` inner works, but for me it feels like **everything** I type before the 4th backslash gets buffered, and then after I press Ctrl+c it unbuffers all at once... My system info:

```
Windows 10 64-bit
Cygwin 2.8.0 x86_64
mintty 2.7.6 (x86_64-pc-cygwin)
antigen (git master)
zsh-syntax-highlighting (git master)
```

Thanks in advance.

**Comment by danielshahaf** [comment]
Does it happen in `zsh -f` + `source zsh-syntax-highlighting.zsh`?

**Comment by guixxx** [comment]
Yes.

**Comment by guixxx** [comment]
I've realized that it will eventually show the characters I typed after the `\\\\`, but it takes ~7 seconds for them to show up.

**Comment by danielshahaf** [comment]
> I've realized that it will eventually show the characters I typed
> after the `\\\\`, but it takes ~7 seconds for them to show up.  

Once you typed «\\\\f» it's probably trying to resolve "f" as
a hostname, then when you type «o» to get «\\\\fo» it tries to resolve
"fo" as a hostname, and so on.

Can you confirm this theory?

Not sure what to say.  The z-sy-h code doesn't treat cygwin specially;
it tries to interpret «\\\\f» as a filename because on unix that's
actually a valid filename.

**Comment by guixxx** [comment]
Bingo! Do you know any way to disable this behavior or it's impossible? Thanks!

**Comment by danielshahaf** [comment]
> Bingo! Do you know any way to disable this behavior or it's impossible? Thanks!

I can think of a few directions:

- make the underlying hostname resolution fast

- have cygwin time out on slow hostname resolutions

- disable path highlighting for «\\*» patterns on cygwin (that's two literal backslashes)

- disable path highlighting entirely: it'd be reasonable to
  skip path highlighting if the `[path]` style is set to the same value
  as the default style

Regarding the tlatter two, the relevant function is
`_zsh_highlight_main_highlighter_check_path`.

Regarding the first two, they are windows/cygwin specifics, I'm not
familiar with them; you'll have to investigate them yourself.

**Comment by guixxx** [comment]
>- disable path highlighting for «\\\\*» patterns on cygwin (that's two literal backslashes)

Thanks for your suggestion. I've fixed this issue by adding a simple check at the beginning of `_zsh_highlight_main_highlighter_check_path`:

```zsh
  if [[ ! -z $IS_CYGWIN ]]; then
    if [[ $arg == \\* || $arg == //* ]]; then
      REPLY=path
      return 0
    fi
  fi
```
I had to add this in my `.zshrc` as well:

```zsh
IS_CYGWIN=1
```

I've discovered that using `//` is actually much worse than `\\`. If I type:

 ```
$ ls //<any character>
```

Cygwin/mintty will not try to resolve the address for some reason, so it will get stuck **forever** unless I press Ctrl+C. Anyway, Since it's fixed for me, I'm closing this.

Cheers.

**Comment by danielshahaf** [comment]
> >- disable path highlighting for «\\\\*» patterns on cygwin (that's two literal backslashes)
> 
> Thanks for your suggestion. I've fixed this issue by adding a simple check at the beginning of `_zsh_highlight_main_highlighter_check_path`:
> 
> ```zsh
>   if [[ ! -z $IS_CYGWIN ]]; then
>     if [[ $arg == \\* || $arg == //* ]]; then

Note that this matches "anything that starts with a single backslash".

>       REPLY=path
>       return 0
>     fi
>   fi
> ```
> I had to add this in my `.zshrc` as well:
> 
> ```zsh
> IS_CYGWIN=1
> ```

You ought to be able to sniff the OS with `uname -s` or `uname -a` or
zsh's builtin parameter `$OSTYPE`.

> I've discovered that using `//` is actually much worse than `\\`. If I type:
> 
>  ```
> $ ls //<any character>
> ```
> 
> Cygwin/mintty will not try to resolve the address for some reason, so
> it will get stuck **forever** unless I press Ctrl+C. Anyway, Since
> it's fixed for me, I'm closing this.

Odd.  Thanks for sharing your solutions.  If others run into the same
problem, we can see about fixing this in z-sy-h upstream.

Cheers!

**Comment by guixxx** [comment]
>Note that this matches "anything that starts with a single backslash".

Oops! I've edited my post to add two more backslashes. Thanks.


>You ought to be able to sniff the OS with `uname -s` or `uname -a` or

Oh, that is what I was looking for. I thought about using `uname -o` but I didn't want to make z-sy-h run it each time I typed something, as it could have a negative impact on performance. `$OSTYPE` is just perfect, thank you! I've edited my previous post to include that as well.

>If others run into the same problem, we can see about fixing this in z-sy-h upstream.

Awesome. Again, thanks for your suggestions!

Cheers.

**Comment by danielshahaf** [comment]
> >You ought to be able to sniff the OS with `uname -s` or `uname -a` or
> 
> Oh, that is what I was looking for. I thought about using `uname -o`
> but I didn't want to make z-sy-h run it each time I typed something,

For future reference,   `${_my_cache_variable=$(uname -o)}` will
evaluate the command only once.  See zshexpn(1).  (But $OSTYPE is even
better.)

> >If others run into the same problem, we can see about fixing this in z-sy-h upstream.
> 
> Awesome. Again, thanks for your suggestions!

You're welcome.

**Comment by msva** [comment]
I have similar issue using directories with gazzilions of files. Isn't it any way to somehow add kinda timeout for path checker?

**Comment by quyenvsp** [comment]
This issue still happen on latest Windows Git bash Zsh z-sy-h. Here is workaround in .zshrc
Override two z-sy-h function to force skip if `$OSTYPE == 'msys'`

```
functions[_zsh_highlight_main_highlighter_check_path]='
  (){
    if [[ $OSTYPE == 'msys' ]]; then
	  if [[ $arg == \\\\* || $arg == //* ]]; then
	    REPLY=path
	    return 0
	  fi
    fi
    '$functions[_zsh_highlight_main_highlighter_check_path]';
    } "$@";
  local exit_code=$?
  return $exit_code'
functions[_zsh_highlight_main__type]='
  (){
    if [[ $OSTYPE == 'msys' ]]; then
	  if [[ $arg == \\\\* || $arg == //* ]]; then
	    REPLY=path
	    return 0
	  fi
    fi
    '$functions[_zsh_highlight_main__type]';
    } "$@";
  local exit_code=$?
  return $exit_code'
```
