### ISSUE TITLE
zsh_directory_name should not be called multiple times per command line

### ISSUE THREAD

**Issue by Julian** [zsh-users/zsh-syntax-highlighting#437]
If you define `zsh_directory_name`, zsh-syntax-highlighting will call it quite a few times.

E.g., with:

```
function zsh_directory_name() {
    echo CALLED
}
```

When typing out `~[foo`, hitting the closing `]` calls it twice, then hitting enter calls it another 2 times.

Or, not hitting enter, but typing additional characters on the line, calls it 2 times *per character*.

Presumably, zsh-syntax-highlighting should call it exactly once unless argv[0] changes (or someone ^L's)?

**Comment by danielshahaf** [comment]
Something should memoize the result of `zsh_directory_name` (h/t @phy1729).  Said something could be the function itself, or its caller in zsh core, or z-sy-h (in which case we'd flush the cache at `accept-line` and at `^L` aka `clear-screen`).

@Julian confirmed that adding (positive and negative) memoizing to his `zsh_directory_name` function fixed (most of?) the issue.

**Comment by danielshahaf** [comment]
Closing with @Julian's agreement via IRC, memoizing fixed the issue.  Thanks for the report!
