### ISSUE TITLE
scalar parameter ZSH_DEBUG_CMD created globally in function _zsh_highlight error

### ISSUE THREAD

**Issue by manajay** [zsh-users/zsh-syntax-highlighting#438]
when i source .zshrc 
the shell log like below:

```
_zsh_highlight:87: scalar parameter ZSH_DEBUG_CMD created globally in function _zsh_highlight
build_prompt:1: scalar parameter RETVAL created globally in function build_prompt
 manajay@manajay  ~ 
_zsh_highlight:90: scalar parameter ZSH_DEBUG_CMD created globally in function _zsh_highlight
build_prompt:1: scalar parameter RETVAL created globally in function build_prompt
 manajay@manajay  ~ 
_zsh_highlight:94: scalar parameter ZSH_DEBUG_CMD created globally in function _zsh_highlight
build_prompt:1: scalar parameter RETVAL created globally in function build_prompt
 manajay@manajay  ~ 
_zsh_highlight:95: scalar parameter ZSH_DEBUG_CMD created globally in function _zsh_highlight
build_prompt:1: scalar parameter RETVAL created globally in function build_prompt
```

i don't know why

**Comment by danielshahaf** [comment]
Lyn Jay wrote on Wed, 12 Jul 2017 09:39 -0700:
> _zsh_highlight:87: scalar parameter ZSH_DEBUG_CMD created globally in function _zsh_highlight

I can reproduce this when I set ZSH_DEBUG_CMD=: and install a DEBUG trap and z-sy-h is enabled (which enables warncreateglobal for its scope).  Can someone come up with a minimal reproducer for this?

> build_prompt:1: scalar parameter RETVAL created globally in function build_prompt

This one is something in your configuration.  Whoever uses $RETVAL needs to declare it with `typeset`.

**Comment by phy1729** [comment]
Minimal reproducer in zsh -f
```sh
f() { setopt local_options warn_create_global; :; }; trap : DEBUG; f
```
Seems like an upstream issue. You can work around this by adding
```sh
local ZSH_DEBUG_CMD
```
as the first line in `_zsh_highlight`.

**Comment by danielshahaf** [comment]
I confirm that [workers/42043](http://www.zsh.org/cgi-bin/mla/redirect?WORKERNUMBER=42043) fixes both the minimal reproducer and the original bug.

**Comment by danielshahaf** [comment]
... but it hasn't been committed upstream yet.  Once that happens I think we can close this issue.

**Comment by phy1729** [comment]
[workers/42043](http://www.zsh.org/cgi-bin/mla/redirect?WORKERNUMBER=42043) has been committed to master in zsh-users/zsh@b476d89fa279469fd24926db7f2b117a318ff38b.
