### ISSUE TITLE
Fedora package?

### ISSUE THREAD

**Issue by franklinyu** [zsh-users/zsh-syntax-highlighting#439]
The [link in INSTALL.md](https://apps.fedoraproject.org/packages/s/zsh-syntax-highlighting) gives no results.

**Comment by danielshahaf** [comment]
@michaelkuhn What's the correct link?

xref #384

**Comment by michaelkuhn** [comment]
This is the correct link. There is a bug that causes multiple (new) packages to not show up in the package search (see https://github.com/fedora-infra/fedora-packages/issues/254). :-(

**Comment by danielshahaf** [comment]
@michaelkuhn Thanks.  What shall we do with INSTALL.md until that downstream issue is fixed?  Remove the link?  Add another link (to, say, https://bodhi.fedoraproject.org/updates/?packages=zsh-syntax-highlighting)?  I'd rather not leave a broken link in INSTALL.md indefinitely.

**Comment by michaelkuhn** [comment]
I would use PkgDB (https://admin.fedoraproject.org/pkgdb/package/rpms/zsh-syntax-highlighting/) but apparently this is being retired next week. I guess the Bodhi link is the next best thing.

**Comment by danielshahaf** [comment]
Fixed.  Thanks for the quick response, @michaelkuhn, and for the report, @franklinyu.
