### ISSUE TITLE
full width emojis render improperly

### ISSUE THREAD

**Issue by llwu** [zsh-users/zsh-syntax-highlighting#442]
Hard to describe but it looks like this:
<img width="484" alt="screen shot 2017-09-10 at 2 33 24 pm" src="https://user-images.githubusercontent.com/5601392/30253193-0b374d8e-9635-11e7-9b1b-fa77c33a9eac.png">

To reproduce, download an iTerm 2 new enough to have "Use Unicode Version 9 Widths" and enable it (currently stable doesn't have it but beta does). This will cause emojis to render at their proper width rather than overlapping, but also introduces this artifact.

Out of curiosity, I tested this with `fish` and it's syntax highlighting seems to work fine although their rprompt spacing get's clobbered (which `zsh` seems to handle fine)
<img width="490" alt="screen shot 2017-09-10 at 2 38 40 pm" src="https://user-images.githubusercontent.com/5601392/30253242-f5a89c60-9635-11e7-8556-4f81dec33d66.png">

I'm willing to help out with a patch, though I'm hoping someone has a hunch of what causes this.

**Comment by danielshahaf** [comment]
This seems like a zsh issue, not a zsh-syntax-highlighting issue.  You should be able to reproduce some character width miscounting without z-sy-h.

Try compiling zsh with --enable-unicode9 to configure.

Could you please explain what needs to be fixed _in z-sy-h_ here?  If there's a zsh bug it needs to be taken to the zsh-users@ mailing list.

**Comment by llwu** [comment]
That `configure` option fixed it, thanks!
