### ISSUE TITLE
Highlighter for Executable

### ISSUE THREAD

**Issue by Hacksaurus** [zsh-users/zsh-syntax-highlighting#445]
Hello!
I was just wondering on how to change the highlight if there is an executable, or if you could implement an function so people can easily do so.
Because whenever I have an executable it simply highlights as a directory as shown:
![screenshot_2017-09-16_13-22-06](https://user-images.githubusercontent.com/24832107/30515729-0ff9aeaa-9ae2-11e7-9084-e03ca1805c78.png)

I actually noticed this has changed after an update, so I was wondering if I could just change it to a more appropriate color.

Thank you!

**Comment by danielshahaf** [comment]
Edit `_zsh_highlight_main_highlighter_check_path`; that's where the `path` style is set.

See also the `path_prefix` style.

**Comment by Hacksaurus** [comment]
Not sure what you mean @danielshahaf ....
You could you explain further? Thank you!

**Comment by danielshahaf** [comment]
Could you explain what you're trying to do?

I thought you were asking how to cause `ls /etc/motd` and `ls /usr/bin/env` to highlight their file argument differently.  Maybe you're asking how to cause `% /etc` and `% ./a.out` to highlight their command word differently?  Or something else?

Please clarify, if possible, by contrasting good and wrong outputs.  Thanks.

**Comment by Hacksaurus** [comment]
What I wanted to do is have `./<SOMETHING>` to highlight something different. `ls /<Whatever>` is fine as it is. I was thinking of using the pattern highlighter shown here: https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/pattern.md Bu doesn't seem to work (even the example), if I could just use that I think I will be fine

**Comment by phy1729** [comment]
In the example picture in your first post, which word would you like to color differently? `g++`, `Executables/1`, or `./Executables/1`? If `Executables/1`,  adding
```
[[ -f $expanded_path && -x $expanded_path ]] && { REPLY=executable; return 0; }
```
under
```
[[ -z $expanded_path ]] && return 1
```
in `_zsh_highlight_main_highlighter_check_path` in `highlighters/main/main-highlighter.zsh` would work, but only after the file exists.

**Comment by danielshahaf** [comment]
@Hacksaurus ping?

**Comment by Hacksaurus** [comment]
I kinda just want the entire thing to be colored differently, so`./Executables/1` Would be the text that I would want to change...

**Comment by danielshahaf** [comment]
Are you talking about directory names in command position with the AUTO_CD option set?

**Comment by Hacksaurus** [comment]
I don't really know how to explain this...
So whenever I type in this: `./` The text of `./` and anything else typed at the end of that should change...

Does that help explain what I want to change?

**Comment by danielshahaf** [comment]
Do you want './foo' and 'g++' colored differently to each other?

**Comment by Hacksaurus** [comment]
Yes any time that I use `./` to execute a file change the color, but if I use a normal program then just use whatever color I normally use...

**Comment by Hacksaurus** [comment]
Alright, the thing is that I got used to having that blue color, so I think I'm ok for now!

Thank your for your patience.
