### ISSUE TITLE
Work with oh-my-zsh, paste slow

### ISSUE THREAD

**Issue by zyf0330** [zsh-users/zsh-syntax-highlighting#446]
reproduce steps:
1. zsh -f
2. source $ZSH/oh-my-zsh.sh
3. source .oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
4. paste 
```
123333333333333333333
432222222222222222
43666666666666666666
658777777777777777
3455555555555555
5466666666666666666666
123333333333333333333
432222222222222222
43666666666666666666
658777777777777777
3455555555555555
5466666666666666666666
```
 and the whole textarea appears after a few seconds

Use zsh-syntax-highlighting singly, this problem won't appear.

**Comment by danielshahaf** [comment]
追随 wrote on Thu, 28 Sep 2017 20:56 -0700:
> reproduce steps:
> 1. zsh -f
> 2. source $ZSH/oh-my-zsh.sh
> 3. source .oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
> 4. paste 
> ```
> 123333333333333333333
> 432222222222222222
> 43666666666666666666
> 658777777777777777
> 3455555555555555
> 5466666666666666666666
> 123333333333333333333
> 432222222222222222
> 43666666666666666666
> 658777777777777777
> 3455555555555555
> 5466666666666666666666
> ```
>  and the whole textarea appears after a few seconds
> 
> Use zsh-syntax-highlighting singly, this problem won't appear.

We are unable to bisect problems caused by oh-my-zsh, even when they do start from `zsh -f`.  Please follow up with oh-my-zsh.

**Comment by zyf0330** [comment]
Ok.

**Comment by zyf0330** [comment]
After upgrading to zsh v5.4.2, this problem doesn't exist anymore.

**Comment by danielshahaf** [comment]
追随 wrote on Fri, 29 Sep 2017 19:58 -0700:
> After upgrading to zsh v5.4.2, this problem doesn't exist anymore.

Thanks for letting us know!
