### ISSUE TITLE
zsh_highlight_highlighter_main_paint:130: error in flags

### ISSUE THREAD

**Issue by eeriee** [zsh-users/zsh-syntax-highlighting#448]
My OS is RHEL 5.3 and zsh version is zsh 5.0.2 (x86_64-unknown-linux-gnu).
When I run 
```
echo "source ${(q-)PWD}/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> 
${ZDOTDIR:-$HOME}/.zshrc
```
It shows
```
zsh: error in flags
```
If I add the following code to the end of .zshrc file manually
```
source (MY_HOME_DIR)/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
```
The error occurs after every command.
```
zsh_highlight_highlighter_main_paint:130: error in flags
```
Can anyone tell me how to solve this problem?

**Comment by danielshahaf** [comment]
5.0.2 works: see https://travis-ci.org/zsh-users/zsh-syntax-highlighting

If I had to guess, I'd say there's a syntax error in your zshrc file.

**Comment by eeriee** [comment]
The problem still occurs if I use Oh-my-zsh and add **zsh-syntax-highlighting** as the plugin.

**Comment by phy1729** [comment]
Related issue robbyrussell/oh-my-zsh#4664.

I haven't been successful at reproducing the issue so far. @eeriee @sagioto @chenxinle (or anyone), could one of you create a minimal reproducer (starting with `zsh -f`)?

**Comment by danielshahaf** [comment]
Anyone who reports this, please include the output of `echo $ZSH_HIGHLIGHT_VERSION $ZSH_HIGHLIGHT_REVISION` and the exact line number in the error message.

**Comment by eeriee** [comment]
@danielshahaf i cannot execute any commands with the ```zsh-syntax-highlighting``` configuration.

```
❯ echo $ZSH_HIGHLIGHT_VERSION
_zsh_highlight_highlighter_main_paint:130: error in flags
```

When remove the ```zsh-syntax-highlighting``` configuration, ```echo $ZSH_HIGHLIGHT_VERSION ``` shows nothing.

@phy1729 sry I don't know how to create a minimal reproducer for this issue.

but with ```zsh -f```, i got
```
❯ zsh -f
$(print_icon MULTILINE_FIRST_PROMPT_PREFIX)$(build_left_prompt)
$(print_icon MULTILINE_LAST_PROMPT_PREFIX)                                                                                                                      $RPROMPT_PREFIX$(build_right_prompt)$reset_color$RPR
```

**Comment by danielshahaf** [comment]
`zsh -f` should prompt you `hostname%`.

**Comment by danielshahaf** [comment]
Closing as unreproducible/inactionable.  If anyone still sees this please reopen and report version numbers and line numbers.
