### ISSUE TITLE
Error when UNSET is unset

### ISSUE THREAD

**Issue by srguglielmo** [zsh-users/zsh-syntax-highlighting#449]
Hi,

When `unsetopt UNSET` in `~/.zshrc`, I receive an error when sourcing `zsh-syntax-highlighting.zsh`:

> _zsh_highlight_bind_widgets:27: widgets[$cur_widget]: parameter not set

`setopt UNSET` (or removing the `unsetopt` command) solves the issue.

Thanks

**Comment by danielshahaf** [comment]
Fixed, thanks!
