### ISSUE TITLE
freeze on path highlighting when directory have many files

### ISSUE THREAD

**Issue by msva** [zsh-users/zsh-syntax-highlighting#456]
I've found, that zsh-syntax-highlight freezes zsh when I trying to enter some path, when last entered (before the freeze) directory contains many files (i.e. even `ls` thinks for some time before show the files).

Also, it seems, there is no way to tell the highlighter to don't try to not perform any operations on that dir (I guess, it is somehow related to the check if last path's part is existing file or not) and just highligt it in some predefined way...

**Comment by danielshahaf** [comment]
I'm guessing it's just being slow, not actually freezes, and this is a duplicate of #379.

**Comment by msva** [comment]
Yeah, thanks, it is. I was just unable to find it by any of keywords I tried :)

**Comment by danielshahaf** [comment]
Cheers.  Any chance you'd like to help with the implementation?  (We're also on #zsh-syntax-highlighting on freenode)

**Comment by phy1729** [comment]
@msva If you get a chance, feedback on #496 would be appreciated.

**Comment by msva** [comment]
Well, it looks good for me :) But I guess, it's only @nicoulaj who can merge it. Isn't he?

**Comment by msva** [comment]
by the way, I guess, if you sure that new features (like `${:|}` and `:P`) have better performance, you can add $ZSH_VERSION check (but it's just my humble opinion and can be unacceptable here. I'd anyway wait for @nicoulaj comments on your PR...

**Comment by danielshahaf** [comment]
@msva: @phy1729 and I have push access as well :-)
