### ISSUE TITLE
What's the difference between installing as a package through zsh or in my ~/.zshrc ??

### ISSUE THREAD

**Issue by norman123123** [zsh-users/zsh-syntax-highlighting#459]
What's the difference between installing as a package through the shell or in my ~/.zshrc  cloning the repo??

**Comment by phy1729** [comment]
Just the location of the zsh-syntax-highlighting files. If installed as a package, the files will live in `/usr/local/share/zsh-syntax-highlighting/` (by default, the packager may have chosen another location). If you clone the repo, the files live where ever you clone them. Either way you need to modify your `.zshrc`.
