### ISSUE TITLE
Command required after assignment

### ISSUE THREAD

**Issue by phy1729** [zsh-users/zsh-syntax-highlighting#461]
zsh errors out with a parse error for
`FOO=bar { :; }`
`FOO=bar ( :; )`
`FOO=bar (( foo ))`
`FOO=bar [[ foo ]]`
`FOO=bar ! :`
We should highlight the word after the assignment as an unknown-token (or perhaps other style) as long as these are parse errors.

**Comment by danielshahaf** [comment]
What's the rule?

**Comment by danielshahaf** [comment]
`[[` is a reserved word. What about builtins?

**Comment by danielshahaf** [comment]
@phy1729 reports builtins don't error

**Comment by danielshahaf** [comment]
Asked upstream about the syntax [users/23000](http://www.zsh.org/cgi-bin/mla/redirect?USERNUMBER=23000)

**Comment by danielshahaf** [comment]
Could you have a look at https://github.com/danielshahaf/zsh-syntax-highlighting/commit/d2ed7f4f5707ed0e3cb6a9e3c86bd99ef5bc301b?

**Comment by phy1729** [comment]
Could use a test, but the code looks good.

**Comment by danielshahaf** [comment]
> Asked upstream about the syntax [users/23000](http://www.zsh.org/cgi-bin/mla/redirect?USERNUMBER=23000)

Upstream's answer (by Bart):

> Literally, the rule is "parameter assignments may precede only a simple command."  (In fact the assignment syntax is part of the definition of simple command syntax.)
> 
> Of the set of $reswords from zsh/parameter, "nocorrect" and all of the aliases for "typeset" may begin a simple command.  The rest may not.
