### ISSUE TITLE
Document that zsh/parameter is now required

### ISSUE THREAD

**Issue by danielshahaf** [zsh-users/zsh-syntax-highlighting#462]
See #457.  If that PR isn't merged then the release notes should document the new requirement; else this ticket may be closed with no further action.

**Comment by danielshahaf** [comment]
The dependency was added in https://github.com/zsh-users/zsh-syntax-highlighting/commit/2a506145790b144b561326341a098fbc0bc780da & https://github.com/zsh-users/zsh-syntax-highlighting/commit/7177ba005fde5c4d12440b8b3ae33bbcf4e9200c

**Comment by phy1729** [comment]
#457 has been merged, so zsh/parameter is no longer a requirement.
