### ISSUE TITLE
How to change the highlight color???

### ISSUE THREAD

**Issue by st4rlight** [zsh-users/zsh-syntax-highlighting#464]
The default color for right is green, and the error is red. I just want to change the color for right from green to blue ( or rather, RGB#92c9ff ), how can I do this?

**Comment by phy1729** [comment]
The [docs for how to tweak the styles](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters.md#how-to-tweak-highlighters) points to [the zshzle man page](http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#Character-Highlighting) for how to specify colors and [the main highlighter docs](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/main.md) for which styles are supported.

The styles that are green by default are `suffix-alias`, `precommand`, and `arg0`, so you might want to add the following into your .zshrc
```
ZSH_HIGHLIGHT_STYLES[suffix-alias]=fg=blue,underline
ZSH_HIGHLIGHT_STYLES[precommand]=fg=blue,underline
ZSH_HIGHLIGHT_STYLES[arg0]=fg=blue
```

**Comment by st4rlight** [comment]
It works, thanks a lot.

**Comment by PianoSea** [comment]
It doesn't work on my mac with zsh version 5.7.1

ZSH_HIGHLIGHT_STYLES[alias]=fg=blue,bold
ZSH_HIGHLIGHT_STYLES[builtin]=fg=blue,bold
ZSH_HIGHLIGHT_STYLES[function]=fg=blue,bold
ZSH_HIGHLIGHT_STYLES[command]=fg=white,bold

I changed all these four color, but it doesnt work. Could you please give me any hints ?
 I added the 
typeset -A ZSH_HIGHLIGHT_STYLES   before I set these value.

**Comment by danielshahaf** [comment]
Your code seems correct.

**Comment by PianoSea** [comment]
@danielshahaf but i couldn't change the color of the font still. I don't know why. 
Do you know which field means the color of the built-in(shell built-in) command as well as the outer command like (ls)

**Comment by danielshahaf** [comment]
I had pasted your code at my shell prompt and it had the desired effect.

If you type `ls` now, what colour is it displayed in?

**Comment by PianoSea** [comment]
![image](https://user-images.githubusercontent.com/6367752/59411484-f04f3880-8ded-11e9-8e3e-7ab87098c678.png)
This is the picture shown. I followed some script setting from a community. However, the color is not blue as I configured. The attachment is my .zshrc. You could change the file zshrc.txt back to .zshrc, because I couldn't upload the .zshrc file directly here.
[zshrc.txt](https://github.com/zsh-users/zsh-syntax-highlighting/files/3284626/zshrc.txt)
 file

**Comment by PianoSea** [comment]
https://github.com/skywind3000/vim/blob/master/etc/zshrc.zsh  
This is the place I copied the configuration file.

**Comment by danielshahaf** [comment]
You've dialed the wrong number: you're using https://github.com/zdharma/fast-syntax-highlighting/, not zsh-syntax-highlighting. Please address your questions to the maintainer of fast-syntax-highlighting. Good luck!

**Comment by PianoSea** [comment]
Got it with many thx! I am a blind person~ lol

**Comment by danielshahaf** [comment]
Well, I don't see any support for Braille displays in [xterm's reference](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html), but if you're aware of something, just open a new issue and we'll see what we can do. ;-)

**Comment by PianoSea** [comment]
Sorry About that. When I mean blind, I mean I didn't find the slight distinction for the fast and zsh . I didn't mean any irrespective for any braille people.

**Comment by danielshahaf** [comment]
No worries.  I didn't read it that way :)

**Comment by trashidi98** [comment]
@phy1729 Hey, I liked your solution, but just wondering how you figure out which fields were automatically green?

**Comment by phy1729** [comment]
The default styles are defined at the top of each highlighter, so for main https://github.com/zsh-users/zsh-syntax-highlighting/blob/5eb494852ebb99cf5c2c2bffee6b74e6f1bf38d0/highlighters/main/main-highlighter.zsh#L31-L65 .

**Comment by GabpmcpML** [comment]
I have a ligature recovered '->' but when I write '=>' ligature doesn't work by each character is a different color. What position of ZSH_HIGHLIGHT_STYLES array represents the equals symbol?

**Comment by danielshahaf** [comment]
When it's white with underline, `path` and `path_prefix`, due to the `EQUALS` zsh option. (Those are the only styles with `underline`, actually.)

I don't understand what you're trying to do. There's no such thing as a ligature (recovered or otherwise) in zsh-syntax-highlighting.

If you have follow-up questions, please start a new thread so the people subscribed to this old issue aren't Cc'd. Cheers.

**Comment by hannarosenfeld** [comment]
Hi, which colors are actually available? Changing the [arg0] color to magenta works, but for example olive or pink don't.

**Comment by phy1729** [comment]
You're looking for the [zshzle man page](https://zsh.sourceforge.io/Doc/Release/Zsh-Line-Editor.html#Character-Highlighting) in particular the text under `fg=colour`
