### ISSUE TITLE
Tmux + italic escaping

### ISSUE THREAD

**Issue by art32** [zsh-users/zsh-syntax-highlighting#465]
I tried use Tmux + italic escaping + zsh-syntax-highlighting on Mac and Centos.

On Mac it's work:
![screen shot 2017-12-19 at 23 41 44](https://user-images.githubusercontent.com/16598661/34177871-41730b56-e516-11e7-969b-3b3372c43fc3.png)

On Centos it doesn't work:
![screen shot 2017-12-19 at 23 42 06](https://user-images.githubusercontent.com/16598661/34177892-4ea8d8fa-e516-11e7-897e-e297238d4199.png)

Tmux, Zsh, Oh-my-zsh, theme and configs identical.

Before I tried use ```fast-syntax-highlighting``` but it doesn't work on both systems.

**Comment by phy1729** [comment]
Do you still see problems if you use a simpler prompt (one line, no colors just built-ins like say `PROMPT='%m%# '`? Locally the printf in tmux results in hello in reverse video (which is likely just my lack of configuring tmux). Could you come up with a minimal reproducer starting with `zsh -f` and including any tmux config needed to reproduce? zsh and zsh-syntax-highlighting versions would also be appreciated (`print $ZSH_VERSION $ZSH_HIGHLIGHT_VERSION`).

**Comment by art32** [comment]
![screen shot 2017-12-20 at 00 51 08](https://user-images.githubusercontent.com/16598661/34180478-e709e824-e51f-11e7-85ed-17207e9a503f.png)

![screen shot 2017-12-20 at 01 00 42](https://user-images.githubusercontent.com/16598661/34181127-1e68c388-e522-11e7-8ac9-70f4d8e15d1e.png)

the same on both systems

~/.tmux.conf
```
set -g default-terminal "tmux-256color" # colors!
set -as terminal-overrides ',xterm*:sitm=\E[3m:Tc'
```

~/.tmux.terminfo
```
tmux|tmux terminal multiplexer,
    ritm=\E[23m, rmso=\E[27m, sitm=\E[3m, smso=\E[7m, Ms@,
    use=xterm,
    use=screen,

tmux-256color|tmux with 256 colors,
    use=xterm-256color,
    use=tmux,
```

```tic -x ~/.tmux.terminfo```

```
zsh -f
tmux
test
```

Centos 7
![screen shot 2017-12-20 at 01 06 32](https://user-images.githubusercontent.com/16598661/34181108-0f8dcc5a-e522-11e7-8b95-36593d280589.png)

Mac OS X
![screen shot 2017-12-20 at 01 09 48](https://user-images.githubusercontent.com/16598661/34181233-85065be6-e522-11e7-9bc9-259f6d717233.png)

**Comment by phy1729** [comment]
Can you reproduce it with
```
set -g default-command "zsh -f"
```
in .tmux.conf?
I've got a C7 VM, but am not yet able to reproduce the issue.

**Comment by art32** [comment]
If I set 
```set -g default-command "zsh -f"```
that syntax-highlighting doesn't work.

**Comment by danielshahaf** [comment]
Does it work in `zsh -f` outside tmux?

What commands are you running in `zsh -f` before you type `test`?  We really do need a complete example.

**Comment by art32** [comment]
Outside tmux ```zsh -f```
![screen shot 2017-12-20 at 02 56 28](https://user-images.githubusercontent.com/16598661/34184552-6c45a4e0-e531-11e7-8bd1-cdf3b9a303da.png)
syntax doesn't work, but ```backspace``` work correctly.

Inside tmux ```zsh -f```
![screen shot 2017-12-20 at 02 58 47](https://user-images.githubusercontent.com/16598661/34184608-b7d30362-e531-11e7-8694-49f7e5677b14.png)
syntax doesn't work and ```backspace``` doesn't work ... (on screen I press 4 * ```BS```)

**Comment by phy1729** [comment]
`zsh -f` runs zsh without most dotfiles, so you'll have to source z-sy-h manually. You may find it easier to construct a minimal reproducer by removing parts of your config until you can't remove anymore without the problem going away. Then verify that the config left indeed reproduces the issue in `zsh -f`.

**Comment by danielshahaf** [comment]
The "backspace not working" bit isn't a z-sy-h issue.. but it might indicate that your $TERM / terminfo settings are wrong, which could easily affect syntax highlighting.  So you might want to get that fixed first.

**Comment by danielshahaf** [comment]
Re minimal config, what you'd do is basically

```sh
$ zsh -f
% source .../zsh-syntax-highlighting.zsh
```

and if you assign to any `ZSH_HIGHLIGHT_*` variables in your dotfiles, you'd run those assignments interactively.

In your case, a minimal reproducer should also be using the vendor terminfo entries..  unless you've verified that it works with them but not with your custom ones (if that's the case you haven't said that).

**Comment by art32** [comment]
@phy1729 @danielshahaf 
I fix my terminfo (delete anaconda2 ...) and this is working fine.
fast-syntax-highlighting also works.

Thanks for the help!
