### ISSUE TITLE
Confusing character class

### ISSUE THREAD

**Issue by danielshahaf** [zsh-users/zsh-syntax-highlighting#472]
https://github.com/zsh-users/zsh-syntax-highlighting/blob/bdbe214453c40908006f1bc53bf0562e93fe957d/highlighters/main/main-highlighter.zsh#L821

https://github.com/zsh-users/zsh-syntax-highlighting/blob/bdbe214453c40908006f1bc53bf0562e93fe957d/highlighters/main/main-highlighter.zsh#L824

Shouldn't the minus be at the end?  It seems zsh only parses _c1_-_c2_ as a range if `c1 < c2` in ASCII, let's not rely on that.  At least it's confusing.

Haven't checked whether there are other instances.

**Comment by phy1729** [comment]
There are no other instances; however, the test in `_zsh_highlight_main_highlighter_highlight_double_quote` does not recognize `$!` (which can theoretically occur with `: !" "$!"` or `: "$!}"` or even `: "$\!"` (which appears to only work with `!`)).
