### ISSUE TITLE
back-double-quoted-argument not working

### ISSUE THREAD

**Issue by glacambre** [zsh-users/zsh-syntax-highlighting#480]
When using `zsh-syntax-highlighting rev c969a1f` on `zsh 5.3.1 (x86_64-pc-linux-gnu)`, backslashed symbols won't be colored differently from the rest of the string for double-quoted strings. Here's how I reproduce this bug:
```zsh
zsh -f
source zsh-syntax-highlighting.zsh
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]="fg=0"
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg=1'
echo "hello \x world"
```
The surprising thing is that highlighting backslashed symbols in `$''` strings works.

Thank you for creating and maintaining zsh-syntax-highlighting by the way, it's very nice and works quite well even with this minor issue :)

**Comment by phy1729** [comment]
Thanks for the clear bug report with minimal reproducer!

I think the present behavior is correct. `zshmisc(1)` states:
```Inside double quotes (""), parameter and command substitution occur, and `\' quotes the characters `\', ``', `"', and `$'.```
(This is missing $histchars[1] which I'll report upstream to fix the docs).

If we test with `print -r` rather than with `echo` (which will mangle its arguments`, you'll see 
```
% print -r "hello \\ \` \" \$ \! \a \b \c \x world"
hello \ ` " $ ! \a \b \c \x world
```
zsh does not change `\a \b \c \x` which is why they are not highlighted as back-double-quoted-argument. In the example given `echo` is the reason the `\x` does not appear in the output.

**Comment by glacambre** [comment]
I see, the current behavior indeed makes sense with your explanation. However, the [documentation](https://github.com/zsh-users/zsh-syntax-highlighting/blob/d17417ec1bd37ace6222175810878c97a47a2b91/docs/highlighters/main.md) states the following:

>back-double-quoted-argument - back double quoted arguments (\x inside "")

This is the reason why I thought `\x` would get a different color. Did I misinterpret the documentation or is the documentation wrong?

**Comment by danielshahaf** [comment]
The `x` is meant as a metasyntactic variable, assuming one of the values `` \`"$! ``, not as a literal. That said, `\x` is an escape sequence inside `""` in many languages (including C), so I see how this might be confusing.

Also, the part of the line between the dash and the parenthetical needs to be revised.

**Comment by danielshahaf** [comment]
How about this?

```diff
diff --git a/docs/highlighters/main.md b/docs/highlighters/main.md
index cec79fa..3459e90 100644
--- a/docs/highlighters/main.md
+++ b/docs/highlighters/main.md
@@ -32,21 +32,21 @@ This highlighter defines the following styles:
 * `path_prefix_pathseparator` - path separators in prefixes of existing filenames (`/`); if unset, `path_prefix` is used (default)
 * `globbing` - globbing expressions (`*.txt`)
 * `history-expansion` - history expansion expressions (`!foo` and `^foo^bar`)
-* `single-hyphen-option` - single hyphen options (`-o`)
-* `double-hyphen-option` - double hyphen options (`--option`)
-* `back-quoted-argument` - backquoted expressions (`` `foo` ``)
-* `back-quoted-argument-unclosed` - unclosed backquoted expressions (`` `foo ``)
-* `single-quoted-argument` - single quoted arguments (`` 'foo' ``)
-* `single-quoted-argument-unclosed` - unclosed single quoted arguments (`` 'foo ``)
-* `double-quoted-argument` - double quoted arguments (`` "foo" ``)
-* `double-quoted-argument-unclosed` - unclosed double quoted arguments (`` "foo ``)
-* `dollar-quoted-argument` - dollar quoted arguments (`` $'foo' ``)
-* `dollar-quoted-argument-unclosed` - unclosed dollar quoted arguments (`` $'foo ``)
+* `single-hyphen-option` - single-hyphen options (`-o`)
+* `double-hyphen-option` - double-hyphen options (`--option`)
+* `back-quoted-argument` - backtick command substitution (`` `foo` ``)
+* `back-quoted-argument-unclosed` - unclosed backtick command substitution (`` `foo ``)
+* `single-quoted-argument` - single-quoted arguments (`` 'foo' ``)
+* `single-quoted-argument-unclosed` - unclosed single-quoted arguments (`` 'foo ``)
+* `double-quoted-argument` - double-quoted arguments (`` "foo" ``)
+* `double-quoted-argument-unclosed` - unclosed double-quoted arguments (`` "foo ``)
+* `dollar-quoted-argument` - dollar-quoted arguments (`` $'foo' ``)
+* `dollar-quoted-argument-unclosed` - unclosed dollar-quoted arguments (`` $'foo ``)
 * `rc-quote` - two single quotes inside single quotes when the `RC_QUOTES` option is set (`` 'foo''bar' ``)
 * `dollar-double-quoted-argument` - parameter expansion inside double quotes (`$foo` inside `""`)
-* `back-double-quoted-argument` -  back double quoted arguments (`\x` inside `""`)
-* `back-dollar-quoted-argument` -  back dollar quoted arguments (`\x` inside `$''`)
-* `assign` - parameter assignments
+* `back-double-quoted-argument` -  backslash escape sequences inside double-quoted arguments (`\"` in `"foo\"bar"`)
+* `back-dollar-quoted-argument` -  backslash escape sequences inside dollar-quoted arguments (`\x` in `$'\x48'`)
+* `assign` - parameter assignments (`x=foo` and `x=( )`)
 * `redirection` - redirection operators (`<`, `>`, etc)
 * `comment` - comments, when `setopt INTERACTIVE_COMMENTS` is in effect (`echo # foo`)
 * `arg0` - a command word other than one of those enumrated above (other than a command, precommand, alias, function, or shell builtin command).
```

**Comment by glacambre** [comment]
Oh, I get now. Yes, the documentation seems a bit clearer to me when worded this way, sorry I got confused and thank you for your patient explanations.

**Comment by danielshahaf** [comment]
No worries, and I just committed the above patch in 4724837df059950851f7f5049b556f36677cdc78 (& its parent), so thanks for making that happen. :)
