### ISSUE TITLE
$(<foo) is not globbing

### ISSUE THREAD

**Issue by danielshahaf** [zsh-users/zsh-syntax-highlighting#483]
`: $(<foo)` highlights the argument as a globbing. It isn't; it's a subcommand substitution that happens to contain a redirection.

Bisected to 987b743646c3e71a160de0ac2177bfe914bde39a.

**Comment by danielshahaf** [comment]
What about `echo foo$(<bar)` ?

**Comment by danielshahaf** [comment]
Maybe we should look for the rest of the syntax, i.e., the digits-minus-digits-greater-than that should follow `<` when it's a glob?

**Comment by phy1729** [comment]
I think the correct fix would be to recurse into `$( )` so that `: $(< foo)` is handled identically to `< foo`

**Comment by phy1729** [comment]
> Maybe we should look for the rest of the syntax, i.e., the digits-minus-digits-greater-than that should follow < when it's a glob?

I think this would work in the interm.
