### ISSUE TITLE
Request for help learning zsh wizardry

### ISSUE THREAD

**Issue by unphased** [zsh-users/zsh-syntax-highlighting#490]
I would like to evaluate how possible it is to implement capability in zsh (or bash!) that I describe in this question I posted: 

https://unix.stackexchange.com/questions/417607/zsh-line-editor-can-i-navigate-and-edit-by-argument?noredirect=1#comment749845_417607

So far it seems that this project, zsh-syntax-highlighting, is one of the projects that appears to employ sophisticated machinery around the shell line editor that indicates to me the possibility of doing what I want. 

To give it another go of describing what I want. I want key binds that let me "slide" the shell argument currently under my cursor to the left or right, so that I can rearrange them effortlessly. 

To do this it seems that some "full" parsing of the command line is needed. 

As a first pass you could imagine implementing this capability by adjusting the `$WORDCHARS`, killing the word around the cursor, navigating back (or forward) one word, and pasting it. 

That should work, but it won't work when there are escaped spaces or strings with spaces in an argument, for example.

Eventually we could also think about what to do when a command escape (shell backticks, subshells) is present, but I'll not worry about that yet. 

when I look at `zsh-syntax-highlighting.zsh`, I can't make heads or tails of it. What is the magic sauce that determines which character regions are to be painted a given color?

**Comment by danielshahaf** [comment]
You're looking for the ${(z)} parameter expansion flag: https://github.com/zsh-users/zsh-syntax-highlighting/blob/a65a07fae4e916f49b84afd8f6d9b2ef258b52fb/highlighters/main/main-highlighter.zsh#L325-L329

Implementing the widget you describe is out of scope for zsh-syntax-highlighting. I suggest that you follow up on the zsh-users@ mailing list (or on stackexchange if that floats your boat) — if Stéphane's answer doesn't address your question, that is.

@psprint may have implemented something like this too.
