### ISSUE TITLE
Highlighter prints things when regex highlighting is triggered for the 1st time after login:

### ISSUE THREAD

**Issue by Leedehai** [zsh-users/zsh-syntax-highlighting#497]
This is my addition to `zsh-syntax-highlighting/highlighters/regexp/regexp-highlighter.zsh` imediately after the line `typeset -gA ZSH_HIGHLIGHT_REGEXP`:
```
# Highlight 'ls' and 'cd'
ZSH_HIGHLIGHT_REGEXP+=('(^| )(ls|cd)($| )' 'fg=green')
```

Everytime the regex is triggered for the 1st time after login, the terminal prints things. The 2nd time and beyond, it works fine
```
Last login: Mon Jan 22 19:28:18 on ttys000
▸ ~ ls
_zsh_highlight_regexp_highlighter_loop:6: array parameter match created globally in function _zsh_highlight_regexp_highlighter_loop
_zsh_highlight_regexp_highlighter_loop:6: array parameter mbegin created globally in function _zsh_highlight_regexp_highlighter_loop
_zsh_highlight_regexp_highlighter_loop:6: array parameter mend created globally in function _zsh_highlight_regexp_highlighter_loop
▸ ~ ls
Applications   Downloads      Movies         Public         pymel.log      vscode
Desktop        GoogleDrive    Music          VirtualBox VMs safe-rm.sh     vscode.zip
Documents      Library        Pictures       anaconda2      settings.json  xgen
▸ ~
```
This behavior repeats if your logout and login again.

**Comment by phy1729** [comment]
Thanks for the bug report with reproducer! Does the latest commit to master fix the issue?

**Comment by Leedehai** [comment]
Whoops, sorry I must have missed the message at that time! It was definitely not my intention to be rude by not responding. I stumbled across this today when I was googling and was surprised this was me who filed this bug..

**Comment by danielshahaf** [comment]
Thanks for letting us know it works for you now! :-)
