### ISSUE TITLE
Add support for REPLs

### ISSUE THREAD

**Issue by revolter** [zsh-users/zsh-syntax-highlighting#505]
Is there a chance to add support for REPLs like `python` or `irb`? Or is this outside the scope of this plugin?

**Comment by phy1729** [comment]
That would be outside the scope. The syntax highlighting would have to be implemented by each REPL. Hopefully a search engine or asking the relevant channel on freenode turns up some results.

**Comment by danielshahaf** [comment]
IIRC ipython's REPL is better than CPython's.
