### ISSUE TITLE
How to change 'dark blue' color when typing wildcard file name like (*.c)?

### ISSUE THREAD

**Issue by dlintw** [zsh-users/zsh-syntax-highlighting#515]
My terminal background is black. The 'blue' color is difficult to see.

**Comment by danielshahaf** [comment]
I recommend to reconfigure your terminal's colour scheme, because that blue is one of the standard eight colours.

Alternatively, `ZSH_HIGHLIGHT_STYLES[globbing]=fg=blue,bold` ought to do it (I can't test the syntax now, sorry).

**Comment by dlintw** [comment]
Thanks, it works.
