### ISSUE TITLE
Consider integrating zsh-url-highlighter

### ISSUE THREAD

**Issue by N4M3Z** [zsh-users/zsh-syntax-highlighting#516]
Dear zsh team, please consider integrating [ascii-soup/zsh-url-highlighter](https://github.com/ascii-soup/zsh-url-highlighter) into the syntax highlighting project. It's simply a matter of adding it to `[zsh-syntax-highlighting-dir]/highlighters/url`. While the project is no longer maintained it works well and should be worthy of inclusion. I'm willing to make a pull request if acceptable.

**Comment by danielshahaf** [comment]
Thanks for broaching the topic.

I'm not a fan of this idea.

1. Merging it would add an ongoing maintenance burden that no one has volunteered to shoulder.

2. There isn't anything stopping people from using zsh-url-highlighter right now when it's a third party project (or if there is any such thing, it's a bug).

3. The plugin is already on https://github.com/unixorn/awesome-zsh-plugins so it's discoverable.

4. The plugin clears the cache in precmd, so hitting `up-history` repeatedly would spam remote servers with `HEAD` requests.

5. We don't have the author's permission to include his code.  There isn't any license header on the code either.

**Comment by N4M3Z** [comment]
Hello Daniel, those are strong arguments that I don't have good answers for. I could help with 1. and 5. The main motivation is that ZSH framework maintainers are not willing to merge url highlighter as another 3rd party component, but almost all of them already include the syntax highlighting.

**Comment by danielshahaf** [comment]
Closing, but feel free to reopen if circumstances change.  Note that (5) is a blocker.
