### ISSUE TITLE
Confuses visual-mode highlighting with select-bracketed / select-quoted

### ISSUE THREAD

**Issue by softmoth** [zsh-users/zsh-syntax-highlighting#521]
The [Zle/select-bracketed][1] and [select-quoted][2] functions work in `visual` and `viopp` modes, and select a portion of the buffer surrounded by matching brackets or quotes. When zsh-syntax-highlighting is loaded, the text is selected but the visual feedback of highlighting the selected text does not happen until the next key press.

[1]: https://github.com/zsh-users/zsh/blob/master/Functions/Zle/select-bracketed
[2]: https://github.com/zsh-users/zsh/blob/master/Functions/Zle/select-quoted

Set up using the default binding recommended at the top of the function file:
```zsh
autoload -U select-bracketed
zle -N select-bracketed
for m in visual viopp; do
  for c in {a,i}${(s..)^:-'()[]{}<>bB'}; do
    bindkey -M $m $c select-bracketed
  done
done
```

Type in something like `: " this is a test "`, and move into the middle of the string in `vicmd` mode. Type `va"`. When z-sy-h is not loaded, the text is highlighted immediately from the first to the last quote, and the cursor is placed on the last quote in visual mode.

When z-sy-h is loaded, the cursor is placed on the last quote in visual mode, but no highlighting is done to indicate the text is selected. Pressing `h` to move the cursor left then causes the highlight to happen.

**Comment by danielshahaf** [comment]
Does the `zle -N` you quote happen before loading z-sy-h? Does this happen with the `feature/redrawhook` branch?

**Comment by softmoth** [comment]
My bad, just a loading order problem (the select-* widgets were getting in there after syntax highlighter).

**Comment by softmoth** [comment]
Thanks, Daniel. You spotted it just as I did, sorry for the noise.
