### ISSUE TITLE
Supporting lookaheads/lookbehinds in regex highlighting

### ISSUE THREAD

**Issue by josh-byster** [zsh-users/zsh-syntax-highlighting#522]
First of all, I wanted to thank you for the awesome plugin. 

I wanted to add highlighting for the second term in a git command. For example, having the `status` in `git status` be highlighted a different color. I still want the `git` to be highlighted green like I have the other commands. I tried adding the following as examples:

`ZSH_HIGHLIGHT_PATTERNS+=('(?<=git )status' 'fg=blue,bold')`

`ZSH_HIGHLIGHT_PATTERNS+=('(?<=git )rebase' 'fg=red,bold')`

However, it doesn't seem like lookbehinds are supported. Am I doing anything wrong or is this not supported at the time? Thank you.

**Comment by phy1729** [comment]
The regexp highlighter uses the `ZSH_HIGHLIGHT_REGEXP` variable as the `ZSH_HIGHLIGHT_PATTERNS` variable is used by the pattern highlighter. Since you're using a lookaround, you'll want to `setopt RE_MATCH_PCRE`.  With those two changes I get the expected behavior.

**Comment by josh-byster** [comment]
Thanks - is there a way I can get PCRE without having to reinstall zsh?

**Comment by danielshahaf** [comment]
> Thanks - is there a way I can get PCRE without having to reinstall zsh?

It is possible that your distro built the zsh/pcre module as a shared
library but put pcre.so in a separate package.  In that case, just
installing the additional package will suffice.  Otherwise you'll have
to rebuild zsh with pcre support.

But first, run `zmodload zsh/pcre` and see if it already works.  (If it
outputs nothing, it worked.)

**Comment by josh-byster** [comment]
@danielshahaf thanks for the response, doesn't look like pcre exists at all as your commend doesn't run without output. I'm on OS X High Sierra - I might be able to try rebuilding zsh.
