### ISSUE TITLE
main-highlighter.zsh: hang when highlight word matches dead remote mount in pwd

### ISSUE THREAD

**Issue by wraeth** [zsh-users/zsh-syntax-highlighting#528]
**Brief Description**
In some circumstances, the main highlighter can hang the shell. This can occur when the word being typed matches a directory in $PWD, and that directory is a mounted remote filesystem (NFS in this case) which has since died (mounted but non-responsive). Adding the directory to `X_ZSH_HIGHLIGHT_DIRS_BLACKLIST` has no effect.

**Steps to replicate**

1. Create directory in $PWD with any arbitrary name (eg. `~/myoldhost`)
2. Mount an NFS share to this directory
3. Make the NFS share non-responsive (in my case: break networking on remote host)
4. Attempt to type a command where an argument happens to be the same name (eg. `ssh myoldhost`)

**Expected result**

Command to be successfully entered and ready to execute

**Actual result**

Shell hangs before last character appears

**Details**

This appears to be caused by the highlighter attempting to probe the named directory, in some cases regardless of whether the argument is a directory/path type, while the mount is dead. Because the system still sees it mounted, the probe is queued waiting for a response resulting in the shell hanging waiting for the syscall to return.

**Comment by phy1729** [comment]
Fixed with #529.
