### ISSUE TITLE
Issue with oh-my-zsh

### ISSUE THREAD

**Issue by jsauvain** [zsh-users/zsh-syntax-highlighting#530]
Hi there

I'm very new to zsh and probably it's not even a bug, but if I start up iTerm, the z-sy-h plugin is not starting but if I type `source .zshrc` it's working afterwards. Any ideas? Thanks in advance

**Comment by danielshahaf** [comment]
You'll have to ask the omz folks.

The upstream zsh community doesn't recommend omz; #zsh on freenode is friendly and helpful and will help you get started with zsh.

My best guess is that you have multiple zshrc files.

**Comment by crazyhottommy** [comment]
@shortspecialbus I did the same, but no highlighting for me. I am using iterm2 + oh-my-zsh and put the highlighting plugin in the  ` ~/.oh-my-zsh/custom/plugins ` and add `plugins=( zsh-syntax-highlighting )` to the .zshrc file.

**Comment by shortspecialbus** [comment]
Make sure it's the last plugin loaded.  Also make sure you didn't accidentally nest it in custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.  Also make sure iterm2 is set to run as a login shell, I guess - I dunno how iterm2 works, but make sure it has something similar to the '-ls' option of xterm.  Beyond that you should probably create a new issue if you're still having trouble as this one is marked closed, good luck.

**Comment by danielshahaf** [comment]
Good advice :).

It shouldn't matter whether zsh is run as a login shell or not.  That basically only affects which dotfiles are sourced, but `.zshrc` is sourced in all interactive shells.

**Comment by crazyhottommy** [comment]
Thanks! it turns out  I had

```
plugins=(git) 
```
in the `.zshrc`.

I put them together

```
plugins=(git  zsh-syntax-highlighting) 
```
it worked! thanks you very much

**Comment by danielshahaf** [comment]
> Thanks! it turns out I had
> 
> `plugins=(git) 
> ` 
> in the `.zshrc`.
> 
> I put them together
> 
> `plugins=(git  zsh-syntax-highlighting) 
> ` 
> it worked! thank you very much

You can use the append syntax, `plugins+=(git)` followed by `plugins+=(zsh-syntax-highlighting)`.
