### ISSUE TITLE
Keywords following the alias `_` for `sudo` aren't highlighted

### ISSUE THREAD

**Issue by laviande22** [zsh-users/zsh-syntax-highlighting#531]
It does make sense that the following keyword after `sudo` should also be highlighted when I issue a command including `sudo` keyword on Z shell. And the plugin actually does so.

![screenshot from 2018-09-11 11-37-24](https://user-images.githubusercontent.com/18096835/45334829-7f0cfb80-b5b7-11e8-8986-759e38a62570.png)

As you all can see, the keyword `systemctl` is properly highlighted. On the other hand, when I issue the same command except for the alias part,

![screenshot from 2018-09-11 11-42-30](https://user-images.githubusercontent.com/18096835/45334890-c6938780-b5b7-11e8-88f3-cae01214eb04.png)

it doesn't highlight the keyword which is quite counterintuitive.

**Comment by phy1729** [comment]
I believe this will be fixed once #471 is merged.

**Comment by laviande22** [comment]
It's good to hear that! When do you think the PR could be merged? Thank you for your contributes.
