### ISSUE TITLE
Running with master results in ls not showing anything

### ISSUE THREAD

**Issue by CMCDragonkai** [zsh-users/zsh-syntax-highlighting#534]
I was checking out the master branch, and whenever I run `ls` I get no results whatsover.

**Comment by danielshahaf** [comment]
This project colors the command lines, not the output of commands.  You should see that the letters `l` and `s` are red and then green.  For coloring `ls` output look up LS_COLORS.

**Comment by CMCDragonkai** [comment]
I understand what this project does. But I'm saying that after switching to master `ls` doesn't show output. Then I switched back and things worked properly.

**Comment by danielshahaf** [comment]
Do you get the described result when you use z-sy-h from within a fresh instance of `zsh -f`?

**Comment by CMCDragonkai** [comment]
On each switch, I started a whole new terminal emulator with ZSH in it. I rolled back to 0.6.0 right now.

**Comment by danielshahaf** [comment]
> On each switch, I started a whole new terminal emulator with ZSH in it. 

That's not good enough.  Please provide a minimal reproduction recipe from within `zsh -f`.

> I rolled back to 0.6.0 right now.

Could you bisect?

**Comment by nicoulaj** [comment]
@CMCDragonkai could try again after 3a7ddcda0b854d60058ac488b52c837e7ea92fc6 ?
