### ISSUE TITLE
X_ZSH_HIGHLIGHT_DIRS_BLACKLIST only works with a single path

### ISSUE THREAD

**Issue by swalladge** [zsh-users/zsh-syntax-highlighting#537]
If I add multiple directories to the blacklist array, the blacklist stops working. For example:

```
X_ZSH_HIGHLIGHT_DIRS_BLACKLIST+=("$HOME/mnt")
X_ZSH_HIGHLIGHT_DIRS_BLACKLIST+=("$HOME/Network")
```
It works fine without the second line there.

**Comment by phy1729** [comment]
Fixed by 1eedb23. Thanks for the report!
