### ISSUE TITLE
Quoted alias does not fall back to command

### ISSUE THREAD

**Issue by phy1729** [zsh-users/zsh-syntax-highlighting#544]
```
alias ls='ls -l'
\ls
```

Should highlight `\ls` as a command.

**Comment by Sea-n** [comment]
I think it's already fixed by 8001587

**Comment by danielshahaf** [comment]
Good catch.  See also 4c5d44d5e4aee8f1c108d3d346111f80f0ba2bb4 on #545.

**Comment by phy1729** [comment]
Fixed in cb8c736 #556.
