### ISSUE TITLE
Broken Arithmetic Expression Highlighting

### ISSUE THREAD

**Issue by sorin-ionescu** [zsh-users/zsh-syntax-highlighting#55]
Highlighting is broken when arithmetic expressions are used in control statements, loops, and perhaps, other places. 

![If Statement](http://i.imgur.com/3MsLk.png)

![For Loop](http://i.imgur.com/FeM2v.png)

**Comment by danielshahaf** [comment]
Works fine. Must have been fixed sometime in the last four years.
