### ISSUE TITLE
Commands prepended with "\" are highlighted as errors.

### ISSUE THREAD

**Issue by nemaniarjun** [zsh-users/zsh-syntax-highlighting#555]
I have global alias set up to expand all aliases in the current statement when I press the space bar.
`ls` is expanded to `\ls --color=tty`.
Earlier it used to shows `\ls` part as white which was fine for me, but now it shows it as red which annoys me. 
Can we edit the script to show it as green or can you point me to the line that I can change to make it show white again? 

Thanks a lot for the great work!

Cheers! :grin:

**Comment by phy1729** [comment]
Dup of #544.

**Comment by danielshahaf** [comment]
It's not actually a duplicate. This issue is about `\ls` being the first word of the alias's expansion. That issue is about using `\foo` when `alias foo=bar` exists to bypass it.

**Comment by phy1729** [comment]
Should be fixed in cb8c736 #556. Please confirm.

**Comment by danielshahaf** [comment]
It's white for me.
