### ISSUE TITLE
command highlight reversed after update

### ISSUE THREAD

**Issue by tmccombs** [zsh-users/zsh-syntax-highlighting#557]
I just updated zsh-syntax-highlighting, and now if a command is valid it is highlighted as red, and invalid commands are highlighted as green

**Comment by danielshahaf** [comment]
Works for me. Please give a reproducer that starts from `zsh -f`.

**Comment by tmccombs** [comment]
hmm, actually my original description is wrong. What' happening is it is marking aliases that start with an environment variable as unknown-token.

For example:

```zsh
$ alias ls=''A=a ls"
$ ls
```
ls is highlighted as red. 

(this happens with `zsh -f`)

**Comment by danielshahaf** [comment]
Duplicate of #554

**Comment by tmccombs** [comment]
ah, yes it is. thanks
