### ISSUE TITLE
Typing . after .. will cause an error message to appear 

### ISSUE THREAD

**Issue by dongsiji** [zsh-users/zsh-syntax-highlighting#562]
After typing .. in the terminal, additional . behind will cause 
```zsh-syntax-highlighting: BUG: _zsh_highlight_main_highlighter_expand_path: called without argument```
to be appended to the terminal.

**Comment by dongsiji** [comment]
![image](https://user-images.githubusercontent.com/35907419/47266787-d797c700-d56d-11e8-9263-7aa48d0f6658.png)

**Comment by danielshahaf** [comment]
Duplicate of #549. Thanks for the reproduction recipe.

**Comment by dongsiji** [comment]
Didn't notice #549 thanks.
