### ISSUE TITLE
Highlight scalar assignments

### ISSUE THREAD

**Issue by danielshahaf** [zsh-users/zsh-syntax-highlighting#572]
In `x="foo"`, highlight `"foo"`, as we already do for `typeset x="foo"` and for `x="foo` (incomplete) in command position.

The RHS of an assignment is implicitly double quoted (like reserved word `typeset`, unlike builtin `typeset`).  I'm not sure whether this has implications for the highlighting.

**Comment by danielshahaf** [comment]
The double quotes are eaten by https://github.com/zsh-users/zsh-syntax-highlighting/blob/4ce56a821e9988c1a24fa1b1d62ed57f72893217/highlighters/main/main-highlighter.zsh#L551-L552

So how about this?

```diff
diff --git a/highlighters/main/main-highlighter.zsh b/highlighters/main/main-highlighter.zsh
index 12e48fe..cd21d65 100644
--- a/highlighters/main/main-highlighter.zsh
+++ b/highlighters/main/main-highlighter.zsh
@@ -547,7 +547,7 @@ _zsh_highlight_main_highlighter_highlight_list()
         fi
         (( in_redirection++ )) # Stall this arg
         continue
-      else
+      elif ! _zsh_highlight_main_highlighter_check_assign; then
         _zsh_highlight_main_highlighter_expand_path $arg
         arg=$REPLY
         _zsh_highlight_main__type "$arg" 0
```

It also fixes #571.

**Comment by phy1729** [comment]
I think it would be better to not change `arg`, so how about this?

```diff
diff --git a/highlighters/main/main-highlighter.zsh b/highlighters/main/main-highlighter.zsh
index eb49d8a..958c048 100644
--- a/highlighters/main/main-highlighter.zsh
+++ b/highlighters/main/main-highlighter.zsh
@@ -559,8 +559,7 @@ _zsh_highlight_main_highlighter_highlight_list()
         continue
       else
         _zsh_highlight_main_highlighter_expand_path $arg
-        arg=$REPLY
-        _zsh_highlight_main__type "$arg" 0
+        _zsh_highlight_main__type "$REPLY" 0
         res="$REPLY"
       fi
     fi
```

With the above change, the only place arg is overwritten is for parameter expansion (which makes the highlighting of
```zsh
foobar='x=$(ls)'
$foobar
```
interesting).

**Comment by danielshahaf** [comment]
Scalar assignments have been highlighted for a while.  (They went away and came back in #663.)  The concern in the previous comment is valid so I filed it as #670.
