### ISSUE TITLE
Cannot change alias fg highlighting

### ISSUE THREAD

**Issue by danielshahaf** [zsh-users/zsh-syntax-highlighting#576]
```zsh
% alias x=ls
% ZSH_HIGHLIGHT_STYLES[alias]=fg=yellow,bold
% x
```

In 0.6, the alias is yellow. In master, it's green.  That's an incompatibility/regression.

See also https://github.com/zsh-users/zsh-syntax-highlighting/issues/574#issuecomment-434434062 and recent changes to test expectations.

**Comment by phy1729** [comment]
Resolved in #568.
