### ISSUE TITLE
More elegant way to use as user

### ISSUE THREAD

**Issue by tuyenpm9** [zsh-users/zsh-syntax-highlighting#589]
Currently zsh-syntax-highlighting.zsh must strictly be sourced manually, e.g: if you put the necessary folders and files under same folder (zsh-syntax-highlighting) then source all *.zsh file under that folder arbitrarily, it gives many error due to zsh-syntax-highlighting.zsh source files in order somehow.

**Comment by danielshahaf** [comment]
That's not a bug. That's just how programming works in virtually all imperative languages.

**Comment by danielshahaf** [comment]
Closing, unless there are reasons why what you describe should work.?
