### ISSUE TITLE
sudo and function

### ISSUE THREAD

**Issue by Raizo62** [zsh-users/zsh-syntax-highlighting#591]
Hi

I have installed github version of zsh-syntax-highlighting

I have configured my zsh with :
```
        source /opt/raizo/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
        ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern)

```
That works nice.

But i must configure sudo to start the commande grc : 

```
raizo_function_colored_sudo() { grc sudo "$@" }
alias sudo='raizo_function_colored_sudo '
```

Then with the command "sudo ifconfig", only "sudo" is colored.

Do I have to configure anything else?

**Comment by danielshahaf** [comment]
> raizo_function_colored_sudo() { grc sudo "$@" }
> alias sudo='raizo_function_colored_sudo '

The problem is that z-sy-h looks 'through' aliases.  That's why

$ zsh -f
% source zsh-syntax-highlighting.zsh
% alias x=sudo
% x ls

shows the 'ls' in green.  In your case, the easiest solution will be to convert the alias to a function:

raizo_function_colored_sudo() { grc sudo "$@" }
sudo() { raizo_function_colored_sudo "$@" }

**Comment by Raizo62** [comment]
No, i have a problem : i believe that i have not the completion on other alias.

**Comment by danielshahaf** [comment]
> No, i have a problem : i believe that i have not the completion on other alias.

Then do:

compdef sudo=raizo_function_colored_sudo

If that doesn't work, please ask on #zsh or on zsh-users@, since this really isn't a z-sy-h question any more.

**Comment by Raizo62** [comment]
Thanks for your answer.

This code seems sufficient :
```
# sudo can start alias
alias sudo='sudo '
# sudo can start colored commands
sudo() { grc sudo "$@" }
```
