### ISSUE TITLE
%? isn't glob

### ISSUE THREAD

**Issue by danielshahaf** [zsh-users/zsh-syntax-highlighting#596]
Via @phy1729 

`%?` is highlighted as a glob, though it isn't one: https://github.com/zsh-users/zsh/blob/f64cd71d442b0b7152131282dd7567be010edb78/Etc/BUGS#L6-L11

**Comment by phy1729** [comment]
```
: ''%? ""%? $(:)%?
```
are all not globs too. I don't think we should care too much about the first two cases (we don't for options either) and the third we must not support in the general case (due to possible side effects).
