### ISSUE TITLE
ctrl-W and ctrl-Y behaviour is broken

### ISSUE THREAD

**Issue by Elronnd** [zsh-users/zsh-syntax-highlighting#597]
In normal zsh, if I've typed `$ a b` and then ^W^W^Y, I'll end up with the same command-line -- `$ a b`.  With this addon, though, the ^W only captures the a, so I end up with `$ a`.

**Comment by danielshahaf** [comment]
Duplicate of #150, already fixed on the `feature/redrawhook` branch.
