### ISSUE TITLE
Multiple runs of initialization get slower and slower

### ISSUE THREAD

**Issue by shaform** [zsh-users/zsh-syntax-highlighting#600]
So if I modify `.zshrc`, I usually use `source ~/.zshrc` to update the current settings.

However, I found that as long as `zsh-syntax-highlighting` is enabled, then repeatedly executing `source ~/.zshrc` would become slower and slower.

**Comment by danielshahaf** [comment]
> However, I found that as long as `zsh-syntax-highlighting` is enabled, 
> then repeatedly executing `source ~/.zshrc` would become slower and 
> slower.

When z-sy-h is installed, it installs itself around whichever other plugins you already have... including itself. If you source z-asug and z-sy-h, both z-asug and z-sy-h will run.  If you source z-sy-h twice, both copies of z-sy-h will run.

I think you should change your zshrc to not source z-sy-h if that has already been done:

```
(( $+zsyh )) || { source z-sy-h.zsh && zsyh=sourced }
```

**Comment by shaform** [comment]
Thanks! This certainly works.
