### ISSUE TITLE
Can't get the regexp highlighter to load

### ISSUE THREAD

**Issue by stevehanson** [zsh-users/zsh-syntax-highlighting#604]
I see that there is a regexp highlighter in the codebase, but I can't seem to load it. When I add it to my highlighters list:

```
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main pattern regexp)
```

then when I start a terminal, I get: 

> zsh-syntax-highlighting: warning: disabling the 'regexp' highlighter as it has not been loaded

I originally had this plugin installed through Homebrew, but it didn't look like the latest version there had the highlighter. So, I uninstalled from Homebrew and installed this plugin with Zplug, and now I have the highlighter in my `~/.zplug`, but I still get the same error.

I took a look at how this plugin identifies if highlighters are loaded and tried the following from the command line:

```bash
> type "_zsh_highlight_highlighter_regexp_predicate"
_zsh_highlight_highlighter_regexp_predicate not found
```

That's as far as I took it. Any thoughts?

**Comment by phy1729** [comment]
Looks like we haven't had a release since regexp has been added, so you'd need to use a version from git rather than 0.6.0.

**Comment by stevehanson** [comment]
Thanks for getting back. I thought Zplug was pulling down the latest from git. I'm new to Zplug though so maybe I'm mistaken.

**Comment by stevehanson** [comment]
Here is the output I get when checking the type of the pattern predicate:

```bash
> type "_zsh_highlight_highlighter_pattern_predicate"
_zsh_highlight_highlighter_pattern_predicate is a shell function from /usr/local/Cellar/zsh-syntax-highlighting/0.6.0/share/zsh-syntax-highlighting/highlighters/pattern/pattern-highlighter.zsh
```

It looks like maybe that's something laying around from my Homebrew install. It's not clear to me what these predicate functions are or how they get installed.

**Comment by stevehanson** [comment]
It looks like this has something to do with how I'm loading it with ZPlug. I noticed that if I manually source the plugin, it works:

```
> source ~/.zplug/repos/zsh-users/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
```

I'm going to close this and assume the issue is a lack of my understanding of ZPlug. Thanks for your time!
