### ISSUE TITLE
zsh-syntax-highlighting breaks Zsh autocd for root entries

### ISSUE THREAD

**Issue by c-blake** [zsh-users/zsh-syntax-highlighting#606]
If there is a command in `$PATH` whose base name matches the basename of an entry under the root of the file tree (i.e., '/') then `AUTO_CD`/`autocd` no longer works to `cd` to that directory (nor does the command get run).

To reproduce you should be able to do this on any version of Zsh from the past several years (I tried Zsh-5.5 through Zsh-5.7.1 and `zsh-syntax-highlighting` 0.5.0, 0.6.0, and the current dev in this github).

E.g., the LLVM package has a program called "opt" and most folks have a directory called "/opt".  So, with a mostly empty `/etc/zsh/` (only a `zshenv` that sets `ZDOTDIR` only if it is not already set), this should reproduce:
```Zsh
(ZDOTDIR=/dev/null zsh -f)
host% setopt autocd
host% /opt
host% pwd
/opt
# Without z-s-highlighting it works fine.  Now activate z-s-highlighting:
host% . /usr/share/zsh/site-contrib/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
host% /opt
zsh: permission denied: /opt
host% opt -h     # This is the "opt" program from LLVM
opt: Unknown command line argument '-h'.  Try: 'opt -help'
opt: Did you mean '-S'?
```
If you don't happen to already have LLVM installed then you can also just create a script called `"usr"` and `chmod` it 755, `mv` somewhere in $PATH and watch `auto_cd` fail for `/usr`.  Most of the basenames in / on Linux are actually not such bad candidates for names of user scripts/programs, e.g., `run`, `proc`, `dev`, `boot`.

Oh, one more thing, the `autocd` _does_ work if you put a trailing '/' as in "/opt/".  Personally, I _never_ remember that trailing slash and this bug drives me bananas, as if permissions on my /-files are messed up.

Not sure, but this _could_ be a bug in Zsh that z-s-highlighting tickles.  If you attach an `strace` to the Zsh just before you press ENTER (maybe with a `-o/tmp/bug.st` to catch the verbose output) the activity you can see shows that it verifies `/usr/lib64/llvm/7/bin/opt` as an executable regular file, not a directory, but then tries to `execve("/opt")` which naturally gets a permission denied. { I feel like `EISDIR` would be a more natural `errno` than the `EACCES` in this case, but that's maybe some Linux kernel bitrot issue (man page suggests `EISDIR`, but kernel code seems to not do that anymore).  I suspect this happens on non-Linux, too, but given the above, the issued error might vary.  Yup..Just tested it on FreeBSD.  Still says "permission denied", though.  Didn't ktrace that one. }

I did look into the Zsh code and it mostly happens in a single C function that is about 1500 lines long.  Since I've only been able to make it happen with with z-s-highlighting, chances seem good that some used hook perturbs logic just enough.  Maybe this bug has arisen before, but I couldn't find any evidence of that.

**Comment by phy1729** [comment]
Minimal reproducer:
```
zsh -f
setopt autocd
type /opt
/opt
```

`type` is being called at https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/highlighters/main/main-highlighter.zsh#L183

Seems like a zsh bug.

**Comment by c-blake** [comment]
I can't reproduce your minimal reproducer.  When I try your e.g. with zsh-5.7.1 I just get `/opt not found` printed (same behavior as for `type /mnt` or any other entry without a corresponding command in `PATH`).  It looks like you get `/opt`.  Is that correct?

If I could have gotten it down to something that didn't depend on z-sy-h then I would have reported it to zsh upstream.

**Comment by phy1729** [comment]
What I posted above was just my input. Apologies for the confusion. With the output the reproducer looks like
```
% PS1='%% ' zsh -f
% setopt autocd
% type /opt
/opt not found
% /opt
zsh: is a directory: /opt
```

**Comment by c-blake** [comment]
Ah.  I see it misbehaving only for `/opt` (or other entries with a corresponding command somewhere in PATH) but not for `/usr` now.  Thanks for the minimal reproduction!  I'll either post a bug report to the main Zsh mailing list or maybe look into debugging it myself this weekend.

**Comment by danielshahaf** [comment]
Is there any workaround z-sy-h could use?  E.g., call `type` with different option flags?

**Comment by danielshahaf** [comment]
@c-blake I guess the 1500-line you refer to is in Src/exec.c? If you debug this, try tracing `type` at the C level (`bin_whence` in Src/builtin.c) — it might be poisoning some global state. Compare #354.

**Comment by c-blake** [comment]
Yeah.  Good suggestion @danielshahaf.  `Src/exec.c` was what I meant.  It all seems more tractable with the small reproduction @phy1729 came  up with (no idea how he figured that out so quickly...Maybe some debugging/tracing technique or maybe domain knowledge of z-sy-h or maybe both or prior knowledge of the bug?).

There may be a workaround for z-sy-h.  You know better than I how necessary that `type` @phy1729 pointed to is, but this also seems like a very bad Zsh bug others will want fixed.  It may be tickled by other packages and other "whence" uses.  The Zsh bug dates back to at least zsh-4.2.7 from 2007 which is the oldest version I could get to compile on a modern Linux box.  I could just report it, but if I can find an easy fix in a few hours of poking around then I'm sure that'd be more appreciated by the Zsh guys.

If you do think of an easy workaround for z-sy-h that has enduring value. It would workaround the bug on earlier versions of Zsh than Zsh-Next..not sure if you have any policy of trying to work on Zsh's N versions back or something.  I know things like CentOS/RedHat EL probably by default use Zsh from many years ago.

Anyway, I'll update this in a day or two when I've dug into it a bit more.

**Comment by danielshahaf** [comment]
> Yeah. Good suggestion @danielshahaf. `Src/exec.c` was what I meant. It all seems more tractable with the small reproduction @phy1729 came up with (no idea how he figured that out so quickly...Maybe some debugging/tracing technique or maybe domain knowledge of z-sy-h or maybe both or prior knowledge of the bug?).

Domain knowledge is that z-sy-h shouldn't have any effect on how the command word is resolved, only on how the command is highlighted; that such effects can happen only through calling shell builtins (such as `type` and `setopt`) or accessing builtin variables; and that z-sy-h does very little of either of these.

If you load z-sy-h, enable tracing (`functions -t _zsh_highlight`), and type `/op<Ctrl+L><Ctrl+L>t` — I mean, press Ctrl+L twice there, to get rid of irrelevant parts of the trace — and manually grep the output for `opt` as a whole word, then you'll see a few dozen variable assignments and string comparisons, and one call to the `type` builtin.  That makes `type` the obvious suspect... though I am curious whether this is what Matthew (@phy1729) did, or whether I'm analyzing this with the benefit of hindsight.

> If you do think of an easy workaround for z-sy-h that has enduring value. It would workaround the bug on earlier versions of Zsh than Zsh-Next..not sure if you have any policy of trying to work on Zsh's N versions back or something. I know things like CentOS/RedHat EL probably by default use Zsh from many years ago.
> 

We don't have a strict policy, but we try to be compatible with older zsh as far as practicable.  We do have users who use OS-provided ancient zsh with latest z-sy-h.

> Anyway, I'll update this in a day or two when I've dug into it a bit more.

On behalf of the zsh maintainers, thank you for looking into this :).

**Comment by c-blake** [comment]
You're welcome and thanks for the debugging explanation.  :-)  I wouldn't be too shocked if this is a bug dating back almost forever.  For what it's worth the `-v` switch to `whence` that `type` does makes no difference to the buggy behavior.  So, it's really a general `whence`+`exec`+`PATH`+FS contents interaction bug.

Like I said, you know better how much your `type`/`whence` matters to z-sy-h.  Contents of '/' are usually very static, though.  That fact probably affords a workaround, but I won't be sure it only impacts root paths until it's fully debugged.  I don't know how practical the workaround would be. I'm honestly almost brand new to z-sy-h.

Zsh-bug-wise `whence` with no active option flags doesn't do very much.  Right now state mutation triggered by its call to `Src/exec.c:findcmd()` (probably `hashcmd`) and then interpreted by `Src/exec.c:execcmd_exec()` or something earlier autocd-wise is my prime suspect, but less sleepy eyes will work better.

**Comment by danielshahaf** [comment]
> Like I said, you know better how much your `type`/`whence` matters to 
> z-sy-h. Contents of '/' are usually very static, though. That fact 
> probably affords a workaround, but I won't be sure it only impacts root 
> paths until it's fully debugged. I don't know how practical the 
> workaround would be. I'm honestly almost brand new to z-sy-h.

We only use `type` for highlighting the command word, and then only as a fallback when the zsh/parameter associative arrays had no matches.

Moving the `type` call on line 183 to a subshell works around the issue.  I've pushed that.  Could you confirm the fix please?  Then I think we can close this issue (we don't have to wait for the upstream bug to be reported or fixed).

Incidentally, that subshell is probably a good idea for other reasons: as a comment there says, `type -w` does an implicit `rehash`, but it's not for z-sy-h to run `rehash`.

> Zsh-bug-wise `whence` with no active option flags doesn't do very much. 
> Right now state mutation triggered by its call to 
> `Src/exec.c:findcmd()` (probably `hashcmd`) and then interpreted by 
> `Src/exec.c:execcmd_exec()` or something earlier autocd-wise is my 
> prime suspect, but less sleepy eyes will work better.

That sounds right, but I'm not fully awake either.  If you have questions about the internals, zsh-workers@ would be the best place to ask them.

Thanks!

**Comment by c-blake** [comment]
I can confirm that your fix works for  me. { Given the sense of it, it should work for anyone and in all circumstances unless there's some very bad OS bug letting kids modify parent address spaces :-) }

**Comment by c-blake** [comment]
Also, Zsh has a more old school 1980s/1990s path search which in some ways is more user-friendly (e.g., it will find `mh/inc` if `/usr/bin/mh/inc` exists and only `/usr/bin` is in your `$PATH` allowing a sort of user-flexible namespacing).  Because of that, it is a little ambiguous if zsh people would want `/opt` to behave like that search and run the program or to `cd /opt`. 

Personally, I have been using `AUTOCD` very habitually since about 1993 and I would never just "root a path" by mistake and prefer the latter.  Right now it does _neither_ after whence gets it in `cmdnametab` which is definitely a bug.  There are just two possible resolutions.

POSIX says any `/` anywhere makes `execvp` skip path search completely.  I bet if one read the committee minutes this POSIX rule was to simplify for implementors a user-nicer rule of "begins with `/` or `./` or anything that "collapses" to a beginning like that such as `/////, `//./././`, etc.  To me that seems putting users at a lower priority than implementors which is wrong-headed.  They probably should have said something like The first path component _reduces_ to either ".", "..", or "/" .  

By now that's a very old standard, and sometimes people fixate on such standards over utility.  Zsh generally prioritizes utility over standards when they conflict, but a lot of the time also provides a `setopt` to get more standard behavior.  Probably the right answer is first fix `hashcmd` to do the most natural thing which is `autocd` into `/opt` if `autocd` is set and document it carefully, but others may disagree.

Anyway, before I file a report with a proposed new behavior or behavior branch, I'm going to search through the mailing list archives since 1995 and see if this topic has come up before and provide some back references.  (Just looping you in since you seemed interested.  This should be my last comment on this now solved-in-z-sy-h issue.)

**Comment by c-blake** [comment]
Also, a much simpler statement of my maybe-should-have-been-POSIX-rule/maybe-should-be-Zsh rule that I'm pretty sure is equivalent *and* how most people probably incorrectly conceive the actual rule is: `starts with '[./]'` or just "explicitly absolute or explicitly relative" in English.  That's also faster to test than `strchr(arg0, '/')` which scans the whole string, though there may be security complaints.

**Comment by danielshahaf** [comment]
Thanks for the additional background! :-)  I'm also subscribed to the upstream lists so I'll see any followups you post there.

The `mh/inc` behaviour is not the default; it is only the case when PATH_DIRS is set.

The criterion "starts with `.`" will false positive for paths such as `/.foo` and `/...` (literally three 0x2E bytes).  What you want, I think, is `^/|^\.\.?($|/)`, plus or minus however an empty string should be handled.  (The regexp is for presentation purposes; an implementation would use `char` comparisons.)

Let's continue the discussion on -workers@. See you there!

**Comment by danielshahaf** [comment]
Yeah, I hate it when I come home and find a movers' truck being unloaded and some guy explaining he's moving into my house because my kids had changed my address. Changing schools all the time is starting to become a problem.

**Comment by c-blake** [comment]
;-)

More seriously, I did once try z-sy-h on Cygwin but had to stop using it because it was almost unusably slow.  I didn't track down exactly why, but presume it was due to the slow `fork()` emulation (probably in a less conditional/fallback situation).

Ok.  See you over @-workers.  (and, yeah, I guess the rule needs to be a little more complex...I still think POSIX blew it for end-user command typer/organizers.  I've had `PATHDIRS` set since it existed and didn't test that in a `zsh -f` setting, but that might modulate the discussion.)

**Comment by danielshahaf** [comment]
Re Cygwin, sorry to hear that. I don't have access to Cygwin, so I rely on pull requests, or at least users who are able to test patches.

In this case, I'd suggest to start with a `zprof` run. We have a `make perf` too; it has had little attention recently, but it might help in conjunction with `git-bisect`. (Doesn't have to be you, but I'm adding this info here for future reference.)  

And yes, I agree that imposing a one-time complexity on implementors is preferable to imposing ongoing costs on users. The cost/benefit analysis is quite lopsided in this matter.

**Comment by danielshahaf** [comment]
workers@ discussion started: [workers/44132](http://www.zsh.org/cgi-bin/mla/redirect?WORKERNUMBER=44132)

**Comment by c-blake** [comment]
Thanks for the pointer.

Re Cygwin - having no highlighting was one of the _least_ painful aspects of that experience for me.  I generally try to avoid Windows/Cygwin whenever possible. Probably best to let someone else performance debug that, but I do suspect the problem is process creation if someone ever wants to look into it/comes to this thread via a search.
