### ISSUE TITLE
Test harness should fail a test file that exits non-zero

### ISSUE THREAD

**Issue by danielshahaf** [zsh-users/zsh-syntax-highlighting#609]
Test files should be able to force a failure if there is an error in their [setup code](https://github.com/zsh-users/zsh-syntax-highlighting/blame/bc3f77f719ae80b5258292a10a5461aee5597eb2/tests/README.md#L42-L46).¹

- [ ] Make sure that `return 1` or `exit 1` (one or the other, but not necessarily both) works to force a failure, and document that.
- [ ] Document in tests/README.md that test files may force a failure by printing to stdout

¹ The link goes to the blame display because of a GitHub UI shortcoming: https://github.com/holman/ama/issues/305.

**Comment by phy1729** [comment]
Is [skip_test](https://github.com/zsh-users/zsh-syntax-highlighting/blame/4fb570e1046fd39ee6703f45f7a6bf139c68bb69/tests/README.md#L19-L20) not sufficient for some use case?

**Comment by danielshahaf** [comment]
Sorry, the use-case is bc3f77f719ae80b5258292a10a5461aee5597eb2.  The tests added by that commit have preambles that verify the tests' preconditions.  I thought the tests should _fail_, not merely _skip_, if the preconditions don't hold.

I still think that would be sensible in the `ls` case (third file): if there's an `ls` function or alias defined during the test, chances are the harness is broken, so fail loudly.  I am ambivalent about the `zstyle` case: while we don't control the contents of $PATH, failing might have merit, in that we'll know to change the test to maintain coverage.

Incidentally, the first test already fails loudly, because the `NO_MATCH` option would abort execution entirely when the `EQUALS` expansion fails.

**Comment by phy1729** [comment]
Makes sense to me, Regarding `zstyle`, we can always make it a hard fail for now and downgrade to a skip later if necessary.

**Comment by phy1729** [comment]
`exit 1` will already error out, but not `Bail out!`. All that's needed to make `return 1` `Bail out!` is to change https://github.com/zsh-users/zsh-syntax-highlighting/blob/bc3f77f719ae80b5258292a10a5461aee5597eb2/tests/test-highlighting.zsh#L122 to say
```zsh
  . "$srcdir"/"$1" || { echo >&2 "Bail out! On ${(qq)1}: source failed: $?"; return 1 }
```
Or we could document that authors ought to print `Bail out! <message>` to stderr and exit non-zero if setup fails.

**Comment by danielshahaf** [comment]
I'd rather not hardcode TAP details into test files, so I prefer the former... though, needn't the left disjunct be wrapped in an anonymous function for `return` to DTRT?

**Comment by danielshahaf** [comment]
(which would shadow the outer `$1`)

**Comment by phy1729** [comment]
From `zshbuiltins(1)`
>       return [ n ]
>              Causes a shell function or `.' script to return to the invoking
>              script with the return status specified by an arithmetic
>              expression n.

**Comment by danielshahaf** [comment]
Thanks.

**Comment by phy1729** [comment]
Looking over this again, I think I'd prefer
```diff
diff --git a/tests/test-highlighting.zsh b/tests/test-highlighting.zsh
index b2a6db5..91f17fa 100755
--- a/tests/test-highlighting.zsh
+++ b/tests/test-highlighting.zsh
@@ -119,7 +119,7 @@ run_test_internal() {
   local BUFFER CURSOR MARK PENDING PREBUFFER REGION_ACTIVE WIDGET REPLY skip_test unsorted=0
   local expected_mismatch
   local -a expected_region_highlight region_highlight
-  . "$srcdir"/"$1"
+  . "$srcdir"/"$1" || { print '1..1\nnot ok - test setup'; return 0; }
 
   (( $#skip_test )) && { print -r -- "1..0 # SKIP $skip_test"; return; }
 
```
as a test setup failure, should not stop subsequent tests from running.
