### ISSUE TITLE
highlighting commands does not consider environment variables

### ISSUE THREAD

**Issue by euclio** [zsh-users/zsh-syntax-highlighting#611]
If you start a command with an environment variable, the command is highlighted as if it is invalid.

```sh
$ /bin/sh     # highlighted correctly
$ export BIN=/bin
$ $BIN/sh   # highlighted with the "invalid command" highlighting, even though `$BIN` contains a valid path
```

**Comment by phy1729** [comment]
The export is unrelated. The issue is that [the block handling parameters](https://github.com/zsh-users/zsh-syntax-highlighting/blob/7ba4f0f119495cd95c9811a0afa94cfbe337fdc3/highlighters/main/main-highlighter.zsh#L585) (et seq) only handles `$foo` or `${foo}`. Looks like a dup of #484.

**Comment by danielshahaf** [comment]
Duplicate of #484, with virtually the same example, even.
