### ISSUE TITLE
POSIX's [[ ]] conditions not matching

### ISSUE THREAD

**Issue by marcospb19** [zsh-users/zsh-syntax-highlighting#614]
Just installed _zsh-syntax-highlighting_
And this example isn't highlighting:

`if [[ "$USER" == root ]]; then...` 

Because of the `[[`

**Comment by phy1729** [comment]
What isn't highlighting? On master `if`, `[[`, `]]`, and `then` are highlighted as reserved-word and `"$USER"` as a double-quoted-argument (among some other highlights).

**Comment by danielshahaf** [comment]
Could you please show the output of `typeset -p ZSH_VERSION ZSH_PATCHLEVEL ZSH_HIGHLIGHT_REVISION ZSH_HIGHLIGHT_VERSION`?

**Comment by marcospb19** [comment]
Found the error.

I was installing 6.0 version from from pacman's package, and version 6.0 don't support '[[', it's "outdated".

Thanks for the help.
