### ISSUE TITLE
no such file or directory: /home/prashant/..../zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

### ISSUE THREAD

**Issue by Prashant-Acharya** [zsh-users/zsh-syntax-highlighting#615]
This shows up every time I open a new terminal.

**Comment by danielshahaf** [comment]
I'm sorry you're having trouble, but that is not a bug in zsh-syntax-highlighting.  It's a bug in whatever code tries to invoke z-sy-h.

**Comment by danielshahaf** [comment]
Are you trying to _install_ z-sy-h or to _uninstall_ it?
