### ISSUE TITLE
State of master - Ready for a new release?

### ISSUE THREAD

**Issue by hackel** [zsh-users/zsh-syntax-highlighting#618]
It's been nearly 2 years since the last release.  246 commits later, perhaps it's time for a new one?  Is master stable?

**Comment by danielshahaf** [comment]
Yes and yes.

As it happens, just this weekend Matthew and I merged or punted most of the issues on the 0.7.0 milestone in preparation for a release.

The blockers are one regression and writing changelog, etc. 

After that we can release — and then merge some destabilizing PR's and release 0.8.0-beta1 :-) 

Thanks for the reminder!

**Comment by danielshahaf** [comment]
Update. We just merged a fix for the last significant blocker, #576. Remaining tasks:

- [ ] Wait a few days for regression reports. (Considering the weekend and summer holidays, shall we wait until Friday?)
- [ ] Fix #623 (test expectations)
- [ ] Appoint a release manager
- [ ] Release

**Comment by danielshahaf** [comment]
A regression has been found, #627, so the release will be delayed. (We could tag a 0.7.0-beta1 even now, of course, but I don't know whether we will.)

**Comment by danielshahaf** [comment]
Haven't forgotten about this, but we are still waiting for someone to step up and volunteer to be the RM.

**Comment by danielshahaf** [comment]
We seem to be making little progress :( 

@phy1729 @nicoulaj I'm starting to wonder if we should release without updating changelog, to reduce the workload. Thoughts?

**Comment by danielshahaf** [comment]
0.7.0-beta1 has been released.

**Comment by danielshahaf** [comment]
Just merged a fix to #670.  Unless regressions are reported, we're ready to release.

**Comment by danielshahaf** [comment]
Released — later than I wanted to, but with the regressions fixed before the release.  (except #677)
