### ISSUE TITLE
highlighting unaccepted autosuggest

### ISSUE THREAD

**Issue by ChristopherChudzicki** [zsh-users/zsh-syntax-highlighting#620]
I recently switched to `zsh` and am using `zsh-syntax-highlighting` along with `zsh-autosuggestions`. Everything works well, except when I reject an autosuggestion, syntax-highlighting seems to be coloring it as if it were accepted:

<img width="727" alt="highlight_one" src="https://user-images.githubusercontent.com/9010790/60396905-28a48580-9b15-11e9-9680-d998aca0e674.png">
<img width="839" alt="highlight_two" src="https://user-images.githubusercontent.com/9010790/60396893-ff83f500-9b14-11e9-87bf-dcd1770a15d0.png">

The unaccepted suggestion is gray, as expected, if I remove `zsh-syntax-highlighting` from my `.zshrc` file:

<img width="907" alt="Screen Shot 2019-06-30 at 9 06 39 AM" src="https://user-images.githubusercontent.com/9010790/60397038-9dc48a80-9b16-11e9-962c-c6ed4d1ff9cf.png"> 

**Versions**:
- `zsh` version 5.3.0
- `zsh-syntax-highlighting` version 0.6.0
- `zsh-autosuggestions` version 0.6.3

**Related**: (edited to ling correct issue)
This issue was posted a while ago in the `zsh-autosuggestions` repo, but they closed it as a `syntax-highlighting` issue: ~https://github.com/zsh-users/zsh-autosuggestions/issues/12~ https://github.com/zsh-users/zsh-autosuggestions/issues/293

**Comment by danielshahaf** [comment]
I don't see any mention of zsh-syntax-highlighting in the referenced issue.?

Next steps:

- Test tip of `master` 
- Test tip of `feature/redrawhook`
- Come up with minimal reproducer starting from `zsh -f` 
    - How does z-asug add that text? `$POSTBUFFER`?

**Comment by danielshahaf** [comment]
zsh-syntax-highlighting recomputes highlighting at `accept-line` (= pressing `<Enter>` ). That's distinct from the highlighting passes that occur at every `self-insert`. I wonder if that's related... 

The `accept-line` callsite exists to remove `path-prefix` highlighting in `cd /usr/loca<accept-line>`.

**Comment by ChristopherChudzicki** [comment]
> I don't see any mention of zsh-syntax-highlighting in the referenced issue.?

You're right, I linked the wrong issue. Fixed it in an edit.

**Comment by danielshahaf** [comment]
@ChristopherChudzicki The referenced issue, to me, says "the issue reproduces with z-asug and z-sy-h but not with z-sy-h only"'. In particular, I do not read Eric's comment as triaging the defect to zsh-syntax-highlighting.

Next steps remain as in my previous comment. (If you're able to provide some of that info, please do.)

**Comment by ChristopherChudzicki** [comment]
I'm going to close, I think this was totally unrelated to `zsh-sy-h`. Turns out I had a script in `.zshrc` that was modifying `$BUFFER` on `accept-line`. 

Anyway, sorry it was unrelated, but thanks for some ideas thats helped me debug it.
