### ISSUE TITLE
syntax highliting for deleted programs 

### ISSUE THREAD

**Issue by kerolloz** [zsh-users/zsh-syntax-highlighting#621]
![image](https://user-images.githubusercontent.com/36763164/60441951-51617380-9c18-11e9-8067-7cd671312d24.png)

**Comment by danielshahaf** [comment]
Run `rehash` when you delete a program.

**Comment by kerolloz** [comment]
@danielshahaf same problem!
![image](https://user-images.githubusercontent.com/36763164/60504109-43b3f880-9cc1-11e9-999f-f80b5724c1b0.png)

**Comment by danielshahaf** [comment]
Works for me. Please give reproduction instructions starting with `zsh -f` using no external dependencies and show the output of `typeset -p ZSH_VERSION ZSH_PATCHLEVEL ZSH_HIGHLIGHT_REVISION ZSH_HIGHLIGHT_VERSION`.

**Comment by kerolloz** [comment]
![image](https://user-images.githubusercontent.com/36763164/60523738-8db1d400-9ceb-11e9-85f1-3bfd5b68da08.png)

**Comment by kerolloz** [comment]
by the way `lb` is [loopback3](//loopback.io/lb3) CLI for creating apps.
I deleted node and npm and reinstalled with `nvm`. so all the installed packages and their commands should be gone but I find that `lb` command still has syntax highlighting.

**Comment by danielshahaf** [comment]
I still need the information I requested in my last comment:

- Reproduction instructions that start by invoking `zsh -f`, end by demonstrating the bug, and are runnable on my workstation (hence, they should depend on nothing but zsh and standard POSIX commands).
- The output of the above command _at the point where the bug reproduces_.

And for future reference, please do not send screenshots when copy-pasting the contents of the terminal would be better.
