### ISSUE TITLE
Expectations of empty-command-newline #3 are unmeetable (was: Tests XPASS on master)

### ISSUE THREAD

**Issue by danielshahaf** [zsh-users/zsh-syntax-highlighting#623]
`make test` is currently failing due to an XPASS:

```zsh
# empty-command-newline
1..4
ok 1 - [1,1] «:»
ok 2 - [2,2] «;»
ok 3 - [3,3] «↵» - # TODO "issue #616"
ok 4 - cardinality check
```

We should change the test file so it either is expected to pass and passes, or is expected to fail and fails.

@phy1729 Were you working on this? What's the correct fix here?

**Comment by phy1729** [comment]
That test has been failing  since added a few weeks ago. I assumed you were working in the area.

Now that I look at it, shouldn't the third point be `  '3 3 commandseparator "issue #616"' # \n` rather than `unknown-token` (i.e. expect the correct result)?

**Comment by danielshahaf** [comment]
> That test has been failing  since added a few weeks ago. I assumed you 
> were working in the area.

I'm not.  I wasn't aware that travis was failing, though.

> Now that I look at it, shouldn't the third point be `  '3 3 
> commandseparator "issue #616"' # \n` rather than `unknown-token` (i.e. 
> expect the correct result)?

I'm not sure what it should highlight.

I suppose it shouldn't be unknown-token because the sequence semicolon-newline is muscle memory for C and Perl programmers (the rationale behind highlighting BUFFER=': ; ;' as an error doesn't apply here).  As to commandseparator, I wonder: should ';' and $'\n' command separators be highlighted differently?

**Comment by danielshahaf** [comment]
I've added a duct tape fix to the "CI is red" problem and am repurposing this issue to track implementing a proper fix.  See the commit message of ab4b6f5823ac026a17778becb4c661ab66016790 for details.

**Comment by danielshahaf** [comment]
Fixed by https://github.com/zsh-users/zsh-syntax-highlighting/commit/8e78e9dbba673d2a6933b5e98045eabd04f554f5.
