### ISSUE TITLE
BUG with start >= end for adjacent command substitutions in double quotes

### ISSUE THREAD

**Issue by goedel-gang** [zsh-users/zsh-syntax-highlighting#624]
There appears to be an issue with highlighting when you have two adjacent command substitutions in double quotes. Let me illustrate:

```
$ zsh -f
$ git log --oneline | head -n 1
ab4b6f5 'main': Hackily unbreak 'make test'.
$ source zsh-syntax-highlighting.zsh
$ echo "$(echo)$zsh-syntax-highlighting: BUG: _zsh_highlight_highlighter_main_paint: start(13) >= end(13)
$(echo)$(zsh-syntax-highlighting: BUG: _zsh_highlight_highlighter_main_paint: start(13) >= end(13)
ezsh-syntax-highlighting: BUG: _zsh_highlight_highlighter_main_paint: start(13) >= end(13)
czsh-syntax-highlighting: BUG: _zsh_highlight_highlighter_main_paint: start(13) >= end(13)
hzsh-syntax-highlighting: BUG: _zsh_highlight_highlighter_main_paint: start(13) >= end(13)
ozsh-syntax-highlighting: BUG: _zsh_highlight_highlighter_main_paint: start(13) >= end(13)
)zsh-syntax-highlighting: BUG: _zsh_highlight_highlighter_main_paint: start(13) >= end(13)
"zsh-syntax-highlighting: BUG: _zsh_highlight_highlighter_main_paint: start(13) >= end(13)
```

Where I was trying to type `$ echo "$(echo)$(echo)"` on the last command line.

As you can see, the revision I'm on is `ab4b6f5 'main': Hackily unbreak 'make test'.`.

My `zsh --version` is `zsh 5.7.1 (x86_64-pc-linux-gnu)`, running on a pretty freshly updated Arch Linux.

![win_screenshot_20190708_215126](https://user-images.githubusercontent.com/22038041/60842283-a9294d00-a1cb-11e9-91ac-369ad8f661f2.png)

**Comment by phy1729** [comment]
Just pushed a commit to master which should fix the issue. Please confirm and reopen if not resolved.

Explanation: We break the `double-quoted-argument` highlighting when entering a parameter substitution so unquoted things in the substitution don't appear to be quoted. The code that added these regions didn't check that the region was non-empty.

**Comment by goedel-gang** [comment]
Yes, that looks perfect! And extraordinarily speedy, too - awesome!

Thank you also for the brief explanation of the mechanics at play here - as a total novice I am now a tiny (but much appreciated) bit closer to understanding how this project works.

Keep up the good work!
