### ISSUE TITLE
Aliases are not highlighted when they start with a variable definition

### ISSUE THREAD

**Issue by mees-** [zsh-users/zsh-syntax-highlighting#626]
An alias is not highlighted when it starts with a variable definition

example:
```zsh
$ alias ssh="TERM=xterm ssh"
$ ssh
```

here the `ssh` on the second line is not highlighted green even though it should be

**Comment by danielshahaf** [comment]
It _is_ green in current master.

**Comment by phy1729** [comment]
In current master, all aliases that are not invalid are highlighted with the `alias` style which is green by default.

**Comment by mees-** [comment]
@phy1729 You're right, I was using an old version
