### ISSUE TITLE
Every time a new window or tab column is opened,plugin's  function falis

### ISSUE THREAD

**Issue by lovelyJason** [zsh-users/zsh-syntax-highlighting#628]
Hello,I found a problem.When I open a new window or a new tab column,my zsh has not suggestions on shell.Unless I  executed an order: source ~/.zshrc

Why?How can I resolve this problem.I can't find the answer from google and baidu
![Snipaste_2019-08-01_15-55-00](https://user-images.githubusercontent.com/50656459/62275617-ea341a80-b474-11e9-8380-d24866a0c00d.png)
![Snipaste_2019-08-01_15-55-51](https://user-images.githubusercontent.com/50656459/62275640-f324ec00-b474-11e9-8c6e-9bdb07a75f18.png)

**Comment by danielshahaf** [comment]
Hi, sorry for the late answer.  Could you please show the output of `typeset -p ZSH_VERSION ZSH_PATCHLEVEL ZSH_HIGHLIGHT_REVISION ZSH_HIGHLIGHT_VERSION`?  I'd like to see whether you use master.  You probably do use master, but if you use the feature/redrawhook branch, then you might be running into #579.

**Comment by danielshahaf** [comment]
Ping?

**Comment by danielshahaf** [comment]
Feedback timeout.
