### ISSUE TITLE
Invisible asterisk (*) character

### ISSUE THREAD

**Issue by rizkysyazuli** [zsh-users/zsh-syntax-highlighting#634]
This is the command that i type:

    git mv src/*.php src/theme

This is what i see:

![Anotasi 2019-09-22 110757](https://user-images.githubusercontent.com/152221/65382181-5d496700-dd29-11e9-8da9-cf76dc28371d.png)

* OS: WSL Ubuntu 18.04
* Terminal: Windows Terminal
* Theme: spaceship
* Font: Fira Code

**Comment by danielshahaf** [comment]
Run `print -P '%F{blue}Hello world%f!'`. What does it print?

**Comment by rizkysyazuli** [comment]
An invisible "Hello world" text

![Anotasi 2019-09-22 150914](https://user-images.githubusercontent.com/152221/65384313-1ff5d100-dd4b-11e9-8354-dc9d7fcc3370.png)

**Comment by danielshahaf** [comment]
@rizkysyazuli I thought that might be the case.  The most likely cause is that your terminal emulator uses for `blue` the same color as the background color.  (Note that `blue` and `cyan` are distinct.  You can see the difference with the `colortest` program.)  You should fix this in your terminal emulator settings.

**Comment by rizkysyazuli** [comment]
@danielshahaf ah, yes indeed it is. thx for the tip!
