### ISSUE TITLE
The zsh-syntax-highlighting seems not to work at macOS 10.15 Catalina

### ISSUE THREAD

**Issue by zezhishao** [zsh-users/zsh-syntax-highlighting#636]
<img width="650" alt="Snipaste_2019-10-11_09-29-19" src="https://user-images.githubusercontent.com/33691477/66617932-b100ef00-ec09-11e9-977c-33a3cc0840f6.png">

Hi,
I have installed this tool using the three different ways: Homebrew in my ~/.zshrc with a plugin manager.
It all does not work.

**Comment by phy1729** [comment]
That appears to be python code. zsh-syntax-highlighting only highlights what is typed at a zsh prompt not the output of other programs.
