### ISSUE TITLE
some aliases not highlighted

### ISSUE THREAD

**Issue by matyklugDebbuged** [zsh-users/zsh-syntax-highlighting#639]
for example vim, which is aliased to sudo vim, is no longer highlighted. once unaliased, it works again.

**Comment by danielshahaf** [comment]
Works for me with recent-ish zsh and z-sy-h master.

Could you please show the output of `typeset -p ZSH_VERSION ZSH_PATCHLEVEL ZSH_HIGHLIGHT_REVISION ZSH_HIGHLIGHT_VERSION`?

Can you reproduce the problem in `zsh -f`?  (Run that.  You'll get a `hostname% ` prompt.   At that prompt, run `source /path/to/zsh-syntax-highlighting.zsh` by hand, after replacing `/path/to` with the correct value, then type in your test command and check if it's highlighted correctly.)

**Comment by matyklugDebbuged** [comment]
just made a fresh install now, and it works. i probably screw something up before.
