### ISSUE TITLE
Getting this warning message: X_ZSH_HIGHLIGHT_DIRS_BLACKLIST is deprecated. Please use ZSH_HIGHLIGHT_DIRS_BLACKLIST.

### ISSUE THREAD

**Issue by ImShakthi** [zsh-users/zsh-syntax-highlighting#640]
Getting the following warning message, while opening my zsh shell

zsh-syntax-highlighting: X_ZSH_HIGHLIGHT_DIRS_BLACKLIST is deprecated. Please use ZSH_HIGHLIGHT_DIRS_BLACKLIST.

**Comment by phy1729** [comment]
The variable `X_ZSH_HIGHLIGHT_DIRS_BLACKLIST` is being set somewhere in your config. You should change it to `ZSH_HIGHLIGHT_DIRS_BLACKLIST` since the feature is no longer considered experimental (and the `X_` version will be removed later).

**Comment by danielshahaf** [comment]
Closed to keep the issue tracker tidy; not meaning to discourage further conversation.
