### ISSUE TITLE
Conflict with `zsh-users/zsh-autosuggestions`

### ISSUE THREAD

**Issue by elony314** [zsh-users/zsh-syntax-highlighting#647]
### Reproduce:
```sh
zsh -df
export WORDCHARS='*?_[]~=&;!#$%^(){}'
source zsh-autosuggestions.zsh
source zsh-syntax-highlighting.plugin.zsh
cd Test1/Test2 
```
Now, input `cd` and continuously use `ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS` until the end of the line. Instead of get the complete `Test1/Test2`, the `Test2` part will be duplicated.

### Expected behavior:
```sh
cd Test1/Test2
```

### Actual behavior:
```
cd Test1/Test2Test2
```

I have also submitted this bug [here](https://github.com/zsh-users/zsh-autosuggestions/issues/483)

**Comment by danielshahaf** [comment]
What's the behaviour when you don't source zsh-syntax-highlighting?

**Comment by elony314** [comment]
It works as expected.

**Comment by danielshahaf** [comment]
I can't reproduce the behaviour you describe _either_ with or without z-sy-h, and I'm not sure what might be going on here, but please try the feature/redrawhook branch.

Also, `WORDCHARS` needn't be exported.  (I'd have said this yesterday but I wasn't on a full-sized keyboard then.)
