### ISSUE TITLE
crash when # at beginning of line (w/ interactive_comments)

### ISSUE THREAD

**Issue by rpolve** [zsh-users/zsh-syntax-highlighting#648]
Hi,

I added 'setopt interactive_comments' to my .zshrc but now **whenever I put a '#' at the beginning of line, the shell crashes**.
I frequently did this in bash whenever I was typing a long command that I am not ready to execute, but need it to be stored in the history.

Secondarily, if i put a '#' **after** a command, it is rendered invisible -- but then, when executed, it is stored correctly in history.

**Comment by danielshahaf** [comment]
Please remove that line from your zshrc, then run `zsh -o interactivecomments` and quote the error message, if any.

Please report the output of `print -rl -- $ZSH_VERSION $ZSH_PATCHLEVEL $ZSH_HIGHLIGHT_VERSION $ZSH_HIGHLIGHT_REVISION`.

See also the widget bound to Alt+q by default in the `emacs` keymap (I don't remember its name by heart and can't look it up from here).

The "invisibility" is just a colorscheme issue. Look into your terminal emulator's RGB color values for the standard 16 colors.

**Comment by rpolve** [comment]
Thank you Daniel and sorry for the late reply.

I now notice it only happens if the command starts with a space, as someone would do as not to include it in the history.

```
[polve@isolengo ~]$  # ls
zsh: segmentation fault (core dumped)  zsh -o interactivecomments
[polve@isolengo ~]$ print -rl -- $ZSH_VERSION $ZSH_PATCHLEVEL $ZSH_HIGHLIGHT_VERSION $ZSH_HIGHLIGHT_REVISION
5.7.1
zsh-5.7.1-0-g8b89d0d
0.6.0
434af7b11dd33641231f1b48b8432e68eb472e46
[polve@isolengo ~]$
```

**Comment by danielshahaf** [comment]
Yes, please report it zsh-users@zsh.org.  It would be helpful if you could include in your report:

- A backtrace;
- A minimal reproduction (start `zsh -f` and manually run only as much of your zshrc as needed to reproduce the issue);
- (extra credit) Test results with [the 5.7.1-test-2 prerelease](https://sourceforge.net/projects/zsh/files/zsh-test/5.7.1-test-2/), if it's possible for you to test it.
