### ISSUE TITLE
Tab Completion issues

### ISSUE THREAD

**Issue by SonOfDiablo** [zsh-users/zsh-syntax-highlighting#654]
Hello,

I'm having a few issue with the syntax highlighting not working when using tab completion in certain scenarios (I know of 2 so far).

**Scenario One:**  
When hitting tab to perform a completion, but there is no valid completion, the syntax highlighting will disappear.   
Example when typing cd and then continuously hitting tab until you have no where else to go:   
One tab: 
![One Tab](https://i.imgur.com/LD18eIl.png)
Hit enter to select Desktop and then tab again: 
![Second Tab](https://i.imgur.com/ERsiy92.png)
   
   
**Scenario Two:**   
When tab completing a command (or alias) the highlighting works a bit odd.   
Example (using the yalst alias from the omz archlinux plugin):
Before tabbing:  
![Before Tab](https://i.imgur.com/wc0gJol.png)  
  
One (or more) tabs:   
![A Few Tabs](https://i.imgur.com/3CVLmLz.png)  
  
Now selecting with Enter appends a whitespace to the command, but doesn't apply highlighting. The highlighting is first applied when I hit backspace or write anything else. If I were to hit tab again the highlight still isn't applied.  
Select with Enter:
![Select with Enter](https://i.imgur.com/8itXBW7.png)   
Hit Space:
![Hit Space](https://i.imgur.com/NhleZom.png)  
Tab Right After:
![Tab Right After](https://i.imgur.com/L6m6taK.png)  
Tab After Space:
![Tab After Space](https://i.imgur.com/wHIknHO.png)   
   
   
.zshrc: https://pastebin.com/UDXY7L42
.zsh_plugins.txt: https://pastebin.com/J2nUf4yu   
   
If any other info about my setup is needed please let me know!

**Comment by danielshahaf** [comment]
Try the feature/redrawhook branch.

**Comment by SonOfDiablo** [comment]
> Try the feature/redrawhook branch.

That fixed my issues, thanks! :)

**Comment by mortezadadgar** [comment]
@danielshahaf I'm still facing first scenario it's no big deal but I think this is not fixed yet

**Comment by danielshahaf** [comment]
@mortezadadgar Did you try the proposed workaround?

**Comment by mortezadadgar** [comment]
> @mortezadadgar Did you try the proposed workaround?

redrawhook branch isn't merged into master?

**Comment by danielshahaf** [comment]
That branch has been merged but the new code is guarded by an `is-at-least 5.8.0.2`.  Try enabling the new codepath.

**Comment by mortezadadgar** [comment]
@danielshahaf yeah enabling redraw fixes the problem but it does introduce another issue with autosuggestions whether it's loaded before or after this plugin
![image](https://user-images.githubusercontent.com/27911493/150503598-305b5c5c-4afc-4880-9c85-5ea989f1306a.png)
![image](https://user-images.githubusercontent.com/27911493/150503555-adf5ed62-4f74-41f9-869c-b2c92fa3e0d7.png)
