### ISSUE TITLE
About color temperature

### ISSUE THREAD

**Issue by tztnuaji** [zsh-users/zsh-syntax-highlighting#657]
Why do i feel the colors are dark,such as green or blue,how do i make these colors lighter?

**Comment by danielshahaf** [comment]
See https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/main.md and your terminal emulator's definitions of the standard 16 colors.  (I don't recall off the top of my head what's the syntax for using 256 or 16M colors; if you wantn that, try asking #zsh on freenode.)

**Comment by danielshahaf** [comment]
(Or use [redshift](http://jonls.dk/redshift/).)

**Comment by tztnuaji** [comment]
> See https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/main.md and your terminal emulator's definitions of the standard 16 colors. (I don't recall off the top of my head what's the syntax for using 256 or 16M colors; if you wantn that, try asking #zsh on freenode.)

$ echotc Co
255

It is indeed possible to change the font color  by replacing the values of this array--ZSH_HIGHLIGHT_STYLES,but i am not clear about the 255 format, fg='255' or fg='255 255 0' or fg='255,255,0'  only the first one worked,if it is in hex triplet format,I can extract the colors through software like photoshop,but i cannot do it in 255 format.

**Comment by danielshahaf** [comment]
Again, I suggest that you follow up on either #zsh on freenode or zsh-users@zsh.org.  z-sy-h doesn't parse the color values; it just copies them verbatim into `$region_highlight` which zsh itself (specifically, zle) parses.

**Comment by tztnuaji** [comment]
> Again, I suggest that you follow up on either #zsh on freenode or [zsh-users@zsh.org](mailto:zsh-users@zsh.org). z-sy-h doesn't parse the color values; it just copies them verbatim into `$region_highlight` which zsh itself (specifically, zle) parses.

Appending  zmodload zsh/nearcolor at the end of the ~/.zshrc can enable hexadecimal format.
You have helped me a lot,thank you very much.
