### ISSUE TITLE
precommand flags with an unknown argument

### ISSUE THREAD

**Issue by danielshahaf** [zsh-users/zsh-syntax-highlighting#658]
I think `sudo -x ls` should _not_ be highlighted as an error, for forward compatibility with future versions of sudo.  Therefore, I think the test added in e27e53b1ef19387949f4a214c641c568539bb027 is wrong.

@phy1729 WDYT?

(FWIW, there was actually a comment about this very situation in the code before that commit — not that that matters now.)

**Comment by phy1729** [comment]
It's impossible for z-sy-h to know aprori if `-x` takes an argument. While it's true we currently assume it doesn't, at least there's an indication of where the parsing went wrong.

If there were a style for known syntax error distinct from unknown-token, unknown-token could be defaulted to normal masking such issues for end users.

**Comment by danielshahaf** [comment]
There are several different matters here.

First, was there a particular use-case or instance that prompted you to make the change?  If so, could you describe it, for context?

> It's impossible for z-sy-h to know aprori if -x takes an argument. While it's true we currently assume it doesn't,

Agreed: the code should make that assumption.  It should only assume the normal BSD option stacking conventions (as in `_arguments -s : "-◌+${colon_or_null}"`; we don't generally  know whether the `-◌` option takes an argument).  Therefore, `sudo -x foo bar` should highlight `-x` as `single-hyphen-option` and _both_ of the following words as `default` — exactly the same as `ls -x foo bar`, except for the command word.

That's neither what the code before the referenced commit did nor what HEAD does.

> at least there's an indication of where the parsing went wrong.

We shouldn't use unknown-token unless we know positively that there's a syntax error; showing bold red on valid command lines would be poor UX.  (Call it the Hippocratic Principle if you wish, or observe that ${EDITOR}s generally behave this way.)

If we've lost track of the state, we should fall back to `default` until we can resync (e.g., by encountering a global alias or a command separator).

Information about where parsing went wrong is like debug printf's: of interest to the developers but not to users.  Users just want their tools to stay out of their (the users') ways so they (the users) will be able to get on with whatever they're doing.

> If there were a style for known syntax error distinct from unknown-token, unknown-token could be defaulted to normal masking such issues for end users.

It is not a "known" syntax error.  `${precommand_options}` isn't the source of truth here.  It _could_ be a typo on the part of the user, but it could also be a new upstream release of `sudo` that the code doesn't know about.  Don't confuse the dependent and independent variables :-) 

To your point, having more than one "error" style, or having some form of debug tracing, can certainly be discussed — but I do think that the behaviour expected by that test should be changed.  WDYT?

**Comment by danielshahaf** [comment]
By the way, falling back to `default` would also be sensible for any --long-options that we don't know about. (Few of the existing precommands have long options, but more might be added in the future.)

**Comment by danielshahaf** [comment]
*sigh*

I just rediscovered #641, which basically points out that this issue is a regression from 0.6.0: it causes `sudo --askpass` to be highlighted as an error where previously it worked.

As it's a regression, I'm bumping the milestone.  Which unfortunately makes this issue a release blocker :(

Let's try and agree on a fix.

**Comment by danielshahaf** [comment]
PR #664.
