### ISSUE TITLE
Review test expectations of pasted quotes (#130)

### ISSUE THREAD

**Issue by danielshahaf** [zsh-users/zsh-syntax-highlighting#661]
@phy1729 Could you have a look at the test expectations in e9b1ce1a36a2?  The test passes, but should `default` apply to the whole word or only to the `bar` part?  I'm sure we discussed this but I don't recall the conclusion…  Thanks!

**Comment by phy1729** [comment]
#481 was where it previously came up. The `base_style` in _highlight_argument specifies what the argument is (option or default) and the other styles handle the quoting and substitutions that make up the word.

**Comment by danielshahaf** [comment]
Thanks for the pointer!  And sorry, I should've figured the answer out myself…
