### ISSUE TITLE
Possible additions to 0.7.0's changelog

### ISSUE THREAD

**Issue by danielshahaf** [zsh-users/zsh-syntax-highlighting#662]
@phy1729 Should any of the following four commits be mentioned in changelog?

commit ac90970edcfe8c6c0f1804fb0f32f5aa8b9f9137
Author: Matthew Martin <phy1729@gmail.com>
Date:   Thu Nov 2 19:11:00 2017 -0500

    brackets: Don't call _zsh_highlight_add_highlight with empty style

 highlighters/brackets/brackets-highlighter.zsh | 5 ++---
 1 file changed, 2 insertions(+), 3 deletions(-)

commit 9dcfacc4a5229c2b368043c9ff10dc7936c4b886
Author: Matthew Martin <phy1729@gmail.com>
Date:   Thu Nov 2 19:23:18 2017 -0500

    brackets: Disallow negative nesting level

 highlighters/brackets/brackets-highlighter.zsh | 14 +++++++++-----
 1 file changed, 9 insertions(+), 5 deletions(-)

commit ff85c7e01b0a7e5d9f92fc0195685edbea2b8dbc
Author: Matthew Martin <phy1729@gmail.com>
Date:   Tue Feb 6 18:48:46 2018 -0600

    driver: Do not highlight newlines or past BUFFER for zle standout

 zsh-syntax-highlighting.zsh | 6 ++++--
 1 file changed, 4 insertions(+), 2 deletions(-)

commit e1ecf950e23471b235e318ba7b85e77395a6b146
Author: Matthew Martin <phy1729@gmail.com>
Date:   Mon Oct 1 11:10:44 2018 -0400

    main: Do path expanstion after alias expansion

 highlighters/main/main-highlighter.zsh | 10 +++++++---
 1 file changed, 7 insertions(+), 3 deletions(-)

**Comment by phy1729** [comment]
brackets: Don't call _zsh_highlight_add_highlight with empty style
brackets: Disallow negative nesting level
driver: Do not highlight newlines or past BUFFER for zle standout
These three are bug fixes that shouldn't be user visible and (if memory serves) were only caught by improvements to the tests. I'd leave them out.

main: Do path expanstion after alias expansion
Also doesn't seem important enough to mention.

**Comment by danielshahaf** [comment]
Thanks, that was easy :)
