### ISSUE TITLE
 plugin breaks 'select-word-style bash' functionality

### ISSUE THREAD

**Issue by datanoise** [zsh-users/zsh-syntax-highlighting#67]

**Comment by davidshepherd7** [comment]
This is a problem for me as well. The reason that I can't simply source this plugin after setting the word style is that I have functions like the following:

    kill-bashword () {select-word-style bash; zle kill-word}

bound to keys. So `select-word-style` will be called when this keybinding is used, which will always be after loading the plugin. Is there absolutely no way around this?
