### ISSUE TITLE
Precommand killing options

### ISSUE THREAD

**Issue by phy1729** [zsh-users/zsh-syntax-highlighting#678]
As mentioned in 77c6bf20 and the linked comment, some precommands have options which result in the command no longer acting as a precommand (e.g. `sudo`'s `-e`). `precommand_options` needs to be extended with another section for such flags. (Name improvements welcome).

**Comment by danielshahaf** [comment]
Could you outline an XFail test for this?  What's an example value of $BUFFER and its desired (≠ actual) highlighting?

**Comment by phy1729** [comment]
https://github.com/phy1729/zsh-syntax-highlighting/tree/i678-tests ( https://github.com/phy1729/zsh-syntax-highlighting/commit/e1e302b45fdae0fc130ebed4375a183b7c172382 )

The first isn't XFail due to #202 / #669 .

**Comment by danielshahaf** [comment]
Thanks; any reason not to merge them?

I've noted the regression on #669.
