### ISSUE TITLE
SH_WORD_SPLIT variable expansions in command positions are incorrectly highlighted

### ISSUE THREAD

**Issue by kbd** [zsh-users/zsh-syntax-highlighting#687]
As reported [in a different thread](https://github.com/zsh-users/zsh-syntax-highlighting/issues/617#issuecomment-595924724), aliases to environment variables are highlighted incorrectly:

![Screen Shot 2020-03-06 at 12 27 52 PM](https://user-images.githubusercontent.com/728060/76115759-00bfc880-5fa6-11ea-9add-8f1a1ff6904c.png)

Using Homebrew installed version 0.7.1.

**Comment by danielshahaf** [comment]
With the first definition in effect, what happens when you _run_ the `e` alias?

Is the SH_WORD_SPLIT option set?

**Comment by kbd** [comment]
Good questions. `sh_word_split` is set, and I have my `$EDITOR` set to `open -t` on Mac so it opens the default system text editor (vscode):

![Screen Shot 2020-03-11 at 9 44 53 AM](https://user-images.githubusercontent.com/728060/76435746-068a2500-637d-11ea-9216-cbb9af2be18f.png)

When I run the first `e`, it runs `open -t` and correctly opens vscode. When I run the second `e` it opens vim.

**Comment by danielshahaf** [comment]
Retitled the issue; it's not specific to aliases, nor to environment variables.

> Edit: this alias is one of the reasons I have `sh_word_split` set. For reference, here's what happens when it's not set:

You could leave shwordsplit at its default value (unset) and change the alias: replacing the alias by a function definition such as `e() { eval $EDITOR "${(q)@}" }` should DTRT.

If you want to look into adding shwordsplit support, that would probably require having [the parameter expansion code](https://github.com/zsh-users/zsh-syntax-highlighting/blob/1a752da1c2f58bd96e1e09a83f53556060674f3f/highlighters/main/main-highlighter.zsh#L636-L675) consult `${zsyh_user_options[shwordsplit]}`.

**Comment by danielshahaf** [comment]
Test added in 34df84a7dd88e55a629d90f644e021d995e1a616.

**Comment by danielshahaf** [comment]
`e() { eval ${(q)=EDITOR} "${(q)@}" }` is more robust against metacharacters in the value of $EDITOR. (However, I'm not at my workstation, so double-check my `${(q)=foo}`.)

**Comment by kbd** [comment]
Thanks for the shell tips! When I switched from bash years ago that 'open -t' alias stopped working, so I found the zsh option that made it behave more like bash there. I haven't run into any cases where that option causes unexpected behavior for me.

One more thing I should have mentioned initially but neglected to: this incorrect highlighting is new in version 0.7.0 or 0.7.1. When I updated Homebrew I was able to compare against shell sessions still open from the prior version and it didn't have this behavior.

**Comment by danielshahaf** [comment]
> I haven't run into any cases where that option causes unexpected behavior for me.

Well, SH_WORD_SPLIT is off by default, so I expect sooner or later you'll run into a code sample for native zsh that assumes that option is at its default value.

> One more thing I should have mentioned initially but neglected to: this incorrect highlighting is new in version 0.7.0 or 0.7.1. When I updated Homebrew I was able to compare against shell sessions still open from the prior version and it didn't have this behavior.

Thanks.  I've labelled this a regression, but I don't think there's much to be gained from bisecting this, since we already have an idea of the root cause: https://github.com/zsh-users/zsh-syntax-highlighting/issues/687#issuecomment-597744845.
