### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by sgarvett** [zsh-users/zsh-syntax-highlighting#715]
this might be a dumb equation, but I couldn't find it in the documentation. How does one uninstall the whole zsh-syntax-highlighting, I want to do a clean install of this. Thank you!

**Comment by danielshahaf** [comment]
You can run `zsh -o sourcetrace` to find where z-sy-h is installed.  Remove that directory, remove any reference to z-sy-h from your zshrc, then install the usual way:

https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md

**Comment by sgarvett** [comment]
> You can run `zsh -o sourcetrace` to find where z-sy-h is installed. Remove that directory, remove any reference to z-sy-h from your zshrc, then install the usual way:
> 
> https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md

Thank you @danielshahaf, I thought it was more complex than just removing the directory. I wasn't sure if it would mess anything up by doing it that way. Thanks again.

**Comment by danielshahaf** [comment]
Cheers :-)

**Comment by No0ne003** [comment]
i don't understand i want to remove it too

**Comment by danielshahaf** [comment]
> i don't understand i want to remove it too

So do the reverse of what you did to enable it.

Usually, there'll be an explicit reference to `zsh-syntax-highlighting` in one's .zshrc file (`${ZDOTDIR:-$HOME}/.zshrc`) that one can simply comment out.

If you've installed something (a suite of plugins, a VM, whatever) that enables z-sy-h implicitly, refer to the something's documentation.
