### ISSUE TITLE
Use of readonly builtin conflicts with POSIX_BUILTINS option

### ISSUE THREAD

**Issue by paxe** [zsh-users/zsh-syntax-highlighting#721]
I happen to be using POSIX_BUILTINS with zsh, and recently started seeing this error:
_zsh_highlight:3: read-only variable: ret

In reviewing docs, I see that readonly means typeset -gr when POSIX_BUILTINS is set, so please either:

- Replace the readonly declaration at the start of _zsh_highlight() by typeset -r
or
- Insert localoptions no_POSIX_BUILTINS at the front of _zsh_highlight().

I suppose a more all-encompassing solution could instead be the use of "emulate zsh".

**Comment by danielshahaf** [comment]
Already fixed in HEAD (see #719).

paxe wrote on Wed, 08 Apr 2020 17:52 -0700:
> I happen to be using POSIX_BUILTINS with zsh, and recently started seeing this error:
> _zsh_highlight:3: read-only variable: ret
> 
> In reviewing docs, I see that readonly means typeset -gr when POSIX_BUILTINS is set, so please either:
> 
> - Replace the readonly declaration at the start of _zsh_highlight() by typeset -r
> or
> - Insert localoptions no_POSIX_BUILTINS at the front of _zsh_highlight().
> 
> I suppose a more all-encompassing solution could instead be the use of "emulate zsh".
> 
>

**Comment by danielshahaf** [comment]
Closing as duplicate. If that's wrong, don't hesitate to reopen.
