### ISSUE TITLE
How to exclude certain prefixes (paths) from syntax highlighting?

### ISSUE THREAD

**Issue by zachriggle** [zsh-users/zsh-syntax-highlighting#724]
I have several network filesystems mounted on my machine, and zsh-syntax-highlighting does several tests on the path which incur very large delays when typing paths on the mount.

How can I configure highlighting to *not* try to investigate paths under a certain directory, or which start with a given prefix?

**Comment by danielshahaf** [comment]
https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/main.md#parameters

**Comment by zachriggle** [comment]
Thanks!  Not sure why I couldn't find this ❤️

**Comment by danielshahaf** [comment]
You're welcome. :)
