### ISSUE TITLE
X_ZSH_HIGHLIGHT_DIRS_BLACKLIST is deprecated

### ISSUE THREAD

**Issue by okerivy** [zsh-users/zsh-syntax-highlighting#725]
`zsh-syntax-highlighting: X_ZSH_HIGHLIGHT_DIRS_BLACKLIST is deprecated. Please use ZSH_HIGHLIGHT_DIRS_BLACKLIST.`

When I open the terminal, this warning appears
It was not there before, recently updated zsh-syntax-highlighting.

I don't know where I configured this `X_ZSH_HIGHLIGHT_DIRS_BLACKLIST`,
I have installed this tool before, but now it is only updated. `brew upgrade zsh-syntax-highlighting`
No other configuration
And this configuration is not in the **`.zshrc`** configuration file

Thank you

**Comment by okerivy** [comment]
ok solved

Put the configuration of `zsh-syntax-highlighting`  before this command `source $ZSH/oh-my-zsh.sh`

like this:
```
# zsh-syntax-highlighting
export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=$(brew --prefix)/share/zsh-syntax-highlighting/highlighters

# oh-my-zsh
source $ZSH/oh-my-zsh.sh
```

**Comment by danielshahaf** [comment]
1. You don't need to `export` that variable.
2. Setting `ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR` is a workaround, not a solution.  You should run `zsh -x` and see where that variable gets defined, even if that's not in your zshrc.
3. It seems you have two different installations of z-sy-h, and that they're both being activated somehow.  (You can use `zsh -o sourcetrace` to confirm this.)  You should probably disable one of the two installations, otherwise, you'll get much weirder errors if we ever change the interface between the entry point file and the highlighters.

Good luck. :)

**Comment by danielshahaf** [comment]
When I wrote "where that variable gets defined" I meant `X_ZSH_HIGHLIGHT_DIRS_BLACKLIST`.

**Comment by okerivy** [comment]
Thanks, (I use **`zsh -o sourcetrace`** to confirm this.) 
I found this code in **`.zshrc `**, and then deleted `zsh-syntax-highlighting` in  **`plugins`** , just fine, Thank you

I may have installed it twice, in two ways, one is a **plugin**, one is **brew install**

```
# Which pluginsecwould you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.

plugins=(
  # https://github.com/robbyrussell/oh-my-zsh/wiki/Plugin:git
  git
  zsh-syntax-highlighting
  autojump
  sublime
  #extract
  #web-search
  #zsh-autosuggestions
  #git-open
)
```


Becomes like this

```
# Which pluginsecwould you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.

plugins=(
  # https://github.com/robbyrussell/oh-my-zsh/wiki/Plugin:git
  git
  autojump
  sublime
)
```

**Comment by danielshahaf** [comment]
That should resolve the issues.  I think oh-my-zsh tracks the "bleeding edge" z-sy-h (i.e., the tip of the git `master` branch), whereas brew uses stable releases only, so pick whichever you prefer.  Cheers :)
