### ISSUE TITLE
Aliases not correctly highlighted anymore

### ISSUE THREAD

**Issue by BjoernDaase** [zsh-users/zsh-syntax-highlighting#726]
* Fedora 32
* Zsh-syntax-highlighting 0.7.1

I have tons of aliases for flatpak packages to make them somehow work from the command line, looking like this
`alias obs="flatpak run com.obsproject.Studio"`.

However, `obs` is now highlighted red instead of green. I somehow thought that worked in an earlier version...

**Comment by danielshahaf** [comment]
If you literally type `flatpak run com.obsproject.Studio` at the prompt, how is that highlighted?  What's the output of `which -a \flatpak`?  Could you please show the output of `typeset -p ZSH_VERSION ZSH_PATCHLEVEL`?  Can you reproduce the problem in `zsh -f` (followed by manually defining the aliases and running `source /path/to/zsh-syntax-highlighting.zsh`)?

**Comment by BjoernDaase** [comment]
Oh, seems like I missed one point. I also have the flatpak command aliased to `alias flatpak='flatpak_(){ flatpak "$@" && [[ "$1" = install || "$1" = remove ]] && ~/my_script.sh; }; flatpak_'` to execute a post install script.  

Without this extra flatpal alias the problem does not appear.

**Comment by danielshahaf** [comment]
First of all, your alias as written will break when used in SHORT_LOOPS contexts.  You should change it to use an anonymous function (`alias flatpak='() { flatpak "$@" && [[ "$1" = install || "$1" = remove ]] && ~/my_script.sh }`), or a real function (`flatpak() { command flatpak "$@" && [[ "$1" = install || "$1" = remove ]] && ~/my_script.sh; }`), or possibly `flatpak_() { flatpak "$@" && [[ "$1" = install || "$1" = remove ]] && ~/my_script.sh }; alias flatpak=flatpak_`.

I'm guessing that if you literally type `flatpak_(){ flatpak "$@" && [[ "$1" = install || "$1" = remove ]] && ~/my_script.sh; }; flatpak_`, at the prompt, at least one word in there is red — probably the first and third words.  The new behaviour is that whenever a word in the expansion of an alias would be highlighted in red, the alias itself gets highlighted in red.  Any one of the changes I recommended above for SHORT_LOOPS reasons would fix this issue as well.

**Comment by BjoernDaase** [comment]
Thanks a lot, `flatpak() { command flatpak "$@" && [[ "$1" = install || "$1" = remove ]] && ~/my_script.sh; }` does the thing!  
Learned something today, I did not know about short loops in zsh :)

**Comment by danielshahaf** [comment]
> Thanks a lot, `flatpak() { command flatpak "$@" && [[ "$1" = install || "$1" = remove ]] && ~/my_script.sh; }` does the thing!
>  Learned something today, I did not know about short loops in zsh :)

You're welcome.  Also, upon re-reading your function, I think you might want

flatpak() { command flatpak "$@" && if [[ "$1" = install || "$1" = remove ]] ; then ~/my_script.sh; fi }

The difference is the exit code of the function when the exit code of «command flatpak» is 0 but $1 isn't one of those two values.
