### ISSUE TITLE
_zsh_highlight_main_precmd_hook: unsetopt:2: no such option:  warnnestedvar

### ISSUE THREAD

**Issue by hao-lh** [zsh-users/zsh-syntax-highlighting#731]
Hi there,

Thanks for providing such an elegant plugin for community, really saves life for zsh users.
But recently I installed `zsh-syntax-highlighting` by strictly following install procedure in readme file and encountered following issue.

![zsh_highlight_issue](https://user-images.githubusercontent.com/14138581/81051586-8b646b80-8ef4-11ea-8611-d42a0a1881c3.jpg)

Installation command from Oh-my-zsh
`git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting`

And relevant configuration files in `~/.zshrc` file
```
plugins=(git 
	zsh-autosuggestions 
	zsh-syntax-highlighting 
	zsh-completions
	history-substring-search)

autoload -U compinit && compinit
source $ZSH/oh-my-zsh.sh
```

My running environment is OS X El Capitan 10.11.6, but it is fine on other machines running macOS Mojave 10.14.6.

Thank you again for your dedicated contribution for this plugin and help for looking at my issue.

**Comment by danielshahaf** [comment]
Thanks for the bug report and sorry for the breakage. This is a regression from yesterday's fix to #727. I'll commit a fix tonight. In the meantime, you can just comment the `unsetopt warnnestedvar` out on El Capitan. Let us know if you run into any further issues!

TODO's:

- [ ] Fix the bug
- [ ] See why Travis didn't catch it

**Comment by hao-lh** [comment]
@danielshahaf 

Hi man, thank you so much for your such quick responses.
Looking forward to your solution and I would test and feedback to you tomorrow :)

**Comment by jinfagang** [comment]
@danielshahaf  how to comment it out? I just got this issue too when install zsh-sytax-highlighting new.

**Comment by danielshahaf** [comment]
@jinfagang To comment out a line means to write a `#` in front of it, but forget about doing that; I just pushed a fix, it'll be easier to just z-sy-h to latest HEAD again.

@hao-lh @jinfagang Please reopen if needed.  Cheers!

**Comment by danielshahaf** [comment]
> TODO's:
> - [ ] See why Travis didn't catch it

Because the code runs in a `precmd` hook, and test suite doesn't run `precmd` hooks.  Normally I'd file a bug for this, but the cost/benefit of fixing it seems exceedingly high, given that `_zsh_highlight_main_precmd_hook` is the only precmd hook in z-sy-h, and it will become a trivial one-liner function once #688 is merged.  I'll keep an eye out for possible other benefits, though.

**Comment by hao-lh** [comment]
@danielshahaf @jinfagang 

Thank you so much for the quick response.
The updated version works perfect now on El Capitan 10.11.6.
