### ISSUE TITLE
When updating the plugin, there's no prompt

### ISSUE THREAD

**Issue by Moshem123** [zsh-users/zsh-syntax-highlighting#732]
It took me a hell of a long time to figure out there's something wrong with this plugin.
When pulling latest changes, all of a sudden, the prompt would disappear after 1 command.
Example:
![image](https://user-images.githubusercontent.com/17252601/81158982-2e6ac300-8f91-11ea-8bdf-9a98d622f46e.png)

After disabling every plugin and then re-enabling plugins one by one, I noticed that `zsh-syntax-highlighting` is messing up my prompt.

When reverting to commit `06710f37807ad9095e7e159e2215b1710368ca96`, every new prompt echoed:
```
_zsh_highlight_main__precmd_hook:unsetopt:2: no such option: warnnestedvar
```
only when going back to commit [f1b9fbbaf0123fb7b14b4a11bc18c86fd4b2305b](https://github.com/zsh-users/zsh-syntax-highlighting/commit/f1b9fbbaf0123fb7b14b4a11bc18c86fd4b2305b) the problem fully resolves.
I think issues first introduced on: [16d818a21f886ec61a9bdafd1722920863c65b1b](https://github.com/zsh-users/zsh-syntax-highlighting/commit/16d818a21f886ec61a9bdafd1722920863c65b1b)
Can you please help?
Thanks.

**Comment by danielshahaf** [comment]
Thanks for the bug report.

Please show the output of `typeset -p ZSH_VERSION ZSH_PATCHLEVEL ZSH_HIGHLIGHT_REVISION ZSH_HIGHLIGHT_VERSION`.  (Do not upload a screenshot; copy-paste it as text, so we can copy-paste the values on our side.)

Please [post instructions](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html#showmehow) that start with `zsh -f` and reproduce the bug.  (Once in `zsh -f`, you can run the command `source /path/to/zsh-syntax-highlighting.zsh`, replacing `/path/to` with the correct value, to load zsh-syntax-highlighting.)

The instructions should be minimal.  Run as few things as you can while still reproducing the bug.  In particular, do not source your entire `.zshrc`; run, interactively, only the particular commands you need.  Similarly, do not source an entire configuration framework (such as `oh-my-zsh.zsh`); instead run, manually, only the specific parts needed (e.g., `source /path/to/a/particular/plugin.zsh`).

Post the instructions (as text) once you have made them as minimal as you can.

Can you reproduce the problem in `zsh -x`?  If so, paste the output here (as text).  (The relevant part of the output is likely to be the part immediately after `_zsh_highlight_main_precmd_hook` is called.)

What's the output of `which -a precmd $precmd_functions` (sic)?

What's the output of `setopt` (without arguments)?

----

Does the following patch fix the problem?

```diff
diff --git a/highlighters/main/main-highlighter.zsh b/highlighters/main/main-highlighter.zsh
index e4a17e0..59d4036 100644
--- a/highlighters/main/main-highlighter.zsh
+++ b/highlighters/main/main-highlighter.zsh
@@ -1692,7 +1692,7 @@ _zsh_highlight_main__precmd_hook() {
   # Unset the WARN_NESTED_VAR option, taking care not to error if the option
   # doesn't exist (zsh older than zsh-5.3.1-test-2).
   setopt localoptions
-  if [[ -o warnnestedvar ]] 2>/dev/null; then
+  if eval '[[ -o warnnestedvar ]]' 2>/dev/null; then
     unsetopt warnnestedvar
   fi
 
```

**Comment by benchaikin** [comment]
> Thanks for the bug report.
> 
> Please show the output of `typeset -p ZSH_VERSION ZSH_PATCHLEVEL ZSH_HIGHLIGHT_REVISION ZSH_HIGHLIGHT_VERSION`. (Do not upload a screenshot; copy-paste it as text, so we can copy-paste the values on our side.)
> 
> Please [post instructions](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html#showmehow) that start with `zsh -f` and reproduce the bug. (Once in `zsh -f`, you can run the command `source /path/to/zsh-syntax-highlighting.zsh`, replacing `/path/to` with the correct value, to load zsh-syntax-highlighting.)
> 
> The instructions should be minimal. Run as few things as you can while still reproducing the bug. In particular, do not source your entire `.zshrc`; run, interactively, only the particular commands you need. Similarly, do not source an entire configuration framework (such as `oh-my-zsh.zsh`); instead run, manually, only the specific parts needed (e.g., `source /path/to/a/particular/plugin.zsh`).
> 
> Post the instructions (as text) once you have made them as minimal as you can.
> 
> Can you reproduce the problem in `zsh -x`? If so, paste the output here (as text). (The relevant part of the output is likely to be the part immediately after `_zsh_highlight_main_precmd_hook` is called.)
> 
> What's the output of `which -a precmd $precmd_functions` (sic)?
> 
> What's the output of `setopt` (without arguments)?
> 
> Does the following patch fix the problem?
> 
> ```diff
> diff --git a/highlighters/main/main-highlighter.zsh b/highlighters/main/main-highlighter.zsh
> index e4a17e0..59d4036 100644
> --- a/highlighters/main/main-highlighter.zsh
> +++ b/highlighters/main/main-highlighter.zsh
> @@ -1692,7 +1692,7 @@ _zsh_highlight_main__precmd_hook() {
>    # Unset the WARN_NESTED_VAR option, taking care not to error if the option
>    # doesn't exist (zsh older than zsh-5.3.1-test-2).
>    setopt localoptions
> -  if [[ -o warnnestedvar ]] 2>/dev/null; then
> +  if eval '[[ -o warnnestedvar ]]' 2>/dev/null; then
>      unsetopt warnnestedvar
>    fi
>  
> ```

This fixed the issue for me

**Comment by Moshem123** [comment]
issue was fixed for me as wel.
thanks.
