### ISSUE TITLE
precmd hooks registered after zsyh don't run

### ISSUE THREAD

**Issue by romkatv** [zsh-users/zsh-syntax-highlighting#733]
Culprit: https://github.com/zsh-users/zsh-syntax-highlighting/blob/e65ebf04663ed49c395b6747d74a163850c0221b/highlighters/main/main-highlighter.zsh#L1695

When this line of code executes in zsh 5.3.1, `_zsh_highlight_main__precmd_hook` terminates. Moreover, other precmd hooks don't run at all.

Here's a test case:

```zsh
() {
  emulate -L zsh -o err_return
  local zsyh
  zsyh="$(mktemp -d ${TMPDIR:-/tmp}/zsyh.XXXXXXXXXX)"
  {
    git clone --depth=1 -- https://github.com/zsh-users/zsh-syntax-highlighting.git $zsyh
    zsh -fis <<END
source $zsyh/zsh-syntax-highlighting.zsh
say_hello() { print hello }
precmd_functions+=(say_hello)
exit
END
  } always {
    rm -rf -- $tmp
  }
}
```

If `zsh` in this command is 5.3.1, you won't see "hello" in the output.

This works fine in zsh 5.8. I haven't tried other versions.

This came my way via https://github.com/romkatv/powerlevel10k/issues/693. Powerlevel10k, like many other themes, installs precmd hooks. When used together with zsyh in zsh 5.3.1, powerlevel10k doesn't work because its precmd hooks don't get called.

**Comment by danielshahaf** [comment]
Thanks, Roman!

**Comment by romkatv** [comment]
Thanks for the super speedy fix!
