### ISSUE TITLE
redrawhook: Effect on third-party plugins

### ISSUE THREAD

**Issue by danielshahaf** [zsh-users/zsh-syntax-highlighting#735]
@ericfreese points in https://github.com/zsh-users/zsh-autosuggestions/issues/529#issuecomment-632113840 that merging feature/redrawhook will break not only zsh-autosuggestions (#579) but possibly other plugins as well.

In a nutshell, suppose that with today's versions of everything (zsh, z-sy-h, and the third-party plugin) the third-party plugin wraps widgets and adds to region_highlight after z-sy-h runs.  Once z-sy-h begins to use redrawhook, z-sy-h's hook will run after the third-party widget wrapper, and without the proposed `region_highlight` `owner=` feature (https://github.com/zsh-users/zsh/pull/57) will trigger issue #418.

Brainstormed solutions include:

- Announce an upcoming breaking change before merging redrawhook
- Merge redrawhook but default it to disabled unless the `owner=` functionality is available
- Use dummy `region_highlight` entries (see next comment)

Between the two options listed thus far, I would vote for the second.  It's not ideal but it avoids breakage for users who also use third-party plugins until those upgrade to pre-redrawhook as well.

Does anyone see a third option?

**Comment by phy1729** [comment]
It's not pretty, but it's possible to add a noop highlight (e.g. `0 0 fg=17,bg=29`) into `region_highlight` to demark the start and end of z-sy-h controlled highlights (assuming other plugins prepend or append to the array and don't insert in the middle). Could be used as a fall back if owner= isn't available.

**Comment by danielshahaf** [comment]
Nice ☺

In addition to `fg=`, `bg=`, and the three booleans (`underline`, `standout`, `bold`), we can also set `start` and `end` to different random values such that `start >= end`.  `start` and `end` are at least 31 bits wide each, so using them would provide more than enough different values for as many plugins to use this trick as want to.

So, here are magic numbers for us:

```sh
% perl -E 'print map "$_ ", reverse sort { $a <=> $b } map { int rand (1<<31) } qw/start end/; print join ",", map { "$_=" . int rand (1<<8) } qw/fg bg/; say join "", map ",$_", grep { int rand 2 } qw/bold standout underline/'
1037776018 929459019 fg=100,bg=191,underline
```

However, I would prefer to start by implementing "If `memo=` (née `owner=`) is supported, use redrawhook, else use the incumbent code", then merge redrawhook, and implement the noop highlighting trick after merging (which would fix #418 for pre-`memo=` zsh).  Makes sense?

**Comment by phy1729** [comment]
Complete agreement on the plan. Just giving a fallback.

I kinda thought the 16 bits of fg and bg values would have been sufficient. I don't think there are even 256 region_highlight modifying zsh plugins much less 65 thousand.

**Comment by danielshahaf** [comment]
To a cryptographer, using an order of magnitude more bits of key space than conceivably required is second nature :P

But yeah, we can leave some of the bits as "reserved, must be set to zero". How about leaving `end` as zero?

(I suppose this is how the designers of IPv6's address space must've felt.)

**Comment by danielshahaf** [comment]
> Merge redrawhook but default it to disabled unless the `owner=` functionality is available

Implemented; see https://github.com/zsh-users/zsh-syntax-highlighting/issues/579#issuecomment-658358680.
