### ISSUE TITLE
zsh-syntax-highlighting breaks some Font Ligatures.

### ISSUE THREAD

**Issue by aaccioly** [zsh-users/zsh-syntax-highlighting#750]
Hi guys.

Looks like syntax-highlighting is conflicting with some font ligatures like `>=`. 
Others like `!=` are fine.

#### Syntax Highlighting Disabled
![Syntax Highlighting Disabled](https://imgur.com/zl0nrQ9.png)
#### Syntax Highlighting Enabled
![Syntax Highlighting Enabled](https://imgur.com/y0KukMR.png)

I think that this is a general issue, however, you can find relevant versions of what I have installed bellow (let me know if anything else is important to troubleshoot the issue).

### Versions

**Terminal Emulator:** Microsoft Windows Terminal 1.1.1812.0
**Shell:** zsh 5.6
**Font:** https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/JetBrainsMono (also verified with FiraCode)

**Comment by phy1729** [comment]
Does `echo test >=` show a greater-than-or-equal glyph? If so, does running the command echo test with the glyph or does it create a file `=` with the contents `test`?

**Comment by aaccioly** [comment]
The second. If I quote the string it interprets the glyph correctly:

![Echo Test](https://imgur.com/WYNZhre.png)

**Comment by phy1729** [comment]
In that case I think the behavior is correct as is.

**Comment by aaccioly** [comment]
Yeah, fair enough, we can call it a feature / not a bug.
It is  also parsing things like `((a >= b)) && echo $a || echo $b` correctly. 
Ultimately I think that is doing the right thing, even it feels a little bit weird.

**Comment by danielshahaf** [comment]
What if, say, the input is `: >>(:)` and the font has a ligature for `>>`?

The catch is that the two `>` signs are adjacent, part of different tokens, but can be configured to be highlighted identically, which might encourage the terminal emulator to consider them eligible for ligatures.
