### ISSUE TITLE
occassional occurred information from terminal

### ISSUE THREAD

**Issue by appleyuchi** [zsh-users/zsh-syntax-highlighting#752]
![问题](https://user-images.githubusercontent.com/27613483/87871570-ccdcc100-c9e3-11ea-868b-f210ec458a9a.png)

I often get the information in terminal:

build_prompt:1: scalar parameter RETVAL created globally in function build_prompt
build_prompt:2: scalar parameter segment created globally in function build_prompt

I don't know how to reproduce it 100%,it just occur occasionally.
Could anyone tell me what happened to my terminal?

A similar issue is found in https://github.com/zsh-users/zsh-syntax-highlighting/issues/438
but they are different

**Comment by danielshahaf** [comment]
And what makes you think this issue has anything to do with zsh-syntax-highlighting? There's no `build_prompt` function in zsh-syntax-highlighting. Looks like you should follow up with whoever wrote that function.

$funcfiletrace and friends may be helpful in tracking that one down.

The warning is generated by the warncreateglobal option.

**Comment by appleyuchi** [comment]
> And what makes you think this issue has anything to do with zsh-syntax-highlighting? There's no `build_prompt` function in zsh-syntax-highlighting. Looks like you should follow up with whoever wrote that function.
> 
> $funcfiletrace and friends may be helpful in tracking that one down.
> 
> The warning is generated by the warncreateglobal option.
I'm not sure,the reason why I post it here is that 
https://github.com/zsh-users/zsh-syntax-highlighting/issues/438 also has build_prompt....
sorry if I put it at the wrong place

**Comment by appleyuchi** [comment]
could you tell me where should I post it?
I'm weak in zsh,
 do you know how to fix it?
it's annoying,
Thanks for your help~!

**Comment by danielshahaf** [comment]
You should post this to whoever wrote `build_prompt`.

I don't know who that is. To find out, you can either grep your dotfiles, or set `PS4=%x:$PS4` and then the error message will include the filename.

**Comment by danielshahaf** [comment]
Actually, forget about PS4; it won't help here. My bad.

**Comment by danielshahaf** [comment]
Note to self: see about exposing a function definition's file:line coordinates via zsh/parameter. The info must be available already, because it's copied into the C funcstack struct at function calls.

**Comment by danielshahaf** [comment]
Ah, turns out that already exists.

@appleyuchi Run `print -r -- ${functions_source[build_prompt]}`.  That should print the name of the file that defines `build_prompt`.  Tell the author of that file their function isn't `WARN_CREATE_GLOBAL`-clean.  Good luck!

**Comment by appleyuchi** [comment]
Thanks for
 your help。。。。I have fixed for RETVAL 
but I can not fixed it for segment.
because segment is defined in a `for-loop`

**Comment by danielshahaf** [comment]
I'm afraid we can't help you with that.  The zsh-syntax-highlighting issue tracker is not a support forum for arbitrary issues involving arbitrary plugins.  Feel free to follow up with the third-party plugin maintainer — I see you've created an issue already (https://github.com/caiogondim/bullet-train.zsh/issues/326) — or with the zsh support forums (`#zsh` on Freenode and the `zsh-users@` list).  In the latter case, don't forget to link to the relevant source code.

Good luck!
