### ISSUE TITLE
Flashing on Ubuntu on Windows when typing fast

### ISSUE THREAD

**Issue by rekaerst** [zsh-users/zsh-syntax-highlighting#765]
![out5](https://user-images.githubusercontent.com/52642831/91025975-b0f4bc80-e62c-11ea-9666-2472bf6c0cc7.gif)

**Comment by danielshahaf** [comment]
> ![out5](https://user-images.githubusercontent.com/52642831/91025975-b0f4bc80-e62c-11ea-9666-2472bf6c0cc7.gif)

Well, I wonder what causes the redraw before the highlighting is finished.  That could be either some other plugin, or the `# Reset region_highlight to build it from scratch` block in z-sy-h.  So:

Can you reproduce this in `zsh -f` with no other plugins?

What's the output of `typeset -pm ZSH_VERSION ZSH_PATCHLEVEL ZSH_HIGHLIGHT_REVISION ZSH_HIGHLIGHT_VERSION`?

**Comment by rekaerst** [comment]
Sorry for bothering. I think this is an issue related to wslhost.exe and conhost.exe and after an update, the flashing disappeared.
Thanks for creating this wonderful plugin

**Comment by danielshahaf** [comment]
You're welcome, but creation credits go to @nicoulaj. Thanks for sharing the solution :-)
