### ISSUE TITLE
With this plugin enabled, source $ZSH/oh-my-zsh.sh multiple times makes zsh slow

### ISSUE THREAD

**Issue by lingsamuel** [zsh-users/zsh-syntax-highlighting#767]
If this plugin is enabled, `source $ZSH/oh-my-zsh.sh` (often `source ~/.zshrc`) multiple times makes zsh very very slow.

### Without z-sy-h:
```bash
plugins=(git colored-man-pages sublime z catimg wakatime  docker docker-compose zsh-autosuggestions)
```
![image](https://user-images.githubusercontent.com/14567045/92126161-69dba800-ee32-11ea-834a-6ee02c685d76.png)

Only takes a few seconds.

### With z-sy-h:
```bash
plugins=(zsh-syntax-highlighting)
```
![image](https://user-images.githubusercontent.com/14567045/92126441-c3dc6d80-ee32-11ea-840d-89affc4054d9.png)

Higher repeat times (~50) needs several minutes!

---

If I execute `source ~/.zshrc` with z-sy-h enabled several times, even the `Ctrl-C` needs a few seconds to response.

The only solution I found is exit the current zsh (or start a new one).

**Comment by danielshahaf** [comment]
See #625.

**Comment by lingsamuel** [comment]
There is no solution if I use `plugins` array instead of `source z-sy-h`?

**Comment by danielshahaf** [comment]
Which one you do doesn't affect the workarounds available to you: `exec zsh`, using the redrawhook codepath (what's the value of $ZSH_VERSION?), and patching the non-redrawhook codepath as explained on the other issue.
