### ISSUE TITLE
regex anchors and character classes in ZSH_HIGHLIGHT_REGEXP keys not matching

### ISSUE THREAD

**Issue by olets** [zsh-users/zsh-syntax-highlighting#768]
I'm not having success with ZSH_HIGHLIGHT_REGEXP keys that include `\s`, `\b`, `\n`, or `\w`. I haven't tried other anchors or character classes. I have tried escaping the `\` as `\\` with no success.

For example following https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/regexp.md:

```shell
typeset -A ZSH_HIGHLIGHT_REGEXP
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main regexp)
ZSH_HIGHLIGHT_REGEXP+=('\bmytest\b' fg=blue)
```

`mytest` never highlights.

My goal is two matches: words that are the single word in a no-trailing-whitespace buffer

```
ZSH_HIGHLIGHT_REGEXP+=('^[\s\n]*(one|two)$' fg=blue)
```

and words that are the last in a no-trailing-whitespace buffer

```
ZSH_HIGHLIGHT_REGEXP+=('\b(three|four)$' fg=red)
```

**Comment by phy1729** [comment]
You may be on a platform that uses `\<mytest\>` or `[[:<:]]mytest[[:>:]]` instead of `\bmytest\b`. For details see https://github.com/zsh-users/zsh-syntax-highlighting/pull/747

**Comment by olets** [comment]
That's it, thanks! I'm on macOS.

So 

```
ZSH_HIGHLIGHT_REGEXP+=('^[[:blank:]]*(one|two)$' fg=blue)
ZSH_HIGHLIGHT_REGEXP+=('[[:<:]](three|four)$' fg=red)
```

Do you happen to know what it would look like with GNU `libc`, or have a reference link? I'm searching and not finding anything good.

**Comment by danielshahaf** [comment]
One of these? —

https://manpages.debian.org/regex/7
https://manpages.debian.org/egrep

**Comment by olets** [comment]
Thanks 👍
