### ISSUE TITLE
Colourse command line options

### ISSUE THREAD

**Issue by jbouter** [zsh-users/zsh-syntax-highlighting#774]
I would very much like to colourise command line options (for example in dark grey). So, inside `df -h`, the `-h` would be dark grey. I am not able to find a way to achieve this, if this is at all possible. If someone could point me in the right direction, that'd be great.

**Comment by danielshahaf** [comment]
See the `main` Highlighter's documentation. E.g., `ZSH_HIGHLIGHT_STYLE[single-hyphen-option]=$ZSH_HIGHLIGHT_STYLE[comment]` at the end of your  `.zshrc`.

**Comment by jbouter** [comment]
Thanks! Your recommendation throws an error, but I'll be able to go forward from here. :-)

**Comment by jbouter** [comment]
For anyone interested in the future, I've added the following to `~/.zshrc`:

```console
typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=black,bold'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=black,bold'
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern line)
```
