### ISSUE TITLE
Aliasing a command starting with a variable isn't recognised

### ISSUE THREAD

**Issue by mohkale** [zsh-users/zsh-syntax-highlighting#783]
I've got an alias like this: `alias ta='$TMUX_HOME/cmds/attach-session'`. However zsh-syntax-highlighting marks it as an invalid command. Is there any way to get `zsh-syntax-highlighting` to recognise this without expanding the alias before assignment?

```
zsh-version: zsh 5.8 (x86_64-pc-linux-gnu)
zsh-syntax-highlighting: master@1715f39a4680a27abd57fc30c98a95fdf191be45
```

**Comment by phy1729** [comment]
The core of this issue is a duplicate of #484.

**Comment by mohkale** [comment]
@phy1729 

I see, thanks for directing me towards that issue.
