### ISSUE TITLE
How can i change a color of highlighting ?

### ISSUE THREAD

**Issue by peach-lasagna** [zsh-users/zsh-syntax-highlighting#787]
NOW:
![изображение](https://user-images.githubusercontent.com/59787538/101394312-e763f800-38fa-11eb-9c48-88e0f53d7aaa.png)
I want to see a dark green `showkey` command. How can i do it? I searched in docs , but didn't found it...

**Comment by danielshahaf** [comment]
https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/main.md

tl;dr: `ZSH_HIGHLIGHT_STYLES[command]='fg=green,bold'`

But note that some terminals take bold to imply bright (i.e., specifying "bold" changes both the stroke width and the colour).  This may be configurable in the terminal (e.g., `xterm +pc`).  You can easily test with `print -P -r -- '%F{green}%Bfoo%b%f'`.

**Comment by peach-lasagna** [comment]
Thx so much!
