### ISSUE TITLE
Intermittent slow _zsh_highlight

### ISSUE THREAD

**Issue by skunkworker** [zsh-users/zsh-syntax-highlighting#792]
Over the past week or two I've been experiencing an intermittent slowdown on zsh. After running zshprof when it was occurring, a lot of time is being spent in _zsh_highlight.

Link to zprof -> https://gist.github.com/skunkworker/44876be32c9c7d4aca5a2a6401c51681

I was experiencing this on the antibody latest version `0.7.0-beta2-dev`, then I cloned the repository and reproduced it on `0.8.0-alpha2-dev`.

Visually it produces a stutter every 7 to 10 characters, "catching up", then pausing again. The same terminal will not have issues for a minute or two then it will repeat.

Here is a link to a zprof where this is not occuring. https://gist.github.com/skunkworker/91df41d6a69e39a7f985d2c57be756bb

EDIT: I noticed my `zsh` was on `5.7.1` I updated it to `5.8` but the issue still persisted. zprof on 5.8 -> https://gist.github.com/skunkworker/cced708c84f6c201d46252628085bfba

**Comment by danielshahaf** [comment]
@skunkworker Hi, sorry for the delay.

> Over the past week or two I've been experiencing an intermittent slowdown on zsh.

What changed about two weeks before your post?

Your gist indicates you use some other plugins as well.  Does the problem occur in `zsh -f` with z-sy-h enabled and nothing else?

**Comment by skunkworker** [comment]
Closing due to issue going away after doing an `antibody update` on all of my zsh dependencies, I'm not sure which one it was.

**Comment by danielshahaf** [comment]
Thanks for the update.
