### ISSUE TITLE
How to remove underline padding to the width of the terminal?

### ISSUE THREAD

**Issue by EliabHdez** [zsh-users/zsh-syntax-highlighting#798]
Can anyone tell me how can I remove the underline in the paths/routes? I don't like this underline...
![subrayado zsh](https://user-images.githubusercontent.com/77374111/109438042-a48f5900-79ed-11eb-8b53-ffdfa0fbb600.JPG)

**Comment by danielshahaf** [comment]
First, note that only the pathname itself should be underlined.  The whitespace between the end of the path and the vertical line indicating the boundary between the two shell windows/panes should _not_ be underlined.  For example, see https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/images/preview.png, and note that the empty space after `txt` is _not_ underlined.

Thus, the fact that the stuff _after the end of the pathname_ is underlined might be some new bug, or an issue with your terminal emulator or with whatever you use for splitting windows (it looks like tmux?).

In any case, to answer your question as asked, see https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/main.md#how-to-tweak-it; the styles are called `path` and `path_prefix`.

And please take the time to write meaningful issue titles.  It does help.  Thanks!

**Comment by danielshahaf** [comment]
Please post the output of `typeset -p ZSH_VERSION ZSH_PATCHLEVEL ZSH_HIGHLIGHT_REVISION ZSH_HIGHLIGHT_VERSION TERM`.  (Do not upload a screenshot; copy-paste it as text, so we can copy-paste the values on our side.)

**Comment by danielshahaf** [comment]
Feedback timeout.
