### ISSUE TITLE
Crashes PyCharm's terminal functionality

### ISSUE THREAD

**Issue by jpuris** [zsh-users/zsh-syntax-highlighting#799]
Hi,

Very recently I've noticed that when this plugin in enabled, it will crash the terminal window available in IntelliJ's PyCharm Professional IDE.

Steps to reporduce
1. Install oh my zsh
2. Add `zsh-syntax-highlighting` to plugins to be loaded
3. Open PyCharm and navigate to terminal "widget?"
4. Type a letter

Expected:
Terminal window stays open and input is visible

Actual:
Terminal window closes (crashes?)

This seems to happen when the input is checked by the plugin. Unfortunately I have no idea how any of this works behind the basic functionality and do not know how to pull the logs on whats happening.

I'm hoping someone is able to reproduce the issue and / or hint on steps that would allow me to present some debug info on what may be causing this.

**Comment by danielshahaf** [comment]
Thanks for the bug report.

To save the error message, disable z-sy-h; open a terminal; within the terminal, type `zsh` at the prompt to launch a nested shell; within that shell, run `source /path/to/zsh-syntax-highlighting.zsh`; then type a letter.  The inner shell will exit, but the outer one won't.

Please post the output of `typeset -p ZSH_VERSION ZSH_PATCHLEVEL ZSH_HIGHLIGHT_REVISION ZSH_HIGHLIGHT_VERSION`.  (Do not upload a screenshot; copy-paste it as text, so we can copy-paste the values on our side.)

Please [post instructions](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html#showmehow) that start with `zsh -f` and reproduce the bug.  For minimality, don't source your entire .zshrc or oh-my-zsh in there.  Thanks!

**Comment by jpuris** [comment]
1. Disable the plugin in `~/.zshrc`
2. `source ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh`
3. Type in input to trigger a crash

**No crash.. it works and input is highlighted.**

If I start new terminal instance within PyCharm with the plugin enabled in `~/.zshrc`, the problem is immediately reproducible. 

I'm using ohmyzsh, last commit `9a9f3831925432fdf4352c24a002506a06d329c1`
With following plugins enabled
```shell
plugins=(
    iterm2
    zsh-autosuggestions
    kubectl
    zsh-syntax-highlighting
)
```

**Comment by jpuris** [comment]
Found the issue! This is caused by
```zsh
#### FIG ENV VARIABLES ####
[ -s ~/.fig/fig.sh ] && source ~/.fig/fig.sh
#### END FIG ENV VARIABLES ####
```

Which was added by https://withfig.com/
It now makes sense.. I will report this behaviour to fig team.

Thank you for the assist @danielshahaf

**Comment by jpuris** [comment]
Issue on Fig's repo https://github.com/withfig/fig/issues/38
