### ISSUE TITLE
Homebrew installation fails

### ISSUE THREAD

**Issue by lucian303** [zsh-users/zsh-syntax-highlighting#802]
Installed with homebrew. Added the below to zshrc. This no longer works. Output:

```
Last login: Tue Mar 16 11:43:16 on ttys003
[oh-my-zsh] plugin 'zsh-syntax-highlighting' not found
```

Yes, I added this to my .zshrc
```
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=/usr/local/share/zsh-syntax-highlighting/highlighters
```

**Comment by danielshahaf** [comment]
1. That variable needn't be `export`ed.

2. We can't provide support for issues that involve oh-my-zsh.

3. You seem to have installed zsh-syntax-highlighting twice: both via homebrew and via oh-my-zsh. Choose one. (If you keep both, it should still work, but twice as slow.)

4. Do commands that you input get syntax highlighted?

**Comment by lucian303** [comment]
I removed the plugin from the oh my zsh plugins list and the message went away while keeping the functionality so it's ok, I think.
