### ISSUE TITLE
How to change the highlighting color of commands like `cd` and `ls`

### ISSUE THREAD

**Issue by MohamedIrfanAM** [zsh-users/zsh-syntax-highlighting#804]

**Comment by MohamedIrfanAM** [comment]
https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/main.md
in which category ls and cd belongs

**Comment by MohamedIrfanAM** [comment]
Currently, it is in the default color `green`.

**Comment by danielshahaf** [comment]
For people finding this in the archives: See the `main` highlighter's documentation.
