### ISSUE TITLE
Cannot input anything after install highlighting plugin

### ISSUE THREAD

**Issue by stan9333** [zsh-users/zsh-syntax-highlighting#805]
My OS is CentOS6.3(64 bit) and I log in this machine whit relay

when i install highlighting plugin and run 'source ~/.zshrc'
I cannot input anything 
it shows '_zsh_highlight_main_highlighter_highlight_list:86: error in flags'
![image](https://user-images.githubusercontent.com/30831679/113402407-872c2100-93d7-11eb-97d8-484113985c04.png)

**Comment by danielshahaf** [comment]
First of all, if you're locked out, then `ssh machine sh` or `ssh machine zsh -f` should get you in.

**Comment by danielshahaf** [comment]
The line number and error message don't seem to agree. What's the values of `$ZSH_PATCHLEVEL` and `$ZSH_HIGHLIGHT_REVISION`?

**Comment by danielshahaf** [comment]
@danielshahaf The error message should be extended to show the string that failed to parse.

**Comment by stan9333** [comment]
Thx for reply!

'ssh machine zsh -f' works , I can get in my machine now. 
My $ZSH_PATCHLEVEL is '1.4705', $ZSH_HIGHLIGHT_REVISION shows nothing

**Comment by stan9333** [comment]
![image](https://user-images.githubusercontent.com/30831679/113412485-fa8b5e00-93ea-11eb-8553-a8228e535620.png)

@danielshahaf

**Comment by danielshahaf** [comment]
Sorry for the extra round trip, but what's `$ZSH_VERSION` please?

What's the contents of the files `.version` and `.revision-hash` in zsh-syntax-highlighting's directory?

**Comment by stan9333** [comment]
![image](https://user-images.githubusercontent.com/30831679/113420303-a8066d80-93fb-11eb-936b-f98d70464f98.png)

 `echo $ZSH_VERSION` return nothing

The contents of the files .version and .revision-hash as below

![image](https://user-images.githubusercontent.com/30831679/113421010-e81a2000-93fc-11eb-98c9-5990c9012dfb.png)

**Comment by danielshahaf** [comment]
> `echo $ZSH_VERSION` return nothing

That's broken. It's probably a bug in your dotfiles or in your vendor's package (not in zsh-syntax-highlighting).

> The contents of the files .version and .revision-hash as below

What's the output of `git status -s` and `git describe`?  Copy-paste it as text, **not**  as an image.

**Comment by stan9333** [comment]
> What's the output of `git status -s` and `git describe`? Copy-paste it as text, **not** as an image.

git command not found,but I am sure git command works before I install zsh-syntax-highlighting...

I have no idea what can I operate now,maybe I should remove zsh-syntax-highlighting compelety and see If can I get in my machine as usaual?

**Comment by stan9333** [comment]
By the way, I cannot use vi or vim now , It shows `output is not to a terminal`

**Comment by danielshahaf** [comment]
> @danielshahaf The error message should be extended to show the string that failed to parse.

Posted a patch upstream: https://www.zsh.org/workers/48379

**Comment by stan9333** [comment]
Ok, maybe I should reinstall my OS now. T.T
Since there is no way to quick fix

**Comment by danielshahaf** [comment]
> `echo $ZSH_VERSION` return nothing

> git command not found,but I am sure git command works before I install zsh-syntax-highlighting...

> By the way, I cannot use vi or vim now , It shows `output is not to a terminal`

I don't know what causes all this, but I don't think it has anything to do with zsh-syntax-highlighting.

> >  it shows `_zsh_highlight_main_highlighter_highlight_list:86: error in flags`
> The line number and error message don't seem to agree.

We haven't been able to determine what version of z-sy-h you use, but assuming you use anything from 2021, that line number refers to this line:

https://github.com/zsh-users/zsh-syntax-highlighting/blob/e8517244f7d2ae4f9d979faf94608d6e4a74a73e/highlighters/main/main-highlighter.zsh#L584

But that line can't generate that particular error message.

**Comment by stan9333** [comment]
Get it, thanks a lot ^_^

**Comment by danielshahaf** [comment]
> Ok, maybe I should reinstall my OS now. T.T

That's up to you.  If you do, you might want to save a copy of the current state for later forensics.

By the way, re-reading the above, I wonder why `vim` _doesn't_ fail with `command not found` like `git` does.  Usually `git` and `vim` are installed to the same directory in $PATH.

Good luck.

**Comment by sergiojunene** [comment]
To me after I install I decongest all the p10k and theme and everything, before installing perfect, but then I don’t know if it’s zsh-syntax problem or what

![Captura de pantalla 2021-04-03 a las 14 54 48](https://user-images.githubusercontent.com/22520811/113479052-e730cf00-948c-11eb-9f4d-9e368f702126.png)

**Comment by sergiojunene** [comment]
And a few days ago I had configured the iTerm2 super well, with the alt option key that went backwards from word to word and fast now nothing, a chaos in my current configuration

**Comment by danielshahaf** [comment]
You're running under `sh` as opposed to `zsh`.

**Comment by sergiojunene** [comment]
@danielshahaf IDK what you mean, I've installed `zsh terminal` and work with `ohmyzsh` and some plugins have given me problems because now with hyper I happen the same thing

![Captura de pantalla 2021-04-03 a las 17 54 38](https://user-images.githubusercontent.com/22520811/113570910-98627100-9615-11eb-9c11-3836aa58abbb.png)
![Captura de pantalla 2021-04-03 a las 23 53 45](https://user-images.githubusercontent.com/22520811/113570919-99939e00-9615-11eb-8362-e9939754b437.png)

**Comment by danielshahaf** [comment]
I was referring to the first three lines of the screenshot in your first reply.

Anyway, your problems are not related to zsh-syntax-highlighting, and in any case we don't provide support for issues that involve oh-my-zsh. Follow up with an appropriate source of technical support.

For future reference, don't take over unrelated issues/threads, and don't post images where text would do.

Closing as both @stan9333's issue and @sergiojunene's issue require no changes on zsh-syntax-highlighting's side.

**Comment by wasPrime** [comment]
> My OS is CentOS6.3(64 bit) and I log in this machine whit relay
> 
> when i install highlighting plugin and run 'source ~/.zshrc' I cannot input anything it shows '_zsh_highlight_main_highlighter_highlight_list:86: error in flags' ![image](https://user-images.githubusercontent.com/30831679/113402407-872c2100-93d7-11eb-97d8-484113985c04.png)

Hi! I have also encountered this problem that shows '_zsh_highlight_main_highlighter_highlight_list:87: error in flags'. Although the line number isn't match exactly, I guess it's the same problem(maybe just the version of zsh-syntax-highlighting I use adds a line before the error line).

**Comment by danielshahaf** [comment]
@wasPrime Thanks for the information! 4.3.10 isn't recent, but we'll accept patches, or fix it ourselves if we have time.  Feel free to open a new issue so this isn't lost (this issue is overloaded).

**Comment by wasPrime** [comment]
> @wasPrime Thanks for the information! 4.3.10 isn't recent, but we'll accept patches, or fix it ourselves if we have time. Feel free to open a new issue so this isn't lost (this issue is overloaded).

The issue I proposed is here(<https://github.com/zsh-users/zsh-syntax-highlighting/issues/842>). Thanks for the support!
