### ISSUE TITLE
https://pygments.org/demo/ is not working anymore.

### ISSUE THREAD

**Issue by apdaga** [zsh-users/zsh-syntax-highlighting#809]
Whenever I visit https://pygments.org/demo/ these days it takes a very long time and keeps on loading. That was not the case earlier. Please resolve the issue if possible.

Thanks,

![image](https://user-images.githubusercontent.com/39180163/114707967-728d4880-9d48-11eb-985d-27db43d9fbe4.png)

**Comment by phy1729** [comment]
zsh-syntax-highlighting is not related to that site. You'll need to report the issue elsewhere.
