### ISSUE TITLE
Highlighting may not be working correctly in iTerm?

### ISSUE THREAD

**Issue by ericboxer** [zsh-users/zsh-syntax-highlighting#810]
It appears that highlighting may not be working in iTerm2 (macOS) correctly. I have zsh installed from Homebrew.

<img width="650" alt="Screen Shot 2021-04-25 at 12 10 41 PM" src="https://user-images.githubusercontent.com/209360/116000680-429f3a00-a5bf-11eb-8c42-6a764ebdf6f0.png">

Even using standard commands the highlighter shows incomplete commands as red, but once a command is completed it does not show up as green as expected.
<img width="650" alt="Screen Shot 2021-04-25 at 12 14 27 PM" src="https://user-images.githubusercontent.com/209360/116000829-c9541700-a5bf-11eb-8d0c-fb86715944cb.png">
<img width="650" alt="Screen Shot 2021-04-25 at 12 14 38 PM" src="https://user-images.githubusercontent.com/209360/116000833-d07b2500-a5bf-11eb-9ae8-9597a25ecc3a.png">

I would normally chalk this up to user error, however, the standard terminal in macOS and the integrated terminal in VSCode seem to function as expected.

<img width="565" alt="Screen Shot 2021-04-25 at 12 15 54 PM" src="https://user-images.githubusercontent.com/209360/116000878-fc96a600-a5bf-11eb-8899-30fdeadf5a42.png">
<img width="1427" alt="Screen Shot 2021-04-25 at 12 16 39 PM" src="https://user-images.githubusercontent.com/209360/116000915-1932de00-a5c0-11eb-858a-304a02c64de3.png">

Even removing any theming, any other addons (really only autosuggest), and basically an empty .zshrc doesn't seem to solve the issue.

Any thoughts on getting this to work correctly?

**Comment by ericboxer** [comment]
Closed to (what i originally suspected) was a user error.

**Comment by danielshahaf** [comment]
What was the solution?

**Comment by ericboxer** [comment]
A long time ago I apparently overwrite the colors used in iTerm. Didn't even think to look there. Researching now how to set the colors from their scripting interface.
