### ISSUE TITLE
Directory names are only errors after issuing command, even if `AUTO_CD` is unset

### ISSUE THREAD

**Issue by Mathspy** [zsh-users/zsh-syntax-highlighting#813]
I am not entirely sure if this is a bug or me misunderstanding how to configure zsh-syntax-highlighting properly, sorry about that!
So I have `AUTO_CD` unset, attempting to write a directory name does indeed result in
```
zsh: command not found: mno
```
but the syntax highlighting _while_ writing the directory acts in a rather interesting way.

So in a directory with only one directory inside of it: `mno` (chosen for lack of `m` or `mn` or `mno` binaries in my PATH, but you should be able to just reproduce with `abc` if you don't have `ab` installed for example)
```sh
$ ls
mno
```
If one was to type `z` (or any other letter), they'd get a red (error) `z` as expected. But if they were to write `m`, it instead has no highlighting (default white), typing `n` after it would still result in no highlighting (unless there is a binary `mn` in PATH, in which case it's green) and typing `mno` has no highlighting (unless there is a binary `mno` in PATH, in which case it's green). After clicking "Enter/Return" though the result corrects itself and the history can be seen with a red `mno`

Demonstration:
![z error](https://user-images.githubusercontent.com/5855663/120061467-af45a280-c05d-11eb-9abe-f2c969e2a857.png)
---
![m not error](https://user-images.githubusercontent.com/5855663/120061300-e23b6680-c05c-11eb-9b3a-03e56b60e95f.png)
---
![mn not error](https://user-images.githubusercontent.com/5855663/120061302-e49dc080-c05c-11eb-92d7-585cf1c9b66c.png)
---
![mno not error](https://user-images.githubusercontent.com/5855663/120061304-e5365700-c05c-11eb-9aff-53c0da3ef3e5.png)
---
![mno error after return](https://user-images.githubusercontent.com/5855663/120061307-e5ceed80-c05c-11eb-9b2f-0c4bb97fdf5a.png)

This is using latest master branch (https://github.com/zsh-users/zsh-syntax-highlighting/commit/894127b221ab73847847bf7cf31eeb709bc16dc5)

I am really not sure if this is the expected behavior or not.
Also thank you for your hard work on this lovely utility, makes using zsh such a pleasure ❤️

**Comment by Mathspy** [comment]
Also I think this might be related to https://github.com/zsh-users/zsh-syntax-highlighting/issues/755 but I didn't wanna comment on an already closed issue

**Comment by danielshahaf** [comment]
Thanks for the detailed write-up!

It's working as expected. With `mno<CURSOR>`, the `mno` is white because it's potentially a prefix of a command such as `mno/bin/foo`. After accepting the line, the `mno` is red because it's in command position and not a command/function/alias/autocdable/etc.. Makes sense?

Excuse brevity.

**Comment by danielshahaf** [comment]
Yeah, numbers are cheap. When in doubt, split :-)

**Comment by Mathspy** [comment]
> Thanks for the detailed write-up!
> 
> It's working as expected. With `mno<CURSOR>`, the `mno` is white because it's potentially a prefix of a command such as `mno/bin/foo`. After accepting the line, the `mno` is red because it's in command position and not a command/function/alias/autocdable/etc.. Makes sense?
> 
> Excuse brevity.

Oh! Right! I kinda completely forgot that since I tend to use non-PATH binaries with a preceding `./`, that makes sense though! Sorry for trouble and thank you!

**Comment by danielshahaf** [comment]
You're welcome!
