### ISSUE TITLE
Highlighting is not working as you type

### ISSUE THREAD

**Issue by chris542** [zsh-users/zsh-syntax-highlighting#815]
I had installed zsh-syntax-highlighting using oh-my-zsh plugin method, and I just migrated to using 'zplug' so that i can get the latest version easily.

After updating the plugin my highlight isnt working as it used to.

e.g.
When you type `vim` it used to highlight it as green. But now it stays white until i insert a whitespace by pressing space.
It used to highlight `vim` as green when my cursor is after `m` but now it needs another extra step to see if this is a valid command.

Is there an option to use as-you-type syntax checker to get what i used to have?

Thanks!

**Comment by danielshahaf** [comment]
"As-you-type" behaviour is the only one shipped. Some other plugin might be interfering.
