### ISSUE TITLE
Parameter parsing does not honor SH_WORD_SPLIT

### ISSUE THREAD

**Issue by akhiljalagam** [zsh-users/zsh-syntax-highlighting#818]
![image](https://user-images.githubusercontent.com/21128035/123514370-57c44200-d6b0-11eb-855b-32eb1e23b5a2.png)
but that aws_head command works fine.

**Comment by phy1729** [comment]
In general that's correct as zsh will error with `zsh: command not found: aws --profile foo --output --text`. However, I presume you have shwordsplit set which the parameter parsing code doesn't yet know about. The easy solutions are use a function, or an alias, or an array; but we should handle shwordsplit as well.

**Comment by phy1729** [comment]
Fixed in f0e6a8e (seems I should have repeated the closes magic word).

**Comment by danielshahaf** [comment]
Thanks!
