### ISSUE TITLE
How to remove underscore from syntax highlighting?

### ISSUE THREAD

**Issue by CleanMachine1** [zsh-users/zsh-syntax-highlighting#821]
Hi, 
just started with ZSH and need a little help, I have looked in your documentation and cannot see anything to reference what I need. Also looked at old issues, to see if anyone else has raised this question.

So when typing commands such as `sudo`, it gets underscored.

How do I turn that off, all I want is mainly syntax color highlights.

OS = Arch (btw)
Installed by =  sudo pacman -S zsh-syntax-highlighting

**Comment by danielshahaf** [comment]
Set `ZSH_HIGHLIGHT_STYLES[foo]=none` for appropriate values of `foo`, such as:

- `path`
- `path_prefix`
- `arg0`

**Comment by CleanMachine1** [comment]
I've tried putting that in .zshrc and a plugin folder in `/usr/share/zsh/plugins/zsh-syntax-highlighting`

But it seems to mess up with powerlevel10k

**Comment by danielshahaf** [comment]
That's not enough information. What's the problem and how may it be reproduced?

**Comment by CleanMachine1** [comment]
Closing since I have since just gotten used to it.

Thanks for the help provided regardless.

Have a good day!
