### ISSUE TITLE
All custom aliases removed

### ISSUE THREAD

**Issue by bagnaram** [zsh-users/zsh-syntax-highlighting#823]
https://github.com/zsh-users/zsh-syntax-highlighting/blob/dffe304567c86f06bf1be0fce200077504e79783/zsh-syntax-highlighting.zsh#L36

This line appears to be resetting all custom aliases I have set on my system. This is problematic because I enable/disable this plugin asynchronously doring my terminal sessions

This command should be something like `unalias -m '^+.*'`

**Comment by bagnaram** [comment]
Created https://github.com/zsh-users/zsh-syntax-highlighting/pull/824

**Comment by phy1729** [comment]
Aliases are (normally) restored later
https://github.com/zsh-users/zsh-syntax-highlighting/blob/dffe304567c86f06bf1be0fce200077504e79783/zsh-syntax-highlighting.zsh#L593

Most aliases can make the round trip unchanged. Aliases starting with `+` are subject to a bug in some version of zsh, so are excluded from being unset. Perhaps see if any of your aliases are using odd characters which have a similar issue.

**Comment by bagnaram** [comment]
I figured out that the issue is that the alias is being lost by my package manager, zinit.

**Comment by bagnaram** [comment]
https://github.com/zdharma/zinit/issues/530 for  reference
