### ISSUE TITLE
Add instructions on sourcing from distro package installation

### ISSUE THREAD

**Issue by Mario-paul** [zsh-users/zsh-syntax-highlighting#828]
Installed using the "Using packages" install how-to section for Ubuntu, but syntax highlighting does not work. .zshrc file obviously does not have sourcing information, and after trying all of the "source" lines from the INSTALL.md, it still doesn't work. clearly zsh-syntax-highlighting is installed somewhere different than the git installations, and those source lines won't work for the Ubuntu repo install.

Am I missing something? And if not, can the "Using packages" section be completed or cleared up?

Thanks

**Comment by danielshahaf** [comment]
You're right, we should spell that out.

In your case, see /usr/share/doc/zsh-syntax-highlighting/README.Debian.gz or `dpkg -L zsh-syntax-highlighting` for the path to zsh-syntax-highlighting.zsh.

Leaving this open to track the documentation change. If you'd like to propose new language for INSTALL.md, that'd be great :-)

**Comment by Mario-paul** [comment]
Hey Daniel, using your help I got it working using the Ubuntu package install. I noticed the Ubuntu package for my distro base (20.04) is extremely outdated though (0.6.0) so I'm just gonna install the latest github version using the oh-my-zsh plugin way lol.

As requested, I added the instructions to source .zshrc file on debian/based package installs on INSTALL.md file. Hope that looks good, otherwise you are free to edit my changes as you like.

**Comment by danielshahaf** [comment]
Thanks! We'll review the PR when we have a moment. (And the next release milestone issues list too, so recent work will reach distro users too...)

**Comment by Mario-paul** [comment]
> Thanks! We'll review the PR when we have a moment. (And the next release milestone issues list too, so recent work will reach distro users too...)

Other than some Cinnamon themes, this is my first real contribution to a Linux project. How exciting! :)

**Comment by danielshahaf** [comment]
Oh, congratulations!  I still remember my first few patches.  Even that day when I reported a typo on IRC and @lgov (hi!) committed it upon the spot with "Patch by:" credit…

**Comment by jnishwanth** [comment]
So this issue should be closed now? Or is there any help needed?

**Comment by phy1729** [comment]
#830 is morally merged in 6507190.
