### ISSUE TITLE
Trigger highlighting form a script

### ISSUE THREAD

**Issue by typkrft** [zsh-users/zsh-syntax-highlighting#829]
This may be an odd scenario, but I've got a script (an fzf powered cheatsheet) that writes output to the prompt using print -z eg: `print -z -- $(printf "printf \"hello, world\"")`. Unfortunately when it prints to the command line the output does not have any highlighting, moving the cursor will trigger it, but I was wonder if there is another way something automatic. I've tried emulating cursor movement with tput to no avail. It's not a huge deal, but I thought I'd ask. Thanks!

**Comment by danielshahaf** [comment]
Looks like this behaves the way you want on the redrawhook codepath.  Try enabling it manually by editing the condition in the source, here:

https://github.com/zsh-users/zsh-syntax-highlighting/blob/dffe304567c86f06bf1be0fce200077504e79783/zsh-syntax-highlighting.zsh#L400-L417

**Comment by typkrft** [comment]
I'm sorry, but I'm not really understanding what you mean. What should I try to enable?

**Comment by danielshahaf** [comment]
> I'm sorry, but I'm not really understanding what you mean. What should 
> I try to enable?

At the line I linked (417), change "5.8.0.2" to "5.3".

What's the output of `typeset -p ZSH_VERSION ZSH_PATCHLEVEL`?

**Comment by typkrft** [comment]
That did the trick. Thank you!

$ `typeset -p ZSH_VERSION ZSH_PATCHLEVEL`
```Shell
typeset ZSH_VERSION=5.8
typeset ZSH_PATCHLEVEL=zsh-5.8-0-g77d203f
```

**Comment by danielshahaf** [comment]
You're welcome. That codepath is on by default when running under the next zsh release, so it seems there's nothing else to do here.
