### ISSUE TITLE
Change colors?

### ISSUE THREAD

**Issue by AndreKucharzyk** [zsh-users/zsh-syntax-highlighting#841]
Is there a way to change the colours of highlighting? My current colors are not that pleasing.

![Colors](https://user-images.githubusercontent.com/31192782/139413743-e735e549-d0ef-4780-a51d-7c1c89a61ff2.jpg)

**Comment by Waxxx333** [comment]
I did this: 
`cd zsh-syntax-highlighting && find . -type f -exec sed -i 's/green/blue/g' {} \;
`
Obviously change "blue" to your desired color. You can use hex  colors too: 
```find . -type f -exec sed -i 's/green/"#FF6329"/g' {} \;```

**Comment by danielshahaf** [comment]
See the documentation about ZSH_HIGHLIGHT_STYLES, and your terminal emulator's color palette.

**Comment by polatouche6** [comment]
there are some config about ZSH_HIGHLIGHT_STYLES  in`zsh-syntax-highlighting/highlighters/main/main-highlighter.zsh`.  you can set it in `~/.zshrc`  to change color.
such as change `ZSH_HIGHLIGHT_STYLES[arg0]`
```
ZSH_HIGHLIGHT_STYLES[arg0]='fg=yello'
```

> I did this: `cd zsh-syntax-highlighting && find . -type f -exec sed -i 's/\<green\>/blue/g' {} \; ` Obviously change "blue" to your desired color. You can use hex colors too: `find . -type f -exec sed -i 's/\<green\>/"#FF6329"/g' {} \;`

**Comment by danielshahaf** [comment]
Yeah, that's right.  Again, see the documentation for details.
