### ISSUE TITLE
Question: I was wondering how to disable on demand

### ISSUE THREAD

**Issue by ayroblu** [zsh-users/zsh-syntax-highlighting#844]
Hi I'm not sure if this is documented somewhere sorry if I missed it
I want to disable syntax highlighting on demand

Currently I have this, but it doesn't disable it on my current prompt, I was wondering if there's a command I could do to disable it on my current prompt as well

```zsh
disable-plugin() {
  ZSH_HIGHLIGHT_MAXLENGTH=0
}
zle -N disable-plugin
bindkey '^K' disable-plugin
```

e.g. I want syntax highlighting to stop if I do this for example:

```sh
$ my slow command ^K
```

The version I have checked out is: 1a9264b

**Comment by danielshahaf** [comment]
What functionality are you looking for?  Disable until explicitly enabled?  Disable just for the command currently being entered?  Always disable for "my slow command"?

For your ad-hoc disabling you probably want to set `region_highlight=()` as well to delete the highlighting that has already been computed.

**Comment by ayroblu** [comment]
Perfect! Thanks!

```zsh
disable-zsh-syntax-highlighting() {
  ZSH_HIGHLIGHT_MAXLENGTH=0
  region_highlight=()
}
```

**Comment by danielshahaf** [comment]
You're welcome.

For posterity:

1. The above solution disables highlighting until the value of `$ZSH_HIGHLIGHT_MAXLENGTH` is changed (or unset).
2. Emptying `$region_highlight` will also delete any highlighting entries by other plugins that are present at that point in time.  In zsh 5.9 you will be able to delete only z-sy-h's entries by doing `region_highlight=( "${region_highlight[@]:#*memo=zsh-syntax-highlighting}" )`.  (The code for this is already implemented in zsh master and z-sy-h master.)
