### ISSUE TITLE
[help needed] Is it possible to change the colours of syntax highlighting?

### ISSUE THREAD

**Issue by p0pcat** [zsh-users/zsh-syntax-highlighting#848]
Is it possible to change the colours of syntax highlighting? I have installed zsh-syntax-highlighting using homebrew.

**Comment by p0pcat** [comment]
never mind, everything can be found

**Comment by danielshahaf** [comment]
> Is it possible to change the colours of syntax highlighting?

Yes. grep for "ZSH_HIGHLIGHT_STYLES".
