### ISSUE TITLE
Upgraded from centos7 to almalinux8 and now zsh plugins won't work

### ISSUE THREAD

**Issue by josaladino2** [zsh-users/zsh-syntax-highlighting#849]
I'm wondering if you have had issues with almalinux8 and oh-my-zsh plugins?  many of them are not working for me any longer.  Also did a new install putting a shared directory in /etc/oh-my-zsh and it seems to load ok, $plugins shows plugins loaded but they don't work.  I also use Powerlevel10k as theme.  Can you give me any help?
Thanks

**Comment by danielshahaf** [comment]
No, because your issue does not involve zsh-syntax-highlighting.  Recommend that you figure out a minimal reproduction recipe (bisect your dotfiles or use `zsh -f`) and then post a specific question to an appropriate support channel.  Sorry your ticket slipped through the cracks, and good luck!
