### ISSUE TITLE
_zsh_autosuggest_highlight_reset:3: maximum nested function level reached; increase FUNCNEST?

### ISSUE THREAD

**Issue by annata83** [zsh-users/zsh-syntax-highlighting#850]
Hello there, this is annoying and don't how to fix it...

`
_zsh_autosuggest_highlight_reset:3: maximum nested function level reached; increase FUNCNEST?
`
zsh 5.8
zplugin to load this.

**Comment by phy1729** [comment]
Appears to be similar to https://github.com/zimfw/zimfw/issues/449 which points to a bug in kitty.

**Comment by annata83** [comment]
Yeah, That's correct; is a Kitty Bug like you  said.
Thank you and sorry to bother.

**Comment by danielshahaf** [comment]
> Appears to be similar to [zimfw/zimfw#449](https://github.com/zimfw/zimfw/issues/449) which points to a bug in kitty.

Wow.  Good catch, but how'd you find this out?

**Comment by phy1729** [comment]
Luck. Didn't look like one of our error messages, but has autosuggest in the function name so searched zsh-asug issues for FUNCNEST and the only result there `https://github.com/zsh-users/zsh-autosuggestions/issues/187` happened to be linked to by the zimfw issue. (Link quoted to prevent spurious github crosslinking.)

**Comment by danielshahaf** [comment]
Hats off :-)

**Comment by thearticulate-edboard** [comment]
Getting same error in alacritty
