### ISSUE TITLE
[Question] Does this feature respect the terminal's color scheme?

### ISSUE THREAD

**Issue by Pound-Hash** [zsh-users/zsh-syntax-highlighting#861]
I don't see anything in the `README` about this. Some `zsh` features use external color schemes. I'm colorblind and need to use the color scheme I've created for my terminal.

**Comment by danielshahaf** [comment]
What's "this feature"?

**Comment by danielshahaf** [comment]
The default ZSH_HIGHLIGHT_STYLES values use only the standard 16 colours.

**Comment by Pound-Hash** [comment]
> What's "this feature"?

Bat, for example, uses its own schemes.

**Comment by danielshahaf** [comment]
Closing as the OP has acknowledged the answer.  If you have further questions feel free to ask them.

**Comment by Pound-Hash** [comment]
> What's "this feature"?

zsh-syntax-highlighting

As a feature, it enjoys all the benefits of being five syllables short of its more welcome and respectable namesake. And all the more easy and effortless as well. For ease of flow, five syllables can go.

**Comment by danielshahaf** [comment]
zsh-syntax-highlighting is not a feature.  If you need a shorthand, "this project", "this plugin", and "z-sy-h" will all be widely understood.
