### ISSUE TITLE
How to change the color of directories in the output of "ls" command?

### ISSUE THREAD

**Issue by Alecton4** [zsh-users/zsh-syntax-highlighting#864]
Hello devs! First, this is the output, directories are colored in dark blue which is really hard to read:

![image](https://user-images.githubusercontent.com/43232804/157236489-0994a3b0-c4ae-4613-af7d-01ecef44134b.png)

I tried to change the "ansiBlue" color in VSCode integrated terminal, but this only affects the line where the first arrow points to in the above screenshot, which is ```Oh My Zsh is already at the latest version.```.
I have also tried to put ```ZSH_HIGHLIGHT_STYLES[autodirectory]=fg=blue``` in my ```.zshrc```, but it also won't work.
Thanks.

**Comment by danielshahaf** [comment]
This project deals with colouring the text you type at the prompt, and only that.  We don't deal with colouring ls(1) output and don't know who does.  Good luck.
