### ISSUE TITLE
Please add a highlighter for flags (like powershell)

### ISSUE THREAD

**Issue by ghost** [zsh-users/zsh-syntax-highlighting#866]
### New Feature/Highlighter

Hi,

This is just a humble request to add a highlighter for flags which start with "-" or "--", just like powershell does.

[![image](https://user-images.githubusercontent.com/90166733/161026764-4c9a9296-1e6a-4707-b43c-b212040249c4.png)](https://www.brianjgraf.com/powershell-pubg-module/2019-03-31-23_18_08-windows-powershell/)

Also, a highlighter for integers would be nice but it isn't that important :)
Or can I create one myself? If yes, how?

**Comment by phy1729** [comment]
The styles for the main highlighter are documented at https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/main.md#how-to-tweak-it ; in particular there's `single-hyphen-option` and `double-hyphen-option`. For grey as in the screenshot you'd want `ZSH_HIGHLIGHT_STYLES[single-hyphen-option]=fg=8` and `ZSH_HIGHLIGHT_STYLES[double-hyphen-option]=fg=8`.

**Comment by NotYasho** [comment]
@phy1729 Thanks, that helps!
