### ISSUE TITLE
syntax highlighting seems to clash with zsh-autosuggestions

### ISSUE THREAD

**Issue by EigenDev** [zsh-users/zsh-syntax-highlighting#867]
Hello,

This wasn't an issue until maybe two months ago, but I noticed that when typing a command, the entire history of the command will appear white even though I have not pressed the →key. When I comment out the zsh-syntax-highlighting from the plugins in .zshrc, the auto suggestions work as expected where the suggested command remains grey as I continue typing it out.  I've attached two images to show what I mean. 

Expected behavior (syntax-highlighting turned off):
![Selection_024](https://user-images.githubusercontent.com/29236993/161814665-d5bb873a-cb14-4c61-a1e7-19267071ad30.png)

Actual behavior (syntax-highlighting turned on):
![Selection_023](https://user-images.githubusercontent.com/29236993/161814680-3252c2ad-6834-45cd-bf9d-0794cc3ef537.png)

Any help/suggestions would be greatly appreciated!

**Comment by danielshahaf** [comment]
Please update to latest z-sy-h master.  (I'm guessing you're both on non-latest z-sy-h but on zsh 5.8.1, in which case you are probably seeing #857.)

**Comment by EigenDev** [comment]
Thank you! Upgrading solved the issue. Closing now
