### ISSUE TITLE
Auto cd'ing of directories in CDPATH not properly colored

### ISSUE THREAD

**Issue by sfauzia** [zsh-users/zsh-syntax-highlighting#88]
If I auto cd (via setopt auto_cd) into a directory in my CDPATH, the directory name is colored red, the same color used for non-legit commands. Subdirectories of the current directory, on the other hand, are colored normally when auto cd'd into.

Thanks in advance for looking into this.

**Comment by danielshahaf** [comment]
> If I auto cd (via setopt auto_cd) into a directory in my CDPATH, the directory name is colored red, the same color used for non-legit commands. Subdirectories of the current directory, on the other hand, are colored normally when auto cd'd into.

Right now, both cases are highlighted by an underline (the same as "existing files"). Since that's not red, I'm assuming the issue has been fixed. Feel free to reopen if further changes are needed.
