### ISSUE TITLE
Highlighting missing from vi / nano etc

### ISSUE THREAD

**Issue by marcpaskell** [zsh-users/zsh-syntax-highlighting#886]
Hi - recently moved over to zsh, installed ohmyzsh and wanted to add the highlighting plugin. 

Followed the install instructions and the plugin seems to be installed, recognised and listed in the omz plugin list. Highlighting works on the prompt but not inside any editors i have (vi, nano etc).

<img width="246" alt="Screenshot 2022-07-14 at 16 48 41" src="https://user-images.githubusercontent.com/1905808/179023729-a30d4a24-f3f5-4d3b-9b36-920135144379.png">

Any suggestions at to where to look would be great.

Thanks

**Comment by danielshahaf** [comment]
z-sy-h only highlights input at zsh's prompt.  It does not interact with your $EDITOR in any way.  You'll want to look in your $EDITOR's documentation for how to enable syntax highlighting.  Good luck!
