### ISSUE TITLE
Arithmetic evaluation always highlights the first argument as unknow/wrong

### ISSUE THREAD

**Issue by Iskustvo** [zsh-users/zsh-syntax-highlighting#888]
Steps to reproduce:
* Start the zsh in new terminal emulator, without any configuration
  ```zsh
  termite -e 'zsh -dfi'
  ```
* Source z-sy-h from where it's installed, and use only the `main` highlighter
  ```zsh
  source "/usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
  ZSH_HIGHLIGHT_HIGHLIGHTERS=(main)
  ```
* Write simple arithmetic expession and observe incorrect highlighting for the first argument
![2022-08-13-180242_1920x1080_scrot](https://user-images.githubusercontent.com/23140889/184501850-25bebbbb-1beb-40b4-bcc5-dc9fea0fbeae.png)

Versions:
``` 
zsh - 5.9-1
zsh-syntax-highlighting - 0.7.1-1
```

**Comment by danielshahaf** [comment]
Fixed in master; could you confirm?

**Comment by Iskustvo** [comment]
Yes, it works as expected. Thanks!
