### ISSUE TITLE
scalar parameter ref created globally in function my_git_prompt_info

### ISSUE THREAD

**Issue by yanmxa** [zsh-users/zsh-syntax-highlighting#893]
After souce the ~/.zshrc. the terminal keeps echoing the following information in my centos. 
```
$ my_git_prompt_info:1: scalar parameter ref created globally in function my_git_prompt_info
```
I don't know how to fix it.

Refs: https://github.com/zsh-users/zsh-syntax-highlighting/issues/438

**Comment by danielshahaf** [comment]
It's a WARN_CREATE_GLOBAL warning (see the manual).

Chances are that function needs `local ref` added to it.

Closing since you don't even seem to use zsh-syntax-highlighting.
