### ISSUE TITLE
In termux on android it needs to be manually sourced

### ISSUE THREAD

**Issue by zabeiua** [zsh-users/zsh-syntax-highlighting#901]
I've got the the same setup on ubuntu, debian and 2 termuxes. It works as expected on ubuntu and debian, but in termux i need to have 'alias sou="source ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ' and "sou" in every tmux pane...

**Comment by danielshahaf** [comment]
So you have a file that contains a line of the form `alias sou="…"`?  Delete from that line everything except the part within double quotes.

**Comment by danielshahaf** [comment]
If that doesn't work, ask on the termux support channels.  Good luck.
