### ISSUE TITLE
[enhancement] Add highlighting for flags/options/arguments

### ISSUE THREAD

**Issue by AcinonXDev** [zsh-users/zsh-syntax-highlighting#903]
So instead of
<img width="697" alt="Suggestion_ScreenShot_Before" src="https://user-images.githubusercontent.com/88356560/202575263-423b8fdb-a703-4eb3-8760-b0838375b75f.png">
<img width="697" alt="Suggestion_ScreenShot_After" src="https://user-images.githubusercontent.com/88356560/202575275-d93d3827-fccb-4bb0-a8b7-853187f25c43.png">

**Comment by phy1729** [comment]
You seem to want `ZSH_HIGHLIGHT_STYLES[single-hyphen-option]=fg=yellow`; the full list of styles for the main highlighter is at https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/main.md .

**Comment by AcinonXDev** [comment]
Okay, I've set it up and it's working how I expected. Thanks!
