### ISSUE TITLE
TokyoNight-like colors for zsh-syntax-highlighting?

### ISSUE THREAD

**Issue by DitchComfort** [zsh-users/zsh-syntax-highlighting#905]
Does anyone know of a Tokyo Night color scheme for zsh-syntax-highlighting? Or at least some matching colors?

Thank you.

**Comment by danielshahaf** [comment]
Doesn't ring a bell.

Closing as inactionable (the issue tracker is our todo list), but feel free to continue discussion.  (Perhaps over at https://github.com/zsh-users/zsh-syntax-highlighting/discussions?)
