### ISSUE TITLE
Plug-in stuck

### ISSUE THREAD

**Issue by Snowfly-Guo** [zsh-users/zsh-syntax-highlighting#910]
Hello, my wsl2 will be very stuck after installing the zsh-syntax-highlighting plugin using oh-my-zsh. Is there any solution, Thank
https://user-images.githubusercontent.com/79904577/208241760-46fe31f0-ceb5-4df4-a398-f2de01016980.gif

***ADMIN EDIT: inline video moved to a link***

**Comment by danielshahaf** [comment]
I'm moved your video to a link because it was moving.

Please don't use videos unless absolutely necessary.

Duplicate of #790.
