### ISSUE TITLE
Highlighting Very Slow when using man

### ISSUE THREAD

**Issue by EliSauder** [zsh-users/zsh-syntax-highlighting#917]
I just went to run `man git` and my terminal hung for close to a second, then displayed the text I ran. When I disable the sourced script in my config everything runs fine. Additionally, every time I type a letter, the terminal hangs, then syntax highlighting will show up.

**Comment by danielshahaf** [comment]
Works for me.  Post reproduction instructions starting with `zsh -f` and using no external dependencies.  Include version numbers of zsh, z-sy-h, and your OS.  Review already-filed issues (primarily but not only those with the `performance` label) to see if this has already been reported.

**Comment by EliSauder** [comment]
Ohp, wrong repo. My appologies.
