### ISSUE TITLE
Getting error in installing

### ISSUE THREAD

**Issue by ritamgit-alt** [zsh-users/zsh-syntax-highlighting#918]
why am I getting this error? did I do anything wrong?

`[oh-my-zsh] plugin 'zsh-syntax-highlighting' not found`

tried several times to install it like this but getting error again and again.

```
plugins=(git
zsh-autosuggestions
zsh-syntax-highlighting
)
```
need some help in here!

**Comment by soryeigeton** [comment]
```
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
```

try to run the git commands , and then after that go to `/.oh-my-zsh/custom/plugins`, make sure the plugins is there. after that if all set u can restart ur terminal and also dont forget to `source ~/.zshrc`

**Comment by ritamgit-alt** [comment]
tried but ain't working.

**Comment by soryeigeton** [comment]
you still receiving the same error? have you tried `source ~/.zshrc`? or maybe close and open the terminal again? what OS or terminal did you use?

**Comment by ritamgit-alt** [comment]
Yep having the same error. I use MacOS

**Comment by soryeigeton** [comment]
what terminal did you use?, have you installed something like ohmyzsh?

**Comment by ritamgit-alt** [comment]
It's zsh terminal and ohmyzsh installed too.

**Comment by ritamgit-alt** [comment]
zsh-autosuggestions perfectly working fine but having error with  zsh-syntax-highlighting.

**Comment by soryeigeton** [comment]
maybe u can try to remove the zsh-syntax-highlighting folder in plugins folder, and then after that redo the git clone

**Comment by soryeigeton** [comment]
i have the same setup and its working fine

**Comment by ritamgit-alt** [comment]
> maybe u can try to remove the zsh-syntax-highlighting folder in plugins folder, and then after that redo the git clone

I'm gonna try this too. Hope this works

**Comment by ritamgit-alt** [comment]
thanks, man. It's working fine now🤗
