### ISSUE TITLE
how do i disable "sudo" underline

### ISSUE THREAD

**Issue by n11dc0la** [zsh-users/zsh-syntax-highlighting#921]
Dear all:

        I want to disable "sudo" underline, and change that colour

**Comment by danielshahaf** [comment]
Change the value of ${ZSH_HIGHLIGHT_STYLES[precommand]} as explained in the documentation.

**Comment by n11dc0la** [comment]
> Change the value of ${ZSH_HIGHLIGHT_STYLES[precommand]} as explained in the documentation.

Thats worked, thx man
