### ISSUE TITLE
file names and settings in docs don't match actual settings in files

### ISSUE THREAD

**Issue by heafnerj** [zsh-users/zsh-syntax-highlighting#923]
I am using `zsh-syntax-highlighting` in `oh-my-zsh` on macOS Catalina and Ventura and am trying to customize some things. The plugin works, but the problem is that the information in the docs does not match the corresponding file names and variable names in the files in my distribution. I my `.zshrc` file I cannot load the plugin as `zsh-syntax-highlighting`, I must use `fast-syntax-highlighting` because the former causes a crash when I launch my Terminal. The docs for customizing `ZSH_HIGHLIGHT_STYLES` seem straightforward but in the file `fast-highlight` the variable is named `FAST_HIGHLIGHT_STYLES`. I've been trying to simply customized `ZSH_HIGHLIGHT_STYLES[path]` and nothing works. Am I missing something very obvious?

**Comment by heafnerj** [comment]
I found the problem! I had copied the plugin's repo from another machine using the name `fast-syntax-highlighting` instead of `zsh-syntax-highlighting`. I guess the name changed sometime in the past and I didn't catch it. Configuration works perfectly now. I apologize for opening this issue, but I was out of options at the time. Thank you for this wonderful software!

**Comment by danielshahaf** [comment]
Glad you solved it.  For future reference:

- fast-syntax-highlighting is a fork of zsh-syntax-highlighting.

- Regarding the "crash" when opening a new terminal, the way to debug that is to run `zsh` without arguments from another shell (or to configure the terminal emulator / pty not to close the tab when the program therein exits).

**Comment by heafnerj** [comment]
Thank you for clearing up the fork issue (I wasn't sure which was the original), and thanks for the debugging tip too.
