### ISSUE TITLE
How to highlight the whole buffer

### ISSUE THREAD

**Issue by blueray453** [zsh-users/zsh-syntax-highlighting#927]
I am trying to use ctrl+a to highlight the whole buffer.

Here is my zle widget.

```
autoload -Uz region_highlight
zle -N region_highlight

_ctrl-a() {
  ((CURSOR = 0))
  ((MARK = $#BUFFER))
  zle region_highlight
}

zle -N _ctrl-a
bindkey '^A' _ctrl-a # Ctrl+A
```

When i press ctrl+a , it says `_zsh_autosuggest_invoke_original_widget:9: region_highlight: function definition file not found`

What is the issue here?

**Comment by phy1729** [comment]
This isn't really a zsh-syntax-highlighting question, but `region_highlight` is an array in ZLE widgets not a function. For further questions on ZLE widgets, you might try the users mailing list or the IRC channel on libera.
