### ISSUE TITLE
Console log JSON

### ISSUE THREAD

**Issue by lobosan** [zsh-users/zsh-syntax-highlighting#932]
Hi, I'm console logging a JSON but the text is all white.

<img width="464" alt="image" src="https://github.com/zsh-users/zsh-syntax-highlighting/assets/314886/d2f7b406-532f-427c-b295-01ffb812f7f8">

However, I would like to see it with colors like the following picture, where numbers are yellow, strings are green and timestamp is purple

<img width="784" alt="image" src="https://github.com/zsh-users/zsh-syntax-highlighting/assets/314886/e9e8d1d7-8138-4eaf-9c0a-04dadb55d3cf">

**Comment by phy1729** [comment]
zsh-syntax-highlighting highlights commands typed on the zsh command line. It does not (and cannot really) highlight the output of commands as that is written directly to the terminal. There exist other projects to colorize the output of commands they wrap or text from stdin. You might try seeing if one of those will suit your needs.

**Comment by lobosan** [comment]
@phy1729 thanks for the clarification.
Can you please recommend some projects to colorize the output of commands?
