### ISSUE TITLE
Installation documentation incomplete

### ISSUE THREAD

**Issue by ferenczy** [zsh-users/zsh-syntax-highlighting#935]
I'm running the latest oh-my-zsh on Zsh 5.8.1 on Ubuntu 21.04. I have installed the plugin using the `zsh-syntax-highlighting` DEB package as it's the most convenient method (rather than manually cloning a Git repo and keeping it up-to-date). Then, I have added `zsh-syntax-highlighting` to the `plugins` array in my `.zshrc`, but oh-my-zsh reported the plugin to be not found.

So I have checked the [`Install.md` file](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md), the _Using packages_ section, but it doesn't mention anything else apart from the installation of the package itself.

So I have checked the content of the DEB package to find out, where's the plugin script file located (it's the directory `/usr/share/zsh-syntax-highlighting/`) and manually added the following line to the end of my `.zshrc`:

    source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

So, shouldn't be such information added to the [`Install.md` file](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md) file? The installation wasn't straightforward (at least for a regular user) and it required compilation of information from various sources, even though, my method (running oh-my-zsh and installing the package using the DEB package) is probably the most common, I would say.

**Comment by danielshahaf** [comment]
Agreed that the sentence about "directing [one's] users to add [that 'source' statement] to their `.zshrc`s" is applicable to all installation methods (except distros that install a /etc/zshrc.d/zsh-syntax-highlighting thingy, if they exist) and should be moved in INSTALL.md accordingly.

I think the package's README.Debian file documents this too.

Excuse brevity.

**Comment by phy1729** [comment]
I think #830 covers this. If so I think it's timed out on the original contributor, so I'll just rebase to one commit myself.

**Comment by phy1729** [comment]
I think this is closed by 6507190.
