### ISSUE TITLE
Homebrew link 404

### ISSUE THREAD

**Issue by HowieG** [zsh-users/zsh-syntax-highlighting#937]
https://github.com/zsh-users/zsh-syntax-highlighting/blob/1386f1213eb0b0589d73cd3cf7c56e6a972a9bfd/INSTALL.md?plain=1#L21

Link to Homebrew formula is broken. Homebrew added folders for each letter of the alphabet so this link now needs a '/z/'

https://github.com/Homebrew/homebrew-core/blob/master/Formula/z/zsh-syntax-highlighting.rb

**Comment by phy1729** [comment]
Thanks for pointing this out. Fixed.

**Comment by HowieG** [comment]
That was so fast damn
