### ISSUE TITLE
login user name disappeared after installing zsh-syntax in linux console !!

### ISSUE THREAD

**Issue by SteveJobsCousin** [zsh-users/zsh-syntax-highlighting#941]
### **how i can return to the default without removing zsh-syntax-highlighting  ?**

> ### my linux distro is ( Ubuntu Server LTS - 22.04 )

**Comment by danielshahaf** [comment]
> usually my linux console text area will look like :
> ***@***.***:~$                                           `
>
> now its just look like : 
> `~                                                                `
> which is confusing to me when switching between multiple users ...
>
> **how i can return to the default without removing zsh-syntax-highlighting  ?**

This issue is entirely independent of zsh-syntax-highlighting.  Ask on zsh support channels.  Good luck.

(Something in your setup changes the value of $PS1 aka $PROMPT.)
