### ISSUE TITLE
Slows down termonal in run time

### ISSUE THREAD

**Issue by ianTevesAcc** [zsh-users/zsh-syntax-highlighting#960]
This plugin has been working pretty well so far. but today it suddenly became very slow at run time.

I don't know where to start in order to diagnose the problem, but if someone can point me in the right direction to find out the cause, that would be so helpful.

**Comment by trallnag** [comment]
Is it slow all the time? Does restarting help?

**Comment by ianTevesAcc** [comment]
Sorry for the late update. 

I gave up and just factory reset my whole pc after backing up all my files. It works now.
Im guessing its a wsl issue in wsl1. As I switched to wsl 1 then switched to wsl2 after the factory reset and have encountered no issues with it ever since.
