### ISSUE TITLE
"Beep" on every char I type

### ISSUE THREAD

**Issue by tscolari** [zsh-users/zsh-syntax-highlighting#98]
I'm having a strange issue when using zsh-syntax-highlighting.
It's working, but every time I type a char it fires a 'beep' sound.
When I disable the plugin, the beeps stop.

Any idea what could cause this or how I could debug it?

I'm using MacOS with prezto.

**Comment by danielshahaf** [comment]
Closing as duplicate. Reopen if it still happens.
